[[usb-mass-storage-boot]]
== USB大容量存储启动

NOTE: 适用于 xref:raspberry-pi.adoc#compute-module-series[自 Compute Module 3 起的 Compute Module 系列]、xref:raspberry-pi.adoc#zero-series[自 Zero 2 W 起的 Zero 系列] 和 xref:raspberry-pi.adoc#flagship-series[自 Raspberry Pi 2B（1.2 版）起的所有旗舰系列设备]。

USB 大容量存储启动让您可以从闪存盘或 USB 磁盘等 USB 大容量存储设备启动 Raspberry Pi。在连接 USB 设备（尤其是硬盘和固态硬盘）时，请注意它们的电源要求。连接一个以上的磁盘通常需要额外的外部电源，这些电源可以来自供电的磁盘盒或供电的 USB 集线器。

NOTE: Models prior to Raspberry Pi 4B have known issues which prevent booting with some USB devices.

=== 带有 EEPROM 引导加载程序的设备

[[pi4]]

[[cm4]]

只要在 xref:raspberry-pi.adoc#BOOT_ORDER[`BOOT_ORDER`] 配置中指定 USB 启动，Raspberry Pi 4 和更新的旗舰系列设备以及 Compute Module 4 和 4S 之后的 Compute Module 设备默认支持 USB 启动。

NOTE: 早期版本的 Raspberry Pi 4 可能需要 xref:raspberry-pi.adoc#raspi-config[bootloader update] 才能从 USB 启动。

NOTE: 早期版本的 Compute Module 4 可能需要 xref:compute-module.adoc#update-the-compute-module-bootloader[bootloader update] 才能从 USB 启动。


[[raspberry-pi-3b]]
=== Raspberry Pi 3B+

Raspberry Pi 3B++支持直接使用USB大容量存储启动。

[[raspberry-pi-2b-3a-3b-cm3-cm3-zero-2-w]]
=== Raspberry Pi 2B, 3A+, 3B, CM3, CM3+, Zero 2 W

在 Raspberry Pi 2B v1.2、3A+、3B、Zero 2 W 以及 Compute Module 3 和 3+上，必须首先启用 xref:raspberry-pi.adoc#usb-host-boot-mode[USB主机启动模式]。这允许 USB 大容量存储器启动和 xref:raspberry-pi.adoc#network-booting[网络启动]。

NOTE: Raspberry Pi 3A+或Zero 2 W不支持网络启动。

要在这些设备上启用 USB 主机启动模式，请在 OTP（一次性可编程）内存中设置 USB 主机位。要设置该位，请从 SD 卡启动，其中 xref:config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`] 包含 `program_usb_boot_mode=1` 行。一旦设置了该位，就可以不使用 SD 卡而通过 USB 启动。


==== 启用带 OTP 的 USB 主机启动模式

[WARNING]
====
对 OTP（一次性可编程）内存所做的任何更改都是永久性的，无法撤销。

在 Raspberry Pi 3A+ 上，设置 OTP 位以启用 USB 主机启动模式将永久阻止 Raspberry Pi 以 USB 设备模式启动。
====

使用任何已刷新 Raspberry Pi OS 的 SD 卡来编程 OTP 位。

要启用 USB 主机启动模式，请在 `config.txt` 中添加以下一行：

[source,ini]
----
program_usb_boot_mode=1
----

然后，使用 `sudo reboot` 重启 Raspberry Pi。要检查 OTP 编程是否正确，请运行以下命令：

[source,console]
----
$ vcgencmd otp_dump | grep 17:
17:3020000a
----

检查是否显示输出 `0x3020000a` 。如果不是，则说明OTP位没有成功编程。在这种情况下，请再次进行编程过程。如果该位仍未设置，这可能表明Raspberry Pi硬件本身存在故障。


您现在可以像从SD卡启动一样从USB大容量存储设备启动。有关详细信息，请参阅以下部分。

[[booting-from-usb-mass-storage]]
=== 从USB大容量存储启动

xref:getting-started.adoc#installing-the-operating-system[过程] 与SD卡相同 - 只需将USB存储设备镜像为操作系统镜像。

准备好存储设备后，连接驱动器并启动Raspberry Pi，同时了解外部驱动器的额外USB电源要求。

5到10秒后，Raspberry Pi应该开始启动并在连接的显示器上显示彩虹启动屏幕。确保您没有在Raspberry Pi中插入SD卡，因为如果您这样做了，它将首先启动。

请参阅 xref:raspberry-pi.adoc#raspberry-pi-boot-modes[引导模式文档] 了解引导顺序和替代引导模式（网络、USB设备、GPIO或SD引导）。

=== 已知问题

 
* 检查可启动USB设备的默认超时时间为两秒。一些闪存驱动器和硬盘启动速度太慢。可以将此超时时间延长至五秒（向SD卡添加新文件 `timeout` ），但请注意，某些设备需要更长的时间才能响应。
* 某些闪存驱动器具有非常特定的协议要求，引导代码无法处理，因此可能不兼容。

=== 指定的 `bootcode.bin` -仅引导模式

IMPORTANT: 这 *不* 适用于Raspberry Pi 4 Model B。

如果您无法使用特定的USB设备来启动Raspberry Pi，另一种选择（适用于Raspberry Pi2Bv1.2、3A+、3B和3B+）是使用特殊的 xref:raspberry-pi.adoc#raspberry-pi-boot-modes[`bootcode.bin-only`] 启动模式。Raspberry Pi仍将从SD卡启动，但 `bootcode.bin` 是唯一从中读取的文件。

[[hardware-compatibility]]
=== 硬件兼容性

在尝试从USB大容量存储设备启动之前，建议验证设备在Linux下是否正常工作。使用SD卡启动并插入USB大容量存储设备。这应该显示为可移动驱动器。这对于USB SATA适配器尤其重要，引导加载程序在大容量存储模式下可能支持它，但如果Linux选择 https://en.wikipedia.org/wiki/USB_Attached_SCSI[USB Attached SCSI-UAS]，则会失败。

机械硬盘几乎总是需要一个供电的 USB 集线器。即使看起来一切正常，如果没有供电的 USB 集线器，也可能会遇到间歇性故障。

[[multiple-bootable-drives]]
=== 多个可启动驱动器

在搜索可启动分区时，引导程序会并行扫描所有 USB 大容量存储设备，并选择第一个作出响应的设备。如果引导分区不包含合适的 `start.elf` 文件，则会选择下一个可用设备。  没有根据 USB 拓扑指定启动设备的方法，因为这会减慢启动速度，并增加不必要且难以支持的复杂配置。

NOTE:  `config.txt` 文件 xref:config_txt.adoc#conditional-filters[条件筛选器] 可用于在复杂设备配置中选择备用固件。
