== 引导顺序

IMPORTANT: 以下启动顺序仅适用于基于 BCM2837 和 BCM2837B0 的 Raspberry Pi 型号。在此之前的型号上，Raspberry Pi 将尝试使用 SD 卡启动，然后使用 xref:raspberry-pi.adoc#usb-device-boot-mode[USB 设备模式启动]。有关 Raspberry Pi 4 和 Raspberry Pi 5 的启动顺序，请参阅 xref:raspberry-pi.adoc#eeprom-boot-flow[EEPROM 启动流程] 部分。

Raspberry Pi 3 上的 USB 启动默认值取决于使用的版本。有关在默认情况下未启用 USB 启动模式的信息，请参阅 xref:raspberry-pi.adoc#usb-mass-storage-boot[page] 。

当 BCM2837 启动时，它会使用两个不同的来源来确定要启用哪些启动模式。首先，检查一次性可编程 (OTP) 存储器块，查看启用了哪些启动模式。如果启用了 GPIO 启动模式设置，则会测试相关的 GPIO 线路，以选择应尝试哪些启用了 OTP 的启动模式。请注意，GPIO 启动模式只能用于选择 OTP 中已启用的启动模式。有关配置 GPIO 启动模式的详情，请参阅 xref:raspberry-pi.adoc#gpio-boot-mode[GPIO 启动模式]。GPIO 启动模式默认为禁用。

接下来，引导 ROM 会检查每个引导源是否有一个名为 `bootcode.bin` 的文件；如果有，它就会将代码加载到本地 128K 缓存中并跳转到该文件。整个启动模式过程如下：

* BCM2837 启动
* 读取 OTP 以确定要启用的启动模式
* 如果启用了 GPIO 启动模式，则使用 GPIO 启动模式完善启用的启动模式列表
* 如果已启用：检查 GPIO 48-53 上主 SD 的 bootcode.bin
 ** 成功 - 启动
 ** 失败 - 超时（五秒）
* 如果启用：检查辅助 SD
 ** 成功 - 启动
 ** 失败 - 超时（五秒）
* 如果启用：检查 NAND
* 如果启用：检查 SPI
* 如果启用：检查 USB
 ** 如果 OTG 引脚 == 0
  *** 启用 USB，等待有效的 USB 2.0 设备（两秒）
   **** 找到设备：
    ***** 如果设备类型 == 集线器
     ****** 搜索每个端口
    ***** 如果设备类型 == （大容量存储器或 LAN951x）
     ****** 存储在设备列表中
  *** 对每个 MSD 进行递归
   **** 如果发现 bootcode.bin 引导
  *** 对每个 LAN951x 进行搜索
   **** DHCP / TFTP 启动
 ** 否则（设备模式启动）
  *** 启用设备模式并等待主机 PC 枚举
  *** 我们回复电脑的 VID: `0a5c` PID: `0x2763` (Raspberry Pi 1 或 Raspberry Pi 2) 或 `0x2764` (Raspberry Pi 3)


[NOTE]
====
* 如果没有插入 SD 卡，SD 启动模式需要 5 秒钟才能失效。为了减少这种情况并更快地回到 USB 模式，可以插入一张没有任何内容的 SD 卡，或者使用上述 GPIO 启动模式 OTP 设置只启用 USB。
* GPIO 的默认值在 https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf[ARM 外围设备datasheet] 第 102 页进行了定义。如果启动时的值不等于默认值，则启用该启动模式。
* USB 枚举是一种向集线器上的下游设备供电的方法，然后等待设备拉动 D+ 和 D- 线，以显示它是 USB 1 还是 USB 2。 这可能需要一些时间：在某些设备上，硬盘驱动器旋转和启动枚举过程可能需要长达三秒钟的时间。因为这是检测硬件是否已连接的唯一方法，所以我们必须等待最短的时间（两秒）。如果设备在最长超时后仍未响应，可以使用 `config.txt` 中的 `program_usb_boot_timeout=1` 将超时时间延长至五秒。
* MSD 启动优先于以太网启动。
* 第一个分区不再必须是 FAT 分区，因为 MSD 启动将继续搜索第一个分区以外的 FAT 分区。
* 启动 ROM 现在还支持 GUID 分区，并已使用 Mac、Windows 和 Linux 对硬盘进行了分区测试。
* 使用供应商ID `0x0424` 和产品ID `0xec00` 检测LAN951x：这与独立LAN9500设备不同，后者的产品ID为 `0x9500` 或 `0x9e00`。 要使用独立 LAN9500，需要添加 I2C EEPROM 以更改这些 ID，使其与 LAN951x 匹配。
====

主 SD 卡启动模式按标准设置为 GPIO 49-53。可以通过第二组引脚从 SD 卡启动，即在 GPIO 引脚上添加 SD 卡。不过，我们尚未启用这一功能。

NAND 启动和 SPI 启动模式虽然还不能完全支持 GPU，但也能正常工作。

USB 设备启动模式在生产时默认已启用，但 USB 主机启动模式只有在 `program_usb_boot_mode=1` 时才能启用。启用后，处理器将使用处理器上 OTGID 引脚的值来决定这两种模式。在任何 Raspberry Pi Model B/B+ 上，OTGID 引脚都被驱动为 0，因此一旦启用，将只能通过主机模式启动（由于 LAN951x 设备的阻碍，无法通过设备模式启动）。

如果 OTGID 引脚处于浮动状态（例如插入 PC 时），USB 将在 Raspberry Pi Zero 或 Compute Module 上作为 USB 设备启动，因此您可以将 `bootcode.bin` 添加到该设备。这样做的 `usbboot` 代码是 https://github.com/raspberrypi/usbboot[可在 GitHub 上获取]。

