[[gpio-boot-mode]]
== GPIO启动模式

NOTE: GPIO启动模式仅适用于Raspberry Pi 3A+、3B、3B+、Compute Module 3和3+。

早期的Raspberry Pis可以配置为允许使用连接到GPIO连接器的硬件在开机时选择引导模式。这是通过在SoC的OTP内存中设置位来完成的。一旦设置了这些位，它们就会永久分配五个GPIO以允许进行此选择。一旦设置了OTP位，它们就不能被取消设置。您应该仔细考虑启用此功能，因为这五个GPIO线将始终控制引导。虽然一旦Raspberry Pi启动，您可以将GPIO用于其他一些功能，但您必须设置它们，以便它们在Raspberry Pi启动时启用所需的引导模式。

要启用GPIO启动模式，请将以下行添加到 `config.txt` 文件中：

[source,ini]
----
program_gpio_bootmode=n
----

其中 `n` 是您希望使用的 GPIO 组。然后重启一次 Raspberry Pi，用此设置对 OTP 进行编程。第 1 组是 GPIO 22-26，第 2 组是 GPIO 39-43。除非您有 Compute Module，否则必须使用第 1 组：第 2 组中的 GPIO 仅在 Compute Module 上可用。由于 OTP 位的排列方式，如果首先为第 1 组 的 GPIO 启动模式编程，那么稍后就可以选择第 2 组。反之则不行：一旦为 GPIO 启动模式选择了第 2 组，就不能再选择第 1 组。

启用GPIO启动模式后，Raspberry Pi将不再启动。您必须拉起至少一个启动模式GPIO引脚才能让Raspberry Pi启动。

=== 引脚分配

==== Raspberry Pi 3B 和 Compute Module 3

[cols="^,^,^"]
|===
| Bank 1 | Bank 2 | 引导类型

| 22
| 39
| SD0

| 23
| 40
| SD1

| 24
| 41
| NAND (no Linux support at present)

| 25
| 42
| SPI (no Linux support at present)

| 26
| 43
| USB
|===

上表中的USB同时选择USB设备启动模式和USB主机启动模式。为了使用USB启动模式，必须在OTP内存中启用它。有关详细信息，请参阅 xref:raspberry-pi.adoc#usb-device-boot-mode[USB设备启动] 和 xref:raspberry-pi.adoc#usb-host-boot-mode[USB主机启动]。

==== 后来的 Raspberry Pi 3B（带金属盖的 BCM2837B0）、Raspberry Pi 3A+、3B+ 和Compute Module 3+

[cols="^,^,^"]
|===
| Bank 1 | Bank 2 | 引导类型

| 20
| 37
| SD0

| 21
| 38
| SD1

| 22
| 39
| NAND (no Linux support at present)

| 23
| 40
| SPI (no Linux support at present)

| 24
| 41
| USB device

| 25
| 42
| USB host - mass storage device

| 26
| 43
| USB host - Ethernet
|===

NOTE: 按照GPIO线的数字顺序尝试各种引导模式，即SD0、SD1、NAND等。

[[boot-flow]]
=== Boot flow

SD0 是 Broadcom SD 卡/MMC 接口。SoC 内的启动 ROM 运行时，总是将 SD0 连接到内置 microSD 卡插槽。在带有 eMMC 设备的 Compute Modules 上，SD0 与 eMMC 设备相连；在 Compute Modules Lite 上，SD0 位于边缘连接器上，与 CMIO 载板上的 microSD 卡插槽相连。SD1 是 Arasan SD 卡/MMC 接口，也能使用 SDIO。所有内置无线局域网的 Raspberry Pi 型号都使用 SD1 通过 SDIO 连接到无线芯片。

GPIO 线路的默认上拉电阻为 50KΩ，如 https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf[BCM2835 ARM 外围设备datasheet] 第 102 页所述。建议将 GPIO 线路的上拉电阻设为 5KΩ：这将让 GPIO 正常工作，也不会消耗过多的功率。
