[[http-boot]]
== HTTP启动

网络安装功能通过以太网使用 HTTP 在 Raspberry Pi 上安装系统 xref:getting-started.adoc#raspberry-pi-imager[Raspberry Pi Imager]。

除了网络安装之外，您还可以使用通过 HTTP下载的文件显式引导设备，并使用 xref:raspberry-pi.adoc#BOOT_ORDER[boot-mode] `7` 。即使 xref:raspberry-pi.adoc#NET_INSTALL_ENABLED[启动时的网络安装被禁用]，您仍然可以使用它。

例如，您可以将其作为后备引导方法添加到您的 `BOOT_ORDER` 中，或者将其放在GPIO条件之后，以便在GPIO引脚拉低时从您自己的服务器启动 HTTP引导。

例如，如果您将以下内容添加到EEPROM配置中，并且GPIO 8（默认状态为1或HIGH）被拉低，则文件 `http://downloads.raspberrypi.org:80/net_install/boot.img` 和 `http://downloads.raspberrypi.org:80/net_install/boot.sig` 将被下载。如果启动时启用网络安装，它将使用相同的URL。如果GPIO 8没有被拉低，行为将保持不变。


[source,ini]
----
[gpio8=0]
BOOT_ORDER=0xf7
HTTP_HOST=downloads.raspberrypi.org
NET_INSTALL_ENABLED=0
----

`boot.img` 和 `boot.sig` 签名文件是包含启动文件系统的内存盘。有关详细信息，请参阅 xref:config_txt.adoc#boot_ramdisk[boot_ramdisk].

如果启用了安全引导并且没有设置 xref:raspberry-pi.adoc#HTTP_HOST[HTTP_HOST]， `BOOT_ORDER` 中的 HTTP将被忽略。

[[requirements]]
=== 要求

要使用HTTP引导, xref:raspberry-pi.adoc#bootloader_update_stable[update] 到2022年3月10日或更高版本发布的引导加载程序。HTTP启动需要有线以太网连接。

要使用自定义CA证书，请将 xref:raspberry-pi.adoc#bootloader_update_stable[update] 到2024年4月5日或更高版本发布的引导加载程序。只有运行BCM2712 CPU的设备支持自定义CA证书。

[[keys]]
=== Keys

所有 HTTP下载都必须签名。引导加载程序包含默认主机 `fw-download-alias1.raspberrypi.com` 上文件的公钥。此密钥将用于验证网络安装镜像，_除非_您设置 xref:raspberry-pi.adoc#HTTP_HOST[HTTP_HOST]_并且_在EEPROM中包含公钥。这允许您在自己的服务器上托管Raspberry Pi网络安装镜像。

WARNING: 使用您自己的网络安装镜像需要您对镜像进行签名并将您的公钥添加到EEPROM。如果您随后应用公共EEPROM更新，您的密钥将丢失，需要重新添加。

https://github.com/raspberrypi/usbboot/blob/master/Readme.md[`USBBOOT`] 拥有编写公钥所需的所有工具。

使用以下命令将公钥添加到 EEPROM 中。`boot.conf` 包含你的修改：

[source,console]
----
$ rpi-eeprom-config -c boot.conf -p mypubkey.pem -o pieeprom.upd pieeprom.original.bin
----

使用以下命令为 EEPROM 生成签名：

[source,console]
----
$ rpi-eeprom-digest -i pieeprom.upd -o pieeprom.sig
----

然后，使用以下命令用私钥签署网络安装映像：

[source,console]
----
$ rpi-eeprom-digest -i boot.img -o boot.sig -k myprivkey.pem
----

最后，将 `boot.img` 和 `boot.sig` 放在网络服务器上，以使用自己签名的网络安装映像。

[[certificates]]
=== 证书

为了安全起见，Network Install使用 HTTPS从Raspberry Pi网站下载操作系统镜像。此功能使用引导加载程序中包含的我们自己的CA根目录来验证主机。

您可以将您自己的自定义CA证书添加到您的设备EEPROM，以安全地从您自己的网站下载图像。使用 `rpi-eeprom-config` 的 `--cacertder` 选项添加DER编码的证书。您必须在EEPROM配置设置中放置证书的哈希值，以确保证书不被修改。

运行以下命令以生成DER编码的证书：

[source,console]
----
$ openssl x509 -in your_ca_root_cert.pem -out cert.der -outform DER
----

然后，运行以下命令生成证书的SHA-256哈希：

[source,console]
----
$ sha256sum cert.der
----

您应该会看到类似于以下内容的输出：

----
701bd97f67b0f5483a9734e6e5cf72f9a123407b346088638f597878563193fc  cert.der
----

接下来，更新 `boot.conf` 以包含证书的哈希值：

[source,console]
----
$ sudo rpi-eeprom-config --edit
----

在 `[gpio8=0]` 部分配置以下设置，替换：

* `<your_website>` 与 xref:raspberry-pi.adoc#HTTP_HOST[您的网站]，例如 `yourserver.org` 
* `<path_to_files>` 与 xref:raspberry-pi.adoc#HTTP_PATH[路径到您的操作系统镜像] 托管在您的网站上，例如 `path/to/files` 
* `<hash>` 与您上面生成的哈希值，例如 `701bd97f67b0f5483a9734e6e5cf72f9a123407b346088638f597878563193fc` 

[source,ini]
----
[all]
BOOT_UART=1
POWER_OFF_ON_HALT=0
BOOT_ORDER=0xf461

[gpio8=0]
BOOT_ORDER=0xf7
NET_INSTALL_ENABLED=0
HTTP_HOST=<your_website>
HTTP_PATH=<path_to_files>
HTTP_CACERT_HASH=<hash>
----

当您指定 `HTTP_CACERT_HASH` 时，Network Install通过端口443使用 HTTPS下载镜像。如果没有哈希，Network install通过端口80使用 HTTP下载镜像。

最后，使用以下命令将所有内容加载到 EEPROM 中：

[source,console]
----
$ rpi-eeprom-config -c boot.conf -p mypubkey.pem -o pieeprom.bin --cacertder cert.der pieeprom.original.bin
$ rpi-eeprom-digest -k myprivkey.pem -i pieeprom.bin -o pieeprom.sig
----

在网络启动期间，您的Raspberry Pi应该使用 HTTPS而不是 HTTP。要查看Network Install解析的完整 HTTPS URL以供下载，请检查启动输出：

----
Loading boot.img ...
HTTP: GET request for https://yourserver.org:443/path/to/files/boot.sig
HTTP: GET request for https://yourserver.org:443/path/to/files/boot.img
----

[[secure-boot]]
=== 安全启动

如果启用了安全启动，则Raspberry Pi只能运行由客户私钥签名的代码。因此，如果您想使用安全启动的网络安装或 HTTP启动模式，您必须签署 `boot.img` 并使用自己的密钥生成 `boot.sig` ，并将这些文件托管在某个地方以供下载。EEPROM中的公钥将用于验证镜像。

如果启用了安全引导并且未设置 xref:raspberry-pi.adoc#HTTP_HOST[HTTP_HOST]，则将禁用网络安装和 HTTP引导。

有关安全启动的更多信息，请参见 https://github.com/raspberrypi/usbboot/blob/master/secure-boot-recovery/README.md[`USBBOOT`]。
