[[nvme-ssd-boot]]
== NVMe SSD启动

NVMe（Non-Volatile Memory express）是通过 PCIe 总线访问外部存储的标准。您可以通过计算模块 4 IO 板上的 PCIe 插槽、计算模块 5 IO 板上的 M.2 插槽以及使用 M.2 HAT+ 的 Raspberry Pi 5 连接 NVMe 硬盘。通过一些额外的配置，您可以从 NVMe 驱动器启动。

=== 先决条件

[[hardware]]
==== 硬件

* NVMe M.2 SSD
* 从PCIe转换为M.2标准的适配器。
** 对于Raspberry Pi 5，我们推荐 xref:../accessories/m2-hat-plus.adoc[M.2 HAT+]，它从Raspberry Pi的 *PCIe FFC* 插槽转换为M Key接口。
** 对于CM4，搜索"PCI-E 3.0×1 通道到 M.2 NGFF M-Key SSD NVMe PCI Express适配器卡"

要检查您的NVMe驱动器连接是否正确，请从另一个存储设备（例如SD卡）启动Raspberry Pi并运行 `ls -l /dev/nvme*` 。示例输出如下所示。

----
crw------- 1 root root 245, 0 Mar  9 14:58 /dev/nvme0
brw-rw---- 1 root disk 259, 0 Mar  9 14:58 /dev/nvme0n1
----

[[software]]
==== 软件

首先确保你的设备正在使用最新的软件，运行下面命令升级软件：

[source,console]
----
$ sudo apt update && sudo apt full-upgrade
----

=== Edit the bootloader boot priority

使用树莓派配置工具来更新bootloader：

[source,console]
----
$ sudo raspi-config
----

在 `Advanced Options` > `Bootloader Order` 下，指定引导加载程序应首先尝试从 `NVMe` 启动： 。

运行以下命令将固件更新到最新版本：

[source,console]
----
$ sudo rpi-eeprom-update -a
----

然后，使用 `sudo reboot` 重新启动。您的Raspberry Pi 应该从NVMe启动。

对于CM4，使用 `rpiboot` 更新引导加载程序。您可以在 https://github.com/raspberrypi/usbboot[USB boot GitHub存储库] 中找到构建 `rpiboot` 和配置IO板以将ROM切换到usbboot模式的说明。

对于带有 eMMC 的 CM4 版本，请确保在启动顺序中将 NVMe 设为第一。记住在 `recovery/boot.conf` 中的 `BOOT_ORDER` 中添加 NVMe 启动模式 `6` 。

当SD卡插槽为空时，CM4 Lite会自动从NVMe启动。

[[nvme-boot_order]]
=== NVMe  `BOOT_ORDER` 

EEPROM配置中的 `BOOT_ORDER` 设置控制引导行为。
对于NVMe引导，使用引导模式 `6` 。有关详细信息，请参阅 xref:raspberry-pi.adoc#raspberry-pi-bootloader-configuration[Raspberry Pi引导加载程序配置]。

=== 示例

以下是引导加载程序检测到NVMe驱动器时通用异步收发设备输出的示例：

----
Boot mode: SD (01) order f64
Boot mode: USB-MSD (04) order f6
Boot mode: NVME (06) order f
VID 0x144d MN Samsung SSD 970 EVO Plus 250GB
NVME on
----

然后它会找到一个FAT分区并加载 `start4.elf` ：

----
Read start4.elf bytes  2937840 hnd 0x00050287 hash ''
----

然后它将加载内核并启动操作系统：

----
MESS:00:00:07.096119:0: brfs: File read: /mfs/sd/kernel8.img
MESS:00:00:07.098682:0: Loading 'kernel8.img' to 0x80000 size 0x1441a00
MESS:00:00:07.146055:0:[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd083]
----

在Linux系统中 SSD显示为 `/dev/nvme0` ，命名空间显示为 `/dev/nvme0n1` 。将有两个分区 `/dev/nvme0n1p1` （FAT）和 `/dev/nvme0n1p2` （EXT4）。使用 `lsblk` 检查分区分配：

----
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 232.9G  0 disk
├─nvme0n1p1 259:1    0   256M  0 part /boot/firmware
└─nvme0n1p2 259:2    0 232.6G  0 part /
----

[[troubleshooting]]
=== 故障排除

如果启动过程失败，请在 https://github.com/raspberrypi/rpi-eeprom[rpi-eeprom GitHub存储库] 上提交问题，确保在启动期间附上控制台的副本和屏幕上显示的任何内容。
