== 网络启动

本节介绍如何在Raspberry Pi 3B、3B+ 和 2B v1.2上启动网络。

在 Pi 4 和 Pi 5 上，网络启动是通过 EEPROM 中的第二阶段引导加载器实现的。更多信息，请参阅 xref:raspberry-pi.adoc#raspberry-pi-bootloader-configuration[Raspberry Pi 引导加载器配置]。

我们还有一个 xref:remote-access.adoc#network-boot-your-raspberry-pi[关于设置网络引导系统的教程]。

网络引导仅适用于上述型号的Raspberry Pi内置的有线适配器。不支持通过无线LAN引导，也不支持从任何其他有线网络设备引导。

[[network-booting]]
=== 网络启动流程

要进行网络引导，引导ROM执行以下操作：

* 初始化板载以太网设备（微芯片LAN9500或LAN7500）
* 发送DHCP请求（供应商类别标识符DHCP选项60设置为 `PXEClient:Arch:00000:UNDI:002001` ）
* 收到DHCP回复
* 接收DHCP代理回复（可选）
* ARP到tftpboot服务器
* ARP回复包括tftpboot服务器以太网地址
* TFTP RRQ `bootcode.bin` 
 ** 找不到文件：服务器回复TFTP错误响应和文本错误消息
 ** 文件存在：服务器将回复文件的第一个数据块（512字节），标题中包含块号
  *** Raspberry Pi回复包含块号的TFTP确认字符包，并重复直到最后一个不是512字节的块
* TFTP RRQ `bootsig.bin` 
 ** 这通常会导致错误 `未找到文件` 。这是意料之中的，TFTP引导服务器应该能够处理它。

从这里开始， `bootcode.bin` 代码继续加载系统。它将尝试访问的第一个文件是 `<serial_number>/start.elf` 。如果这不会导致错误，那么任何其他要读取的文件都将附加 `serial_number` 。这很有用，因为它使您能够为Raspberry Pis创建具有单独 `start.elf` / 内核的单独目录。

要获取设备的序列号，你可以尝试这种启动模式，并使用 tcpdump / wireshark 查看访问了哪些文件，或者运行标准的 Raspberry Pi OS SD 卡并 `cat /proc/cpuinfo` 。

如果您将所有文件放入TFTP目录的根目录，则将从那里访问所有以下文件。

[[debugging-network-boot-mode]]
=== 调试网络启动模式

首先要检查的是OTP位是否正确编程。为此，您需要将 `program_usb_boot_mode=1` 添加到 `config.txt` 并重新启动（使用可以正确启动到Raspberry Pi OS的标准SD卡）。完成此操作后，您应该能够：

[source,console]
----
$ vcgencmd otp_dump | grep 17:
----

如果第17行包含 `3020000a` ，则OTP已正确编程。您现在应该能够取出SD卡，插入以太网，然后以太网LED应该在Raspberry Pi通电后大约5秒点亮。

要在服务器上捕获以太网数据包，请在tftpboot服务器（或DHCP服务器，如果它们不同）上使用tcpdump。您需要在那里捕获数据包，否则您将无法看到直接发送的数据包，因为网络交换机不是集线器！

[source,console]
----
$ sudo tcpdump -i eth0 -w dump.pcap
----

这会将eth0中的所有内容写入名为 `dump.pcap` 的文件。然后，您可以对数据包进行后处理或将其上传到cloud dshark进行通信。

==== DHCP请求/回复

您至少应该看到如下所示的DHCP请求和回复：

----
6:44:38.717115 IP (tos 0x0, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 348)
    0.0.0.0.68 > 255.255.255.255.67: [no cksum] BOOTP/DHCP, Request from b8:27:eb:28:f6:6d, length 320, xid 0x26f30339, Flags [none] (0x0000)
	  Client-Ethernet-Address b8:27:eb:28:f6:6d
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Discover
	    Parameter-Request Option 55, length 12:
	      Vendor-Option, Vendor-Class, BF, Option 128
	      Option 129, Option 130, Option 131, Option 132
	      Option 133, Option 134, Option 135, TFTP
	    ARCH Option 93, length 2: 0
	    NDI Option 94, length 3: 1.2.1
	    GUID Option 97, length 17: 0.68.68.68.68.68.68.68.68.68.68.68.68.68.68.68.68
	    Vendor-Class Option 60, length 32: "PXEClient:Arch:00000:UNDI:002001"
	    END Option 255, length 0
16:44:41.224619 IP (tos 0x0, ttl 64, id 57713, offset 0, flags [none], proto UDP (17), length 372)
    192.168.1.1.67 > 192.168.1.139.68: [udp sum ok] BOOTP/DHCP, Reply, length 344, xid 0x26f30339, Flags [none] (0x0000)
	  Your-IP 192.168.1.139
	  Server-IP 192.168.1.1
	  Client-Ethernet-Address b8:27:eb:28:f6:6d
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Offer
	    Server-ID Option 54, length 4: 192.168.1.1
	    Lease-Time Option 51, length 4: 43200
	    RN Option 58, length 4: 21600
	    RB Option 59, length 4: 37800
	    Subnet-Mask Option 1, length 4: 255.255.255.0
	    BR Option 28, length 4: 192.168.1.255
	    Vendor-Class Option 60, length 9: "PXEClient"
	    GUID Option 97, length 17: 0.68.68.68.68.68.68.68.68.68.68.68.68.68.68.68.68
	    Vendor-Option Option 43, length 32: 6.1.3.10.4.0.80.88.69.9.20.0.0.17.82.97.115.112.98.101.114.114.121.32.80.105.32.66.111.111.116.255
	    END Option 255, length 0
----

`Vendor-Option Option 43` 包含回复的重要部分，这必须包含字符串"Raspberry Pi Boot"，由于引导ROM中的bug，您可能需要在字符串末尾添加三个空格。

[[tftp-file-read]]
==== TFTP 文件读取

当供应商选项被正确指定时，您将看到一个后续的TFTP RRQ数据包正在发送。RRQ可以通过第一个数据块或错误说找不到文件来回复。在一些情况下，他们甚至收到了第一个数据包，然后Raspberry Pi中止了传输（当检查文件是否存在时会发生这种情况）。下面的示例只有三个数据包：原始读取请求、第一个数据块（总是516字节，包含一个排针和512字节的数据，尽管最后一个块总是小于512字节，可能是零长度）和第三个数据包（包含帧号以匹配数据块中的帧号的确认字符）。

----
16:44:41.224964 IP (tos 0x0, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 49)
    192.168.1.139.49152 > 192.168.1.1.69: [no cksum]  21 RRQ "bootcode.bin" octet
16:44:41.227223 IP (tos 0x0, ttl 64, id 57714, offset 0, flags [none], proto UDP (17), length 544)
    192.168.1.1.55985 > 192.168.1.139.49152: [udp sum ok] UDP, length 516
16:44:41.227418 IP (tos 0x0, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 32)
    192.168.1.139.49152 > 192.168.1.1.55985: [no cksum] UDP, length 4
----

[[known-problems]]
=== 已知问题

以太网启动模式存在许多已知问题。由于启动模式的实现是在芯片本身中，除了使用仅带有 `bootcode.bin` 文件的SD卡之外，没有其他变通方法。

[[dhcp-requests-time-out-after-five-tries]]
==== DHCP请求在五次尝试后超时

Raspberry Pi将尝试五次DHCP请求，其间间隔五秒，总共25秒。如果服务器在此期间无法响应，则Raspberry Pi将进入低功耗状态。除了SD卡上的bootcode.bin之外，没有其他解决方法。

[[tftp-server-on-separate-subnet-not-supported]]
==== 不支持单独子网上的TFTP服务器

在Raspberry Pi 3 Model B+（BCM2837B0）中修复。

[[dhcp-relay-broken]]
==== DHCP中继功能发生故障

DHCP检查还检查跳数值是否为 `1` ，这不会与DHCP中继一起使用。

在Raspberry Pi 3 Model B+中修复。

[[raspberry-pi-boot-string]]
==== 树莓派启动字符串

由于计算字符串长度时出错，DHCP回复中的 `Raspberry Pi Boot` 字符串需要额外的三个空格。

在Raspberry Pi 3 Model B+中修复。

[[dhcp-uuid-constant]]
==== DHCP UUID 不变

DHCP UUID 设置为常量值。

在Raspberry Pi 3 Model B+中修复；该值设置为32位序列号。

[[arp-check-can-fail-to-respond-in-the-middle-of-tftp-transaction]]
==== ARP 检查在 TFTP 事务中间可能无法响应

Raspberry Pi仅在初始化阶段响应ARP请求；一旦它开始传输数据，它将无法继续响应。

在Raspberry Pi 3 Model B+中修复。

==== DHCP请求/回复/确认序列未正确实现

在启动时,树莓派会广播一个DHCPDISCOVER数据包。DHCP服务器用一个DHCPOFFER数据包进行响应。但是树莓派接下来会继续启动,而不发送DHCPREQUEST或等待DHCPACK。这可能导致两个独立的设备被分配到同一个IP地址,并且同时使用该IP地址,而没有被正确地分配给客户端。

不同的DHCP服务器在这种情况下的行为也不尽相同。dnsmasq(取决于设置)会对MAC地址进行哈希运算来确定IP地址,并且会ping该IP地址以确保它没有被占用。这样做可以降低发生这种情况的可能性,因为它需要哈希值发生碰撞。
