== 显示并行接口 (DPI)

[.whitepaper, title="Using a DPI Display on the Raspberry Pi", subtitle="", link=https://pip.raspberrypi.com/categories/685-whitepapers-app-notes/documents/RP-003471-WP/Using-a-DPI-display.pdf]
****
显示器并行接口（DPI）显示器可以通过40-pin 通用输入/输出（GPIO）连接器连接到Raspberry Pi设备，作为使用专用显示串行接口（DSI）或高清多媒体接口（HDMI）端口的替代方案。
****

所有带有 40 路接头的 Raspberry Pi 电路板和计算模块都有一个 24 位的并行 RGB 接口。该接口允许将并行 RGB 显示器连接到 Raspberry Pi GPIO，可以是 RGB24（8 位红、绿、蓝）或 RGB666（每种颜色 6 位）或 RGB565（5 位红、6 位绿、5 位蓝）。

该接口由 GPU 固件控制，用户可通过指定的 `config.txt` 参数和启用正确的 Linux 设备树overlay对其进行修改。

[[gpio-pins]]
=== GPIO引脚

Raspberry Pi GPIO 第 0 组可选择的备用功能之一是 DPI（显示并行接口），它是一个简单的时钟并行接口（最多 8 位 R、G 和 B；时钟、使能、hsync 和 vsync）。该接口可作为 GPIO Bank 0 上的备用功能 2 (ALT2)：

[cols="1m,1m"]
|===
|GPIO |ALT2

|GPIO0
|PCLK

|GPIO1
|DE

|GPIO2
|LCD_VSYNC

|GPIO3
|LCD_HSYNC

|GPIO4
|DPI_D0

|GPIO5
|DPI_D1

|GPIO6
|DPI_D2

|GPIO7
|DPI_D3

|GPIO8
|DPI_D4

|GPIO9
|DPI_D5

|GPIO10
|DPI_D6

|GPIO11
|DPI_D7

|GPIO12
|DPI_D8

|GPIO13
|DPI_D9

|GPIO14
|DPI_D10

|GPIO15
|DPI_D11

|GPIO16
|DPI_D12

|GPIO17
|DPI_D13

|GPIO18
|DPI_D14

|GPIO19
|DPI_D15

|GPIO20
|DPI_D16

|GPIO21
|DPI_D17

|GPIO22
|DPI_D18

|GPIO23
|DPI_D19

|GPIO24
|DPI_D20

|GPIO25
|DPI_D21

|GPIO26
|DPI_D22

|GPIO27
|DPI_D23
|===

NOTE:  在 565、666 或 24 位模式下，有多种方式可以在 DPI 输出引脚上显示颜色值（请参阅下表和下面 `dpi_output_format` 参数中的 `output_format` 部分）：

[cols="1,1,^1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"]
|===
.2+h|*Mode* .2+h|*RGB bits* 24+h|*GPIO*
h|*27* h|*26* h|*25* h|*24* h|*23* h|*22* h|*21* h|*20* h|*19* h|*18* h|*17* h|*16* h|*15* h|*14* h|*13* h|*12* h|*11* h|*10* h|*9* h|*8* h|*7* h|*6* h|*5* h|*4*

|1
{set:cellbgcolor:!}
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-

|2
|565
|-
|-
|-
|-
|-
|-
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3

|3
{set:cellbgcolor:!}
|565
|-
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|-
{set:cellbgcolor:!}
|-
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|-
{set:cellbgcolor:!}
|-
|-
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3

|4
{set:cellbgcolor:!}
|565
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|-
{set:cellbgcolor:!}
|-
|-
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|-
{set:cellbgcolor:!}
|-
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3
|-
{set:cellbgcolor:!}

|5
|666
|-
|-
|-
|-
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|2
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3
|2

|6
{set:cellbgcolor:!}
|666
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|2
|-
{set:cellbgcolor:!}
|-
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|-
{set:cellbgcolor:!}
|-
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3
|2

|7
{set:cellbgcolor:!}
|888
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|2
|1
|0
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|1
|0
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3
|2
|1
|0

|===
{set:cellbgcolor:!}

[[disable-other-gpio-peripherals]]
=== 禁用其他GPIO外设

必须禁用所有其他使用冲突 GPIO 引脚的 overlay。在 `config.txt` 中，请注意注释掉或关闭任何启用I2C或SPI的 dtparams ：

[source,ini]
----
dtparam=i2c_arm=off
dtparam=spi=off
----

[[configure-a-display]]
=== 配置显示器

https://en.wikipedia.org/wiki/Direct_Rendering_Manager#Kernel_mode_setting[内核模式设置 (KMS)] 通用显示接口可向任意显示器输出，只要有适当的驱动程序即可。

[[auto-detect]]
==== 自动检测

自动检测允许您的Raspberry Pi与显示器连接，而无需手动配置设备树overlay。
默认情况下启用自动检测。您可以通过在 `config.txt` 中添加以下行来启用显示自动检测：

[source,ini]
----
display_auto_detect=1
----

用 `0` 代替 `1` 以禁用自动检测。
在启用自动检测的情况下连接 Raspberry Pi 官方显示屏时，KMS 会自动确定显示屏型号并配置相应的显示屏设置。

[[manually-configure-a-display]]
==== 手动配置显示器

NOTE: 在 Raspberry Pi OS  _Bookworm_  或更高版本中，以前用于设置 DPI 的 `config.txt` 中的 `dpi_output_format` 和 `dpi_timings` 已被 `vc4-kms-dpi-generic` overlay 取代。

要使用 Raspberry Pi 官方显示屏以外的任何显示屏，必须在 `config.txt` 中指定一个 `dtoverlay` 条目。面板制造商应在 Linux 内核代码中为你的显示器配置时序，并提供一个 overlay 来启用这些设置。有关示例，请参阅 https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/overlays/vc4-kms-kippah-7inch-overlay.dts[Adafruit Kippah 显示器条目]。下面的示例演示了如何在 xref:config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`] 文件中为 Kippah 显示器设置 `dtoverlay` 条目：

[source,ini]
----
dtoverlay=vc4-kms-kippah-7inch-overlay
----

显示时序通常在内核中定义，但也可以在提供的 `panel-dpi` 驱动程序中定义。如果你的面板在内核代码中没有定义覆盖，你可以使用 `panel-dpi` 驱动程序将显示时序定义为参数。这样就可以为任何显示器手动配置设备树。

以下示例演示了如何使用设备树参数定义计时：

[source,ini]
----
dtoverlay=vc4-kms-v3d
dtoverlay=vc4-kms-dpi-generic,hactive=480,hfp=26,hsync=16,hbp=10
dtparam=vactive=640,vfp=25,vsync=10,vbp=16
dtparam=clock-frequency=32000000,rgb666-padhi
----

NOTE: 设备树行长度不得超过80个字符。当设置需要超过80个字符的行时，将该参数的分配拆分为多行。

参数显示树定义支持以下选项：

[cols="1,2"]
|===
| Option | Description

|  `clock-frequency` 
| Display clock frequency (Hz)

|  `hactive` 
| Horizontal active pixels

|  `hfp` 
| Horizontal front porch

|  `hsync` 
| Horizontal sync pulse width

|  `hbp` 
| Horizontal back porch

|  `vactive` 
| Vertical active lines

|  `vfp` 
| Vertical front porch

|  `vsync` 
| Vertical sync pulse width

|  `vbp` 
| Vertical back porch

|  `hsync-invert` 
| Horizontal sync active low

|  `vsync-invert` 
| Vertical sync active low

|  `de-invert` 
| Data Enable active low

|  `pixclk-invert` 
| Negative edge pixel clock

|  `width-mm` 
| Defines the screen width in millimetres

|  `height-mm` 
| Defines the screen height in millimetres

|  `rgb565` 
| Change to RGB565 output on GPIOs 0-19

|  `rgb666-padhi` 
| Change to RGB666 output on GPIOs 0-9, 12-17, and 20-25

|  `rgb888` 
| Change to RGB888 output on GPIOs 0-27

|  `bus-format` 
| Override the bus format for a MEDIA_BUS_FMT_* value, also overridden by rgbXXX overrides

|  `backlight-gpio` 
| Defines a GPIO to be used for backlight control (default value: none)
|===
