[[raspberry-pi-bootloader-configuration]]
== 树莓派 bootloader 配置

[[editing-the-configuration]]
=== 编辑配置

在编辑 bootloader 配置之前，请使用  xref:os.adoc#update-software[update your system] 获取最新版本的 `rpi-eeprom` 软件包。

要查看当前EEPROM配置，请运行以下命令：

[source,console]
----
$ rpi-eeprom-config
----

要编辑当前EEPROM配置并将更新应用于最新的EEPROM版本，请运行以下命令：

[source,console]
----
$ sudo -E rpi-eeprom-config --edit
----

有关EEPROM更新过程的详细信息，请参阅 xref:raspberry-pi.adoc#raspberry-pi-boot-eeprom[boot EEPROM]。

[[configuration-properties]]
=== 配置属性

本节介绍bootloader中可用的所有配置项。语法与 xref:config_txt.adoc[config.txt]相同，但属性特定于bootloader。xref:config_txt.adoc#conditional-filters[条件过滤器] 也受支持，除了EDID。

[[BOOT_UART]]
==== `BOOT_UART` 

如果为 `1` ，则在GPIO 14和15上启用通用异步收发设备调试输出。将接收调试终端配置为115200bps，8位，无奇偶校验位，1个停止位。

默认值： `0` 

[[UART_BAUD]]
==== `UART_BAUD` 

仅限树莓派5。

更改bootloader通用异步收发设备的波特率。

支持的值： `9600`、 `19200`、 `38400`、 `57600`、 `115200`、 `230400`、 `460800`、`921600` 

默认值： `115200` 

[[WAKE_ON_GPIO]]
==== `WAKE_ON_GPIO` 

如果 `1` ，则 `sudo halt` 将在低功耗模式下运行，直到GPIO3或GLOBAL_EN短路接地。

此设置与Raspberry Pi 5之后的旗舰机型、CM5 之后的计算模块以及 Pi 500 之后的键盘机型无关无关，因为 xref:raspberry-pi.adoc#power-button[电源按钮] 总是可以用于从 `HALT` 或 `STANDBY` 唤醒。

默认值： `1` 

[[POWER_OFF_ON_HALT]]
==== `POWER_OFF_ON_HALT` 

如果 `1` 和 `WAKE_ON_GPIO=0` ，则 `sudo停止` 将关闭所有PMIC输出。这是停止的最低功率状态，但可能会导致某些HAT出现问题，因为5V仍将开启。 `GLOBAL_EN` 必须短路到地才能启动。

Raspberry Pi 400有一个电源按钮，即使处理器关闭也能运行。默认情况下启用此行为，但是， `WAKE_ON_GPIO=2` 可以设置为使用外部GPIO电源按钮而不是电源按钮。

在Raspberry Pi 5上，这会将PMIC置于 `待机` 模式，所有输出都将关闭。无需设置 `WAKE_ON_GPIO` ，按下 xref:raspberry-pi.adoc#power-button[电源按钮] 将启动设备。

默认值： `0` 

[[BOOT_ORDER]]
==== `BOOT_ORDER` 

`BOOT_ORDER` 设置允许灵活配置不同引导模式的优先级。它表示为一个 32 位无符号整数，其中每个位代表一种启动模式。启动模式按从最低有效位到最高有效位的顺序尝试。

[[boot_order-fields]]
===== `BOOT_ORDER` fields

`BOOT_ORDER` 属性定义了不同启动模式的顺序。从右向左读取，最多可定义八位数。

[cols="1m,1m,2"]
|===
| Value | Mode | Description

| 0x0
| SD CARD DETECT
| 尝试使用 SD 卡，然后等待卡检测到卡已更改。由于 `0xf` (`RESTART`)已经可用，因此已被弃用。

| 0x1
| SD CARD
| SD card (or eMMC on Compute Module 4).

| 0x2
| NETWORK
| Network boot - See xref:remote-access.adoc#network-boot-your-raspberry-pi[Network boot server tutorial].

| 0x3
| RPIBOOT
| RPIBOOT - See https://github.com/raspberrypi/usbboot[usbboot].

| 0x4
| USB-MSD
| USB mass storage boot - See xref:raspberry-pi.adoc#usb-mass-storage-boot[USB mass storage boot].

| 0x5
| BCM-USB-MSD
| USB 2.0 boot from USB Type C socket (CM4: USB type A socket on CM4IO board). Not available on Raspberry Pi 5.

| 0x6
| NVME
| CM4 and Pi 5 only: boot from an NVMe SSD connected to the PCIe interface. See xref:raspberry-pi.adoc#nvme-ssd-boot[NVMe boot] for more details.

| 0x7
| HTTP
| HTTP boot over ethernet. See xref:raspberry-pi.adoc#http-boot[HTTP boot] for more details.

| 0xe
| STOP
| Stop and display error pattern. A power cycle is required to exit this state.

| 0xf
| RESTART
| 从 `BOOT_ORDER` 字段中的第一个启动模式重新启动，即循环。
|===

`RPIBOOT` 旨在与 Compute Module 4 一起使用，以加载自定义调试映像（例如Linux RAM-disk），而不是正常启动。这应该是最后一个启动选项，因为它当前不支持超时或重试。

[[boot_order-examples]]
===== `BOOT_ORDER` 的例子

[cols="1m,2"]
|===
| BOOT_ORDER | Description

| 0xf41
| 先试 SD，再试 USB-MSD，然后重复（如果 `BOOT_ORDER` 为空，则为默认值）
| 0xf14
| Try USB first, followed by SD then repeat

| 0xf21
| Try SD first, followed by NETWORK then repeat

| 0xf46
| 先试 NVMe，再试 USB-MSD，然后重复
|===

[[MAX_RESTARTS]]
==== `MAX_RESTARTS` 

如果遇到RESTART（ `0xf` ）启动模式超过MAX_RESTARTS次，则会触发看门狗重置。不建议一般使用，但对于需要完全重置以解决硬件或网络接口问题的测试或远程系统可能很有用。

默认值： `-1` （infinite）

[[SD_BOOT_MAX_RETRIES]]
==== `SD_BOOT_MAX_RETRIES` 

SD引导失败后重试的次数，然后移动到由 `BOOT_ORDER` 定义的下一个引导模式。

`-1` 表示无限次重试。

默认值： `0` 

[[NET_BOOT_MAX_RETRIES]]
==== `NET_BOOT_MAX_RETRIES` 

网络引导失败后在移动到由BOOT_ORDER定义的下一个引导模式之前重试的次数。

`-1` 表示无限次重试。

默认值： `0` 

[[DHCP_TIMEOUT]]
==== `DHCP_TIMEOUT` 

当前迭代失败之前整个DHCP序列的超时时间（以毫秒为单位）。

最低： `5000` 

默认值： `45000` 

[[DHCP_REQ_TIMEOUT]]
==== `DHCP_REQ_TIMEOUT` 

重试DHCP DISCOVER或DHCP REQ之前的超时时间（以毫秒为单位）。

最低： `500` 

默认值： `4000` 

[[TFTP_FILE_TIMEOUT]]
==== `TFTP_FILE_TIMEOUT` 

通过TFTP下载单个文件的超时时间（以毫秒为单位）。

最低： `5000` 

默认值： `30000` 

[[TFTP_IP]]
==== `TFTP_IP` 

TFTP服务器的可选带点十进制ip地址（例如192.168.1.99），它覆盖DHCP请求中的server-ip。

这在家庭网络上可能很有用，因为可以使用tftpd-hpa代替dnsmasq，其中宽带路由器是DHCP服务器。

默认值： `""` 

[[TFTP_PREFIX]]
==== `TFTP_PREFIX` 

为了支持每个 Raspberry Pi 独特的 TFTP 启动目录，引导加载程序会在文件名前加上设备特定目录的前缀。如果在前缀目录中既找不到 start4.elf 也找不到 start.elf，那么前缀就会被清除。

在早期型号上，序列号被用作前缀，但在 Raspberry Pi 4 和 5 上，MAC 地址不再由序列号生成，因此很难通过检查 DHCPDISCOVER 数据包在服务器上自动创建 tftpboot 目录。为了支持这一点，TFTP_PREFIX 可以自定义为 MAC 地址、固定值或序列号（默认值）。

|===
| Value | Description

| 0
| Use the serial number e.g.  `9ffefdef/` 

| 1
| 使用 `TFTP_PREFIX_STR` 指定的字符串

| 2
| Use the MAC address e.g.  `dc-a6-32-01-36-c2/` 
|===

默认值：0

[[TFTP_PREFIX_STR]]
==== `TFTP_PREFIX_STR` 

指定当 `TFTP_PREFIX` 设置为 1 时使用的自定义目录前缀字符串。例如：- `TFTP_PREFIX_STR=tftp_test/` 

默认值： `""` 

最大长度：32个字符

[[PXE_OPTION43]]
==== `PXE_OPTION43` 

用不同的字符串覆盖 PXE Option43 匹配字符串。通常情况下，对 DHCP 服务器进行定制比改变客户端行为要好，但在无法做到这一点的情况下，我们提供了这个选项。

默认值： `Raspberry Pi Boot` 

[[DHCP_OPTION97]]
==== `DHCP_OPTION97` 

在早期版本中，客户端 GUID（Option97）只是重复四次的序列号。默认情况下，新的 GUID 格式是四字符代码（FourCC）（Raspberry Pi 4 为 `RPi4` `0x34695052` 或 Raspberry Pi 5 为 `RPi5` `0x35695052` ）、电路板修订版（例如 `0x00c03111` 或 `0x00d04170`）（4 个字节）、mac 地址的最小有效 4 个字节和 4 个字节序列号的连接。
这样做的目的是使其具有唯一性，同时也为 DHCP 服务器提供结构化信息，从而无需依赖以太网 MAC OUID 就能识别 Raspberry Pi 4 和 5 计算机。

指定 `DHCP_OPTION97=0` 可恢复旧的行为，或指定一个非零十六进制值来指定自定义的 4 字节前缀。

默认值： `0x34695052` 

[[MAC_ADDRESS]]
==== `MAC_ADDRESS` 

使用给定值覆盖Raspberry Pi以太网MAC地址。例如 `dc:a6:32:01:36:c2` 

默认值： `""` 

[[MAC_ADDRESS_OTP]]
==== `MAC_ADDRESS_OTP` 

使用存储在 xref:raspberry-pi.adoc#write-and-read-customer-otp-values[客户OTP] 寄存器中的值覆盖Raspberry Pi以太网MAC地址。

例如，使用存储在 `Customer OTP` 的第0行和第1行中的MAC地址。
[source,ini]
----
MAC_ADDRESS_OTP=0,1
----

第一个值（示例中的第 0 行）包含 OUI 和 MAC 地址最重要的 8 位。第二个值（示例中的第 1 行）存储 MAC 地址的剩余 16 位。
这与 Raspberry Pi 制造时编程的 MAC 地址格式相同。

可以按任一顺序选择和组合任何两个客户行。

在 `vcgencmd otp_dump` 输出中， `Customer OTP` 行是 OTP 寄存器 36 至 43，因此如果对前两行进行如下编程，那么 `MAC_ADDRESS_OTP=0,1` 将给出一个 MAC 地址 `e4:5f:01:20:24:7e` 。
 
----
36:247e0000
37:e45f0120
----

默认值： `""` 

[[static-ip-address-configuration]]
==== 静态IP地址配置

如果TFTP_IP并设置了以下选项，则跳过DHCP并应用静态IP配置。如果TFTP服务器与客户端位于同一子网上，则可以省略GATEWay。

[[CLIENT_IP]]
===== `CLIENT_IP` 

客户端的IP地址，例如 `192.168.0.32` 

默认值： `""` 

[[SUBNET]]
===== `SUBNET` 

子网地址掩码，例如 `255.255.255.0` 

默认值： `""` 

[[GATEWAY]]
===== `GATEWAY` 

如果TFTP服务器在不同的子网上，则使用的网关地址，例如 `192.168.0.1` 

默认值： `""` 

[[DISABLE_HDMI]]
==== `DISABLE_HDMI` 

如果 `DISABLE_HDMI=1` ， xref:raspberry-pi.adoc#boot-diagnostics-on-the-raspberry-pi-4[HDMI 启动诊断] 显示将被禁用。其他非零值保留供将来使用。

默认值： `0` 

[[HDMI_DELAY]]
==== `HDMI_DELAY` 

跳过 HDMI 诊断显示，最多 N 秒（默认 5 秒），除非发生致命错误。默认行为旨在避免在正常的 SD/USB 启动过程中短暂出现启动加载程序诊断屏幕。

默认值： `5` 

[[ENABLE_SELF_UPDATE]]
==== `ENABLE_SELF_UPDATE` 

使bootloader能够从TFTP或USB大容量存储设备（MSD）引导文件系统更新自身。

如果启用了自我更新，引导加载程序将在引导文件系统中查找更新文件（.sig/.upd）。如果更新映像与当前映像不同，则应用更新并重置系统。否则，如果 EEPROM 映像字节对字节完全相同，则引导继续正常进行。

注意事项：

* 2021 年之前的引导加载程序版本不支持 `自我更新` 。
* 2022 年之前，SD 启动时未启用自我更新。在 Raspberry Pi 4 上，ROM 已经可以从 SD 卡加载 recovery.bin。在 CM4 上，self-update 和 recovery.bin 都不起作用，需要 USB 启动（参见 xref:compute-module.adoc#compute-module-eeprom-bootloader[计算模块 EEPROM 启动加载程序文档]）。
* 从 2022 年（ https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware-2711/release-notes.md#2022-02-04---network-install---beta[beta] 和 https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware-2711/release-notes.md#2022-03-10---promote-the-2022-03-10-beta-release-to-lateststable[stable]）开始，启用 SD 卡自更新功能。
* 对于网络启动，请确保 TFTP `boot` 目录可以通过 NFS 挂载，并且 `rpi-eeprom-update` 可以写入该目录。

默认值： `1` 

[[FREEZE_VERSION]]
==== `FREEZE_VERSION` 

以前只有 `rpi-eeprom-update` 脚本会检查该属性。但现在启用了自我更新后，引导加载程序也会检查该属性。如果设置为 1，它将覆盖 `ENABLE_SELF_UPDATE` 以停止自动更新。要禁用 `FREEZE_VERSION` ，必须使用 recovery.bin 的 SD 卡启动。

自定义EEPROM更新脚本也必须检查此标志。

默认值： `0` 

[[HTTP_HOST]]
==== `HTTP_HOST` 

如果启动了网络安装或 HTTP引导，则会从此服务器下载 `boot.img` 和 `boot.sig` 。

无效的主机名将被忽略。它们只能包含小写字母数字字符和 `-` 或 `.` 。
如果设置了 `HTTP_HOST` ，则禁用 HTTPS，而使用普通 HTTP。
可以指定一个 IP 地址，以避免 DNS 查找。
主机名中不要包含 HTTP 或任何正斜杠符号。

默认值： `fw-download-alias1.raspberrypi.com` 

[[HTTP_PORT]]
==== `HTTP_PORT` 

您可以使用此属性更改用于网络安装和 HTTP 启动的端口。使用默认主机 `fw-download-alias1.raspberrypi.com` 时，将启用 HTTPS。如果更改了 `HTTP_HOST` ，则会禁用 HTTPS，而使用普通 HTTP。

禁用 HTTPS 后，即使将 `HTTP_PORT` 更改为 `443` ，仍将使用普通 HTTP。

默认值： `443` ，如果启用 HTTPS，则为 `80` 

[[HTTP_PATH]]
==== `HTTP_PATH` 

用于网络安装和 HTTP引导的路径。

区分大小写。
使用Linux斜杠作为路径分隔符。
不需要前导和尾随正斜杠。

如果未设置 `HTTP_HOST` ，则忽略 `HTTP_PATH` ，URL 将是 `https://fw-download-alias1.raspberrypi.com:443/net_install/boot.img` 。如果设置了 `HTTP_HOST` ，URL 将是： `\http://<HTTP_HOST>:<HTTP_PORT>/<HTTP_PATH>/boot.img` 。

默认值： `net_install` 

[[IMAGER_REPO_URL]]
==== `IMAGER_REPO_URL` 

嵌入式 Raspberry Pi Imager 应用程序是通过启动时下载的 JSON 文件配置的。

您可以更改嵌入式 Raspberry Pi Imager 应用程序使用的 JSON 文件的 URL，让它提供您自己的图像。
您可以使用标准 https://www.raspberrypi.com/software/[Raspberry Pi Imager] 应用程序通过 `--repo` 参数传递 URL 进行测试。

默认值： `\http://downloads.raspberrypi.org/os_list_imagingutility_v3.json` 

[[NET_INSTALL_ENABLED]]
==== `NET_INSTALL_ENABLED` 

启用网络安装后，如果bootloader检测到键盘，它会在引导时显示网络安装屏幕。

要启用网络安装，请添加 `NET_INSTALL_ENABLED=1` ，或禁用网络安装，请添加 `NET_INSTALL_ENABLED=0` 。

如果设置了 `DISABLE_HDMI=1` ，则忽略此设置并禁用网络安装。

为了检测键盘，网络安装必须初始化USB控制器并枚举设备。这将启动时间增加大约1秒，因此在某些嵌入式应用程序中禁用网络安装可能是有利的。

默认值：Raspberry Pi 4和Raspberry Pi 400上的 `1` ， Compute Module 4 上的 `0` 。

[[NET_INSTALL_KEYBOARD_WAIT]]
==== `NET_INSTALL_KEYBOARD_WAIT` 

如果启用了网络安装，bootloader会尝试检测键盘和 `SHIFT` 键以启动网络安装。您可以使用此属性以毫秒为单位更改此等待的长度。

将此设置为 `0` 会禁用键盘等待，尽管如果没有找到引导文件并且USB引导模式 `4` 处于 `BOOT_ORDER` 中，仍然可以启动网络安装。

NOTE: 测试表明键盘和SHIFT检测至少需要750毫秒。

默认值： `900` 

[[NETCONSOLE]]
==== `NETCONSOLE` - 高级日志记录

`NETCONSOLE` 将调试消息复制到网络接口。IP地址和端口由 `NETCONSOLE` 字符串定义。

NOTE: NETCONSOLE 会阻塞，直到以太网链接建立或超时。超时值为 `DHCP_TIMEOUT`，但除非请求网络启动，否则不会尝试 DHCP。

[[format]]
===== 格式

更多信息，请参阅 https://wiki.archlinux.org/index.php/Netconsole[Netconsole 文档]。

[source]
----
src_port@src_ip/dev_name,dst_port@dst_ip/dst_mac
E.g. 6665@169.254.1.1/,6666@/
----

为了简化解析，引导加载程序要求每个分隔符都必须存在。您必须指定源 IP 地址，但可以将以下字段留空以使用其默认值：

* `src_port` - `6665`
* `dev_name` - `""` (the device name is always ignored)
* `dst_port` - `6666`
* `dst_ip` - `255.255.255.255`
* `dst_mac` - `00:00:00:00:00`

查看数据的一种方法是将测试的 Raspberry Pi 4 连接到另一个运行 WireShark 的 Raspberry Pi，选择 `udp.srcport == 6665` 作为过滤器，然后选择 *Analyze -> Follow -> UDP stream* 以 ASCII 日志的形式查看。

默认情况下不应启用 `NETCONSOLE` ，因为它可能会导致网络问题。可以通过GPIO过滤器按需启用它：

[source,ini]
----
# Enable debug if GPIO 7 is pulled low
[gpio7=0]
NETCONSOLE=6665@169.254.1.1/,6666@/
----

默认: `""` (未启用）

最大长度：32个字符

[[PARTITION]]
==== `PARTITION` 

如果没有通过 `reboot` 命令（例如 `sudo reboot N` ）或 `autoboot.txt` 中的 `boot_partition=N` 明确设置引导分区号，可以使用 `PARTITION` 选项指定引导分区号。
如果用户按下按钮，这可用于从应急分区启动。
[source,ini]
----
# Boot from partition 2 if GPIO 7 is pulled low
[gpio7=0]
PARTITION=2
----

默认值：0

[[PSU_MAX_CURRENT]]
==== `PSU_MAX_CURRENT` 

仅限树莓派5。

如果设置了该属性，固件就会跳过 USB 供电协商，并假定已连接到具有给定额定电流的电源。
通常情况下，该属性应设置为 `3000` 或 `5000` ，即低电流或高电流电源。

默认值： `""` 

[[USB_MSD_EXCLUDE_VID_PID]]
==== `USB_MSD_EXCLUDE_VID_PID` 

最多四个VID/PID对的列表，指定bootloader应忽略的设备。如果这与HUB匹配，则不会枚举HUB，从而导致排除所有下游设备。
这旨在允许在引导枚举期间忽略有问题的（例如枚举非常慢）设备。这是特定于bootloader的，不会传递给操作系统。

该格式是以逗号分隔的十六进制值列表，其中VID为最重要的半字节。不允许空格。
例如。 `034700a0,a4231234` 

默认值： `""` 

[[USB_MSD_DISCOVER_TIMEOUT]]
==== `USB_MSD_DISCOVER_TIMEOUT` 

如果在此超时时间内未找到USB大容量存储设备，则USB-MSD将停止并选择下一个启动模式。

最低： `5000` （5秒）

默认值： `20000` （20秒）

[[USB_MSD_LUN_TIMEOUT]]
==== `USB_MSD_LUN_TIMEOUT` 

在进入下一个 LUN（如多插槽 SD 卡读卡器）之前等待的时间（以毫秒为单位）。虽然还在调整中，但如果连接的是老式/慢速设备以及包含操作系统的快速 USB-MSD 设备，这可能有助于加快启动速度。

最小值：  `100` 

默认值： `2000` （2秒）

[[USB_MSD_PWR_OFF_TIME]]
==== `USB_MSD_PWR_OFF_TIME` 

仅限树莓派4。

当 Pi 重新启动电源时，硬件会关闭 USB 电源。较短的断电时间可能会导致某些 USB 设备出现问题，因此可以使用此参数强制较长时间的断电，就像电缆被物理移除一样。

在 RaspberryPi 4 1.3 及更旧版本上，可配置/长时间断电要求启用 XHCI 控制器，因此实际上是先短时间断电，然后再长时间配置断电。通过将该参数设置为零，可以跳过较长的可配置断电时间。

在较新的版本中，硬件会确保 USB 电源在重启后关闭，引导加载程序仅在超时后才会启用电源。这是在内存初始化确保 USB 电源关闭至少两秒后发生的。因此，该参数通常对较新的硬件版本没有影响。

最小值： `0` 

最大： `5000` 

默认值： `1000` （1秒）

[[USB_MSD_STARTUP_DELAY]]
==== `USB_MSD_STARTUP_DELAY` 

如果已定义，则会在USB主机控制器初始化后延迟给定超时的USB枚举。如果USB硬盘驱动器需要很长时间才能初始化并触发USB超时，则可以使用此延迟为驱动程序提供额外的初始化时间。还可能需要增加整体USB超时（ `USB_MSD_DISCOVER_TIMEOUT` ）。

最小值： `0` 

最大： `30000` （30秒）

默认值： `0` 

[[VL805]]
==== `VL805` 

仅在 Compute Module 4 上。

如果 `VL805` 属性设置为 `1` ，则bootloader将搜索VL805 PCIe XHCI控制器，并尝试使用嵌入在bootloaderEEPROM中的VL805固件对其进行初始化。这使工业设计能够使用VL805 XHCI控制器，而无需为VL805固件提供专用的SPI 则必须重新刷写bootloader EEPROM

* 在 Compute Module 4 上，引导加载程序从不写入专用的 VL805 SPI EEPROM。该选项只是将控制器配置为从 SDRAM 加载固件。
* 如果 VL805 XHCI 控制器有专用 EEPROM，请勿使用该选项。它将无法初始化，因为 VL805 ROM 会尝试使用专用的 SPI EEPROM（如果已安装）。
* 嵌入式 VL805 固件假定 USB 配置与 Raspberry Pi 4B 相同（两个 USB 3.0 端口和四个 USB 2.0 端口）。不支持加载其他 VL805 固件映像，此类配置应使用专用的 VL805 SPI EEPROM。

默认值： `0` 

[[XHCI_DEBUG]]
==== `XHCI_DEBUG` 

此属性是一个位字段，用于控制大容量存储启动模式下USB调试消息的详细程度。启用所有这些消息会生成大量日志数据，这将减慢启动速度，甚至可能导致启动失败。对于详细日志，最好使用 `NETCONSOLE` 。

[cols="1m,3"]
|===
| Value | Log

| 0x1
| USB descriptors

| 0x2
| Mass storage mode state machine

| 0x4
| Mass storage mode state machine - verbose

| 0x8
| All USB requests

| 0x10
| Device and hub state machines

| 0x20
| All xHCI TRBs (VERY VERBOSE)

| 0x40
| All xHCI events (VERY VERBOSE)
|===

要组合值，请将它们添加在一起。例如：

[source,ini]
----
# Enable mass storage and USB descriptor logging
XHCI_DEBUG=0x3
----

默认值： `0x0` （未启用USB调试消息）

[[config_txt]]
==== `[config.txt]` 部分

读取 `config.txt` 文件后，GPU 固件 `start4.elf` 会读取bootloader EEPROM 配置，并检查是否存在名为 `[config.txt]` 的部分。如果存在 `[config.txt]` 部分，则会在内存中将从该部分开始到文件结束的内容添加到从引导分区读取的 `config.txt` 文件内容中。 这可用于自动将设置应用到每个操作系统，例如 dtoverlays。

WARNING: 如果使用无效配置配置引
导加载程序，导致引导失败，则必须重新刷新引导加载程序 EEPROM，使用有效配置引导。

TIP: 某些配置属性存在于 `config.txt` 中。有关这些属性的更多信息，请参阅 xref:config_txt.adoc#configuration-properties[配置属性]。
