[[frequency-management-and-thermal-control]]
== 频率管理和热控制

所有Raspberry Pi型号都执行一定程度的热管理，以避免在重载下过热。SoC有一个内部温度传感器，GPU上的软件会轮询该传感器以确保温度不超过我们定义的所有型号的85°C限制。可以将其设置为较低的值，但不能设置为较高的值。随着设备接近极限，芯片（Arm、GPU）上使用的各种频率有时甚至电压都会降低。这减少了产生的热量，保持了温度可控。

当内核温度在80°C到85°C之间时，Arm内核将逐步节流。如果温度达到85°C，Arm内核和GPU都将被节流。

对于Raspberry Pi 3 Model B+，PCB技术进行了更改，以提供更好的散热和增加的热质量。此外，还引入了软温度限制，目标是最大限度地延长设备在达到85°C的硬限制之前可以 `冲刺` 的时间。当达到软限制时，时钟速度从1.4GHz降低到1.2GHz，工作电压略有降低。这降低了温度上升的速度：我们将1.4GHz的短周期换成1.2GHz的较长周期。默认情况下，软限制为60°C，这可以通过 xref:config_txt.adoc#overclocking-options[config.txt] 中的 `temp_soft_limit` 设置进行更改。

Raspberry Pi 4 Model B继续采用与Raspberry Pi 3 Model B+相同的PCB技术，以帮助散发多余的热量。目前没有定义软限制。

=== 使用DVFS

NOTE: DVFS的讨论仅适用于4-系列产品（Raspberry Pi 4 Model B、Raspberry Pi 400 和 Compute Module 4，Pi 400）。

Raspberry Pi 4设备实现动态电压和频率缩放（DVFS）。这种技术允许Raspberry Pi 4设备在较低温度下运行，同时仍能提供相同的性能。

SoC 内部的各种时钟（如 Arm、Core、V3D、ISP、H264、HEVC）都受到固件的监控，只要它们不是以全速运行，提供给由时钟驱动的芯片特定部分的电压就会相对于全速降低。实际上，只需提供足够的电压，就能保证模块以特定的速度正常运行。这可以显著降低 SoC 的功耗，从而减少产生的总热量。

由于低电压运行可能涉及系统稳定性问题，尤其是在使用低电压固定时钟外设（如 PCIe）时，因此有三种 DVFS 模式可用，可在 xref:config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`] 中使用以下属性进行配置。大多数系统应使用 `dvfs=3` ，无显示器系统可能会因使用 `dvfs=1` 而略微降低功耗，但有可能出现 PCIe 稳定性问题。

[cols="1m,3"]
|===
| 属性=值 | 描述

| dvfs=1
| 允许欠压

| dvfs=2
| 默认工作频率的固定电压

| dvfs=3
| 如果在 `config.txt` 中指定了 `over_voltage` ，则禁用动态电压缩放，导致系统恢复为 `dvfs=2` 。
|===

NOTE: 此设置已在5-系列设备上删除，并且实际上始终处于模式3。

此外，更步进的中央处理器调速器也用于对ARM核心频率进行更细粒度的控制，这意味着DVFS更有效。这些步骤现在是1500MHz、1000MHz、750MHz和600MHz。当SoC被节流时，这些步骤也会有所帮助，这意味着一路节流回600MHz的可能性要小得多，从而全面提高满载性能。

默认 CPU 调速器为 `ondemand` 。可以使用 `cpufreq-set` 命令（来自 `cpufrequtils` 软件包）手动更改调速器，以减少空闲功耗：

[source,console]
----
$ sudo apt install cpufrequtils
$ sudo cpufreq-set -g powersave
----

=== 测量温度


由于树莓派设备上使用的SoC的架构，以及树莓派操作系统发行版中上游温度监控代码的使用，基于Linux的温度测量可能不准确。然而， `vcgencmd` 命令提供当前SoC温度的准确瞬时读数，因为它直接与GPU通信：

[source,console]
----
$ vcgencmd measure_temp
----

=== 添加散热器

由于内置节流功能，因此不需要散热片来防止 SoC 过热损坏。不过，散热片或小型风扇可以减少热节流并提高性能。垂直安装 Raspberry Pi 可获得最佳气流，从而略微改善散热。

=== 风扇外壳

为确保 Raspberry Pi 的最佳性能，请使用主动冷却解决方案，如风扇。Raspberry Pi 固件可管理所有官方风扇的转速。

==== Raspberry Pi 4 风扇

对于 Raspberry Pi 4，将 https://www.raspberrypi.com/products/raspberry-pi-4-case-fan/[Raspberry Pi 4 外壳风扇] 添加到 Raspberry Pi 4 外壳的盖子上。

==== Raspberry Pi 5 风扇

Raspberry Pi 5可以使用下列选项之一来帮助冷却：

* https://www.raspberrypi.com/products/active-cooler/[主动冷却器]
* https://www.raspberrypi.com/products/raspberry-pi-5-case/[树莓派5的情况下]

Raspberry Pi 5 的两个风扇选项都插入了位于电路板右上方 40 针 GPIO 接头和 USB 2 端口之间的四针 JST-SH PWM 风扇接头。风扇连接器的电流限制与 USB 外围设备相同。我们向超频者推荐 Active Cooler 机箱，因为它能提供更好的散热性能。

当 Raspberry Pi 5 的温度升高时，风扇的反应如下：

* 50°C以下，风扇停止（0%转速）
* 50°C，风扇低速开启（30%转速）
* 在60°C时，风扇转速增加到中速（50%转速）
* 在67.5°C时，风扇转速提升至高速（70%转速）
* 在75°C风扇增加到全速（100%速度）

温度降低使用具有5°C**滞后**的相同映射；当温度下降到低于上述每个阈值的5°C时，风扇速度会降低。

启动时风扇打开，转速表输入检查风扇是否在旋转。如果是，则启用 `cooling_fan` 设备树overlay。默认情况下，此overlay位于 `bcm2712-rpi-5-b.dtb` 中，但带有 `status=disabled` 。

[[raspberry-pi-5-fan-connector-pinout]]
==== Raspberry Pi 5 风扇连接器引脚

Raspberry Pi 5 风扇连接器是一个1mm间距的JST-SH插座，包含以下四个引脚：

[cols="1,2,2",width="50"%"]
|===
| 引脚 | 功能 | 线材颜色
| 1 | +5V | 红色
| 2 | PWM | 蓝色
| 3 | GND | 黑色
| 4 | Tach | 黄色
|===


