[[otp-register-and-bit-definitions]]
== OTP寄存器和位定义

Raspberry Pi 系列使用的所有 SoC 都有一个内置的一次性可编程 (OTP) 存储块。少数位置有出厂编程数据。

OTP内存大小：

* 非BCM2712设备：66个32位值
* BCM2712设备：192个32位值

要显示 OTP 的内容，请运行以下命令：

[source,console]
----
$ vcgencmd otp_dump
----

=== 非BCM2712设备上的OTP寄存器

此列表包含寄存器上的公开可用信息。如果此处未定义寄存器或位，则它不是公开的。

`16`:: OTP 控制寄存器 - BCM2711
+
* 位 26：禁用 VC JTAG
* 第 27 位： 禁用 VC JTAG

`17`:: 启动模式寄存器
+
* 位 1：将振荡器频率设置为 19.2MHz
* 位 3：启用 SDIO 引脚上的上拉功能
* 位 15：禁用 ROM RSA 密钥 0 -（如果设置，则启用安全启动）(BCM2711)
* 位 19：启用 GPIO 启动模式
* 位 20：设置检查 GPIO 启动模式的存储体
* 位 21：启用从 SD 卡启动
* 位 22：设置从 SD 卡启动的存储体
* 位 28：启用 USB 设备启动
* 位 29 ：启用 USB 主机启动（以太网和大容量存储器）

NOTE: 在 BCM2711 上，引导模式由 xref:raspberry-pi.adoc#raspberry-pi-bootloader-configuration[bootloader EEPROM 配置] 定义，而不是 OTP。

`18`:: 引导模式寄存器副本
`28`:: 序列号
`29`:: ~（序列号）
`30`:: xref:raspberry-pi.adoc#raspberry-pi-revision-codes[revision code] ^1^
`33`:: 板修订扩展 - 含义取决于板型号。
可通过 `/proc/device-tree/chosen/rpi-boardrev-ext` 中的 device-tree 获取，出于测试目的，可通过在 `config.txt` 中设置 `board_rev_ext` 来临时覆盖此 OTP 值。
+
* Compute Module 4
 ** 第 30 位：计算模块是否安装了 Wi-Fi 模块
  *** 0 - Wi-Fi
  *** 1 - 无 Wi-Fi
 ** 第 31 位：计算模块是否安装了 EMMC 模块
  *** 0 - EMMC
  *** 1 - 无 EMMC（精简版）
* 树莓派 400
 ** 位 0-7： https://github.com/raspberrypi-ui/piwiz[piwiz] 使用的默认键盘国家代码。

`36-43`:: xref:raspberry-pi.adoc#industrial-use-of-the-raspberry-pi[customer OTP values]
`45`:: MPG2解码密钥
`46`:: WVC1 解码密钥
`47-54`:: 用于安全启动的 RSA 公钥的 SHA256
`55`:: 安全启动标志（保留给启动加载程序使用）
`56-63`:: 256 位设备专用私钥
`64-65`:: MAC 地址；如果设置，系统将优先使用该地址，而不是根据序列号自动生成的地址
`66`:: 高级启动寄存器（非 BCM2711）
+
* 第 0-6 位：ETH_CLK 输出引脚的 GPIO
* 第 7 位：启用 ETH_CLK 输出
* 第 8-14 位：LAN_RUN 输出引脚的 GPIO
* 位 15：启用 LAN_RUN 输出
* 位 24：扩展 USB HUB 超时参数
* 第 25 位：ETH_CLK 频率：
 ** 0 - 25MHz
 ** 1 - 24MHz

^1^还包含用于禁用过压、OTP编程和OTP读取的位。

=== BCM2712设备上的OTP寄存器

此列表包含寄存器上的公开可用信息。如果此处未定义寄存器或位，则它不是公开的。

`22`:: 引导模式寄存器
+
* 位 1：从 SD 卡启动
* 位 2-4 ：从 SPI EEPROM 启动（以及哪些 GPIO）
* 位 10：禁止从 SD 卡启动
* 位 11：禁止从 SPI 启动
* 位 12：禁止从 USB 启动

`23`:: 复制引导模式寄存器
`29`:: 高级启动模式
+
* 位 0-7 ：用于 SD 卡检测的 GPIO
* 位 8-15: 用于 RPIBOOT 的 GPIO

`31`:: 序列号的低 32 位
`32`:: xref:raspberry-pi.adoc#raspberry-pi-revision-codes[电路板版本]
`33`:: 板属性 - 含义取决于板型号。
可通过 `/proc/device-tree/chosen/rpi-boardrev-ext` 中的 device-tree 获取。

`35`:: 序列号的上 32 位
完整的 64 位序列号在 `/proc/device-tree/serial-number` 中提供

`50-51`:: 以太网 MAC 地址
在设备树中传递给操作系统，例如 `/proc/device-tree/axi/pcie@120000/rp1/ether@100000/local-mac-address` 。

`52-53`:: Wi-Fi MAC 地址
在设备树中传递给操作系统，例如 `/proc/device-tree/axi/mmc@1100000/wifi@1/local-mac-address` 。

`54-55`:: 蓝牙 MAC 地址
这将在设备树中传递给操作系统，例如 `/proc/device-tree/soc/serial@7d50c000/bluetooth/local-bd-address`。

`77-84`:: xref:raspberry-pi.adoc#industrial-use-of-the-raspberry-pi[customer OTP values]
`86`:: board country - https://github.com/raspberrypi-ui/piwiz[piwiz] 使用的默认键盘国家代码。
如果已设置，则可通过 `/proc/device-tree/chosen/rpi-country-code` 中的设备树查看。

`87-88`:: xref:raspberry-pi.adoc#industrial-use-of-the-raspberry-pi[customer Ethernet MAC address]
如果已设置，则覆盖 OTP 第 50-51 行

`89-90`:: xref:raspberry-pi.adoc#industrial-use-of-the-raspberry-pi[customer Wi-Fi MAC address]
如果设置，则覆盖 OTP 第 52-53 行

`89-90`:: xref:raspberry-pi.adoc#industrial-use-of-the-raspberry-pi[customer Bluetooth MAC address]
如果设置，则覆盖 OTP 第 54-55 行

`109-114`:: 出厂设备 UUID
目前是一个 16 位数字 ID，应与设备上的条形码相匹配。用 0 字符填充并用 c40 编码。

可通过 `/proc/device-tree/chosen/rpi-duid` 中的 device-tree 获取。



