[[spi-overview]]
== 串行外设接口（SPI）

树莓派计算机配备了许多 https://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus[SPI] 总线。SPI可用于连接各种外围设备——显示器、网络控制器（以太网、CAN总线）、UART等。这些设备最好由内核设备驱动程序支持，但 `spidev` 应用编程接口允许用多种语言编写用户空间驱动程序。

[[spi-hardware]]
=== SPI硬件

Raspberry Pi Zero、1、2和3有三个SPI控制器：

* `SPI0`，具有两个硬件芯片选择，可用于所有 Raspberry Pi 的排针；还有一个替代映射，仅在 Compute Module 上可用。
* `SPI1` 具有三种硬件芯片选择，适用于除原始Raspberry Pi 1 Model A和Model B之外的所有Raspberry Pi型号。
* `SPI2` 也有三种硬件芯片选择，仅在 Compute Module 1、3和3+上可用。

在树莓派4、400和 Compute Module 4 上，有四个额外的SPI总线：SPI3到SPI6，每个都有两个硬件芯片选择。这些额外的SPI总线可通过某些GPIO引脚上的备用功能分配获得。有关详细信息，请参阅 https://datasheets.raspberrypi.com/bcm2711/bcm2711-peripherals.pdf[BCM2711 Arm外围设备] datasheet。

 https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf[BCM2835 Arm外设] datasheet中的第10章描述了主控制器。第2.3章描述了辅助控制器。

==== 引脚/GPIO映射

===== SPI0

[cols="1m,1,1m,1m"]
|===
a| SPI function | Header pin a| Broadcom pin name a| Broadcom pin function

| MOSI
| 19
| GPIO10
| SPI0_MOSI

| MISO
| 21
| GPIO09
| SPI0_MISO

| SCLK
| 23
| GPIO11
| SPI0_SCLK

| CE0
| 24
| GPIO08
| SPI0_CE0_N

| CE1
| 26
| GPIO07
| SPI0_CE1_N
|===

===== SPI0备用映射（仅 Compute Module ，CM4除外）

[cols="1m,1m,1m"]
|===
a| SPI function a| Broadcom pin name a| Broadcom pin function

| MOSI
| GPIO38
| SPI0_MOSI

| MISO
| GPIO37
| SPI0_MISO

| SCLK
| GPIO39
| SPI0_SCLK

| CE0
| GPIO36
| SPI0_CE0_N

| CE1
| GPIO35
| SPI0_CE1_N
|===

===== SPI1

[cols="1m,1,1m,1m"]
|===
a| SPI function | Header pin | Broadcom pin name | Broadcom pin function

| MOSI
| 38
| GPIO20
| SPI1_MOSI

| MISO
| 35
| GPIO19
| SPI1_MISO

| SCLK
| 40
| GPIO21
| SPI1_SCLK

| CE0
| 12
| GPIO18
| SPI1_CE0_N

| CE1
| 11
| GPIO17
| SPI1_CE1_N

| CE2
| 36
| GPIO16
| SPI1_CE2_N
|===

===== SPI2（仅 Compute Module ，CM4除外）

[cols="1m,1m,1m"]
|===
a| SPI function a| Broadcom pin name a| Broadcom pin function

| MOSI
| GPIO41
| SPI2_MOSI

| MISO
| GPIO40
| SPI2_MISO

| SCLK
| GPIO42
| SPI2_SCLK

| CE0
| GPIO43
| SPI2_CE0_N

| CE1
| GPIO44
| SPI2_CE1_N

| CE2
| GPIO45
| SPI2_CE2_N
|===

===== SPI3（仅限BCM2711）

[cols="1m,1,1m,1m"]
|===
a| SPI function | Header pin a| Broadcom pin name a| Broadcom pin function

| MOSI
| 03
| GPIO02
| SPI3_MOSI

| MISO
| 28
| GPIO01
| SPI3_MISO

| SCLK
| 05
| GPIO03
| SPI3_SCLK

| CE0
| 27
| GPIO00
| SPI3_CE0_N

| CE1
| 18
| GPIO24
| SPI3_CE1_N
|===

===== SPI4（仅限BCM2711）

[cols="1m,1,1m,1m"]
|===
a| SPI function | Header pin a| Broadcom pin name a| Broadcom pin function

| MOSI
| 31
| GPIO06
| SPI4_MOSI

| MISO
| 29
| GPIO05
| SPI4_MISO

| SCLK
| 26
| GPIO07
| SPI4_SCLK

| CE0 
| 07
| GPIO04
| SPI4_CE0_N

| CE1
| 22
| GPIO25
| SPI4_CE1_N
|===

===== SPI5（仅限BCM2711）

[cols="1m,1,1m,1m"]
|===
a| SPI function | Header pin a| Broadcom pin name a| Broadcom pin function

| MOSI
| 08
| GPIO14
| SPI5_MOSI

| MISO
| 33
| GPIO13
| SPI5_MISO

| SCLK
| 10
| GPIO15
| SPI5_SCLK

| CE0
| 32
| GPIO12
| SPI5_CE0_N

| CE1
| 37
| GPIO26
| SPI5_CE1_N
|===

===== SPI6（仅限BCM2711）

[cols="1,1,1,1"]
|===
| SPI function | Header pin | Broadcom pin name | Broadcom pin function

| MOSI
| 38
| GPIO20
| SPI6_MOSI

| MISO
| 35
| GPIO19
| SPI6_MISO

| SCLK
| 40
| GPIO21
| SPI6_SCLK

| CE0
| 12
| GPIO18
| SPI6_CE0_N

| CE1
| 13
| GPIO27
| SPI6_CE1_N
|===

==== 主模式

信号名称缩写

Signal name abbreviations:

SCLK:: serial clock
CE:: chip enable (often called chip select)
MOSI:: master out slave in
MISO:: master in slave out
MOMI:: master out master in

===== 标准模式

在标准SPI模式下，外设实现标准的三线串行协议（SCLK、MOSI和MISO）。

===== 双向模式

在双向 SPI 模式中，执行的是相同的 SPI 标准，但数据线（MOMI）只用一根，而不是标准模式中的两根（MISO 和 MOSI）。在这种模式下，MOSI 引脚用作 MOMI 引脚。

===== 低速串行接口（LoSSI）模式

LoSSI 标准允许向外围设备（LCD）发出命令，并将数据传输到外围设备。LoSSI 命令和参数的长度为 8 位，但有一个额外位用于指示字节是命令还是参数/数据。数据时，该额外位设置为高电平；命令时，该额外位设置为低电平。由此产生的 9 位值被序列化到输出端。LoSSI 通常与 http://mipi.org/specifications/display-interface[MIPI DBI] 类型 C 兼容的 LCD 控制器一起使用。
 
NOTE: 某些命令会触发 SPI 控制器的自动读取，因此此模式不能用作多用途 9 位 SPI。

==== 传输模式

* Polled
* Interrupt
* DMA

==== 速度

CLK 寄存器的时钟分频器 (CDIV) 字段设置 SPI 时钟速度：

SCLK:: Core Clock / CDIV

如果 CDIV 设置为 0，则除数为 65536。除数必须是 2 的倍数，奇数向下舍入。请注意，由于模拟电气问题（上升时间、驱动强度等），并非所有可能的时钟速率都可用。

有关更多信息，请参阅 <<driver,Linux driver>> 部分。

==== 芯片选择

在 DMA 模式下运行时，与 CS 线的自动置位和置位取消相关的设置和保持时间如下：

* CS 线将在传输的第一个字节的 msb 之前至少三个核心时钟周期置位。
* CS 线将在最后一个时钟脉冲的后沿之后不早于一个核心时钟周期置位。

=== SPI 软件

[[driver]]
==== Linux driver

默认的 Linux 驱动程序是 `spi-bcm2835` 。

SPI0 默认禁用。要启用它，请使用 xref:configuration.adoc#raspi-config[raspi-config]，或确保 xref:config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`] 中的 `dtparam=spi=on` 行未注释。默认情况下，它使用两条芯片选择线，但可以使用 `dtoverlay=spi0-1cs` 将其减少为一条。此外还有 `dtoverlay=spi0-2cs` ；不带任何参数的情况下，它等同于 `dtparam=spi=on` 。

要启用 SPI1，可以使用 1、2 或 3 条芯片选择线。在 `/boot/firmware/config.txt` 中添加相应行：

[source,ini]
----
#1 chip select
dtoverlay=spi1-1cs
#2 chip select
dtoverlay=spi1-2cs
#3 chip select
dtoverlay=spi1-3cs
----

SPI2、SPI3、SPI4、SPI5 和 SPI6 也有类似的overlays。

由于某些限制，该驱动程序不使用硬件芯片选择线。相反，它可以使用任意数量的 GPIO 作为软件/GPIO 片选。这意味着你可以自由选择任何空闲的 GPIO 作为 CS 线路，而且所有这些 SPI 覆盖都包含该控制 - 详情请参见 `/boot/firmware/overlays/README` ，或运行（例如） `dtoverlay -h spi0-2cs` （ `dtoverlay -a | grep spi` 可能有助于列出所有这些线路）。

===== 速度

驱动程序支持内核时钟整除的所有速度，但如上所述，由于 GPIO 和所连接设备的限制，并非所有这些速度都能支持数据传输。根据经验，任何超过 50MHz 的速度都不可能工作，但具体情况可能会有所不同。

===== 支持的模式位

SPI_CPOL:: clock polarity
SPI_CPHA:: clock phase
SPI_CS_HIGH:: chip select active high
SPI_NO_CS:: 1 device per bus, no Chip select
SPI_3WIRE:: bidirectional mode, data in and out pin shared

双向模式也称为 3 线模式，由 `spi-bcm2835` 内核模块支持。请注意，在这种模式下，`spi_transfer` 结构的 `tx` 或 `rx` 字段必须是空指针，因为只能进行半双工通信。否则，传输将失败。`spidev_test.c` 源代码没有正确考虑这一点，因此在三线模式下根本无法工作。

===== 每个字支持的位数

* 8 - 正常
* 9 - 支持使用 LoSSI 模式

===== 传输模式

所有 SPI 总线都支持中断模式。 SPI0 和 SPI3-6 也支持 DMA 传输。

===== SPI 驱动程序延迟

此 https://forums.raspberrypi.com/viewtopic.php?f=44&t=19489[thread] 讨论了延迟问题。

==== spidev

`spidev` 为单个 SPI CS 线路提供了一个基于 `ioctl` 的用户空间接口。设备树用于指示 CS 线路是由内核驱动模块驱动，还是由 `spidev` 代表用户管理；两者不可能同时进行。请注意，Raspberry Pi 自己的内核对于使用设备树来启用 `spidev` 比较宽松 - 上游内核会对此类使用发出警告，最终可能会完全禁止使用。


===== 从 C 使用 `spidev`

Linux 文档中有一个环回测试程序可以用作起点。请参阅 <<troubleshooting-spi-hardware,Troubleshooting>> 部分。

===== 从 Python 使用 `spidev`

有多个 Python 库提供对 `spidev` 的访问，包括 `spidev` （ `pip install spidev` - 请参阅 https://pypi.org/project/spidev/）和 `SPI-Py` （https://github.com/lthiery/SPI-Py）。

===== 在 bash 等 shell 中使用 `spidev`

以下命令将写入二进制 1、2 和 3：

[source,console]
----
$ echo -ne "\x01\x02\x03" > /dev/spidev0.0
----

==== 其他SPI库

还有其他用户空间库通过直接操作硬件来提供 SPI 控制：不建议使用这种方法。

[[troubleshooting-spi-hardware]]
=== 故障排除

==== 环回测试

这可以用来测试SPI发送和接收。在MOSI和MISO之间放一根电线。它不测试CE0和CE1。

[source,console]
----
$ wget https://raw.githubusercontent.com/raspberrypi/linux/rpi-6.1.y/tools/spi/spidev_test.c
$ gcc -o spidev_test spidev_test.c
$ ./spidev_test -D /dev/spidev0.0
spi mode: 0
bits per word: 8
max speed: 500000 Hz (500 KHz)

FF FF FF FF FF FF
40 00 00 00 00 95
FF FF FF FF FF FF
FF FF FF FF FF FF
FF FF FF FF FF FF
DE AD BE EF BA AD
F0 0D
----

以上部分内容抄自 https://elinux.org/RPi_SPI[elinux SPI 页面]，该页面也借鉴了此处内容。两者均采用 CC-SA 许可。
