== 通用串行总线（USB）

一般来说，Linux 支持的所有设备都可以与 Raspberry Pi 一起使用，但 Raspberry Pi 4 之前的型号有一些限制。

=== 最大功率输出

与所有电脑一样，Raspberry Pi 上的 USB 端口提供的功率是有限的。USB 设备的问题通常是由电源问题引起的。要排除电源不足的原因，请使用供电集线器将 USB 设备连接到 Raspberry Pi。

|===
| Model | Max power output of USB ports

| Raspberry Pi Zero, 1
| 500mA per port^1^

| Raspberry Pi 2, 3, 4
| 1200mA total across all ports

| Raspberry Pi 5
| 600mA if using a 3A supply, 1600mA if using a 5A supply
|===

. 对于原始 Raspberry Pi 1 Model B，每个端口的限制电流为 100mA。

=== Raspberry Pi 5

Raspberry Pi 5 需要能够在 +5V 电压下提供 3A 电流（15W）的优质 USB-C 电源才能启动。不过，使用这样的电源会限制外设的电流消耗。如果您使用的电源无法在首次启动时以 +5V 电压提供 5A 电流，则操作系统会警告您外围设备的电流将限制在 600mA。

对于希望驱动大功率外设（如硬盘和固态硬盘），同时为峰值工作负载保留余量的用户，应使用能够在 +5V 电压下提供 5A 电流（25W）的支持 USB-PD 的电源。如果 Raspberry Pi 5 固件检测到这样的电源，就会将外围设备的 USB 电流限制增加到 1.6A，为下游 USB 设备提供 5W 的额外电源，并提供 5W 的额外板载电源余量。

NOTE: 电源余量由 USB 端口和风扇共享。

=== Raspberry Pi 4

Raspberry Pi 4 提供两个 USB 3.0 端口和两个 USB 2.0 端口，它们与 VL805 USB 控制器相连。所有四个端口的 USB 2.0 线路都连接到 VL805 中的一个 USB 2.0 集线器。这就将 USB 1.1 和 USB 2.0 设备的总可用带宽限制为单个 USB 2.0 端口的带宽。

在 Raspberry Pi 4 上，以前型号使用的 USB 控制器位于 USB Type C 端口上，默认情况下被禁用。

=== Raspberry Pi Zero, 1, 2 and 3

Raspberry Pi 1 Model B+、Raspberry Pi 2 和 Raspberry Pi 3 板提供四个 USB 2.0 端口。Raspberry Pi Zero 板有一个微型 USB on-the-go (OTG) 端口。

Raspberry Pi 4 之前型号的 USB 控制器对某些设备只有基本的支持，因此软件处理开销较大。它还只支持一个根 USB 端口：来自连接设备的所有流量都通过这条单一总线传输，其最高运行速度为 480Mbps。

USB 2.0 规范定义了三种设备速度--低速、全速和高速。大多数鼠标和键盘为低速，大多数 USB 音效设备为全速，大多数视频设备（网络摄像头或视频采集）为高速。

一般来说，将多个高速 USB 设备连接到 Raspberry Pi 不会有任何问题。

与低速和全速设备通信时产生的软件开销意味着同时激活低速和全速设备的数量受到限制。少量这些类型的设备连接到 Raspberry Pi 不会造成任何问题。


=== 已知的 USB 问题

==== 与 USB 3.0 集线器的互操作性

在使用全速或低速设备（包括大多数鼠标和键盘）时，USB 3.0 集线器存在一个问题。大多数 USB 3.0 集线器硬件中的一个错误意味着 Raspberry Pi 4 之前的型号无法与连接到 USB 3.0 集线器的全速或低速设备对话。

通过 USB 3.0 集线器连接 USB 2.0 高速设备（包括 USB 2.0 集线器）时可正常运行。

避免将低速或全速设备连接到 USB 3.0 集线器。作为一种变通方法，将 USB 2.0 集线器插入 USB 3.0 集线器的下游端口并连接低速设备，或在 Raspberry Pi 和 USB 3.0 集线器之间使用 USB 2.0 集线器，然后将低速设备插入 USB 2.0 集线器。

==== USB 1.1 网络摄像头

老式网络摄像头可能是全速设备。由于这些设备会传输大量数据并产生额外的软件开销，因此无法保证可靠运行。作为一种变通方法，可尝试使用较低分辨率的摄像头。

==== USB 声卡

昂贵的发烧级声卡通常使用大量 USB 带宽。无法保证 96kHz/192kHz DAC 的可靠运行。作为一种变通方法，强制输出流为 CD 质量（44.1kHz/48kHz 16 位）可将流带宽降至可靠水平。

==== 单 TT USB 集线器

USB 2.0 和 3.0 集线器有一种与连接到其下游端口的全速或低速设备对话的机制，称为事务转换器 (TT)。该设备可缓冲来自主机的高速请求，并以全速或低速将其传输到下游设备。USB 规范允许两种集线器配置： 单 TT（所有端口一个 TT）和多 TT（每个端口一个 TT）。由于硬件限制，如果在单 TT 集线器上插入过多的全速或低速设备，设备可能会表现不可靠。建议使用多 TT 集线器连接多个全速和低速设备。作为一种变通方法，将全速和低速设备分散到 Raspberry Pi 自身的 USB 端口和单 TT 集线器之间。


