[[building]]
== 构建内核

操作系统预装的默认编译器和链接器被配置为构建在该操作系统上运行的可执行文件。 **原生编译** 使用这些默认编译器和链接器。**交叉编译** 是为运行编译过程的目标之外的目标编译代码的过程。

Raspberry Pi 内核的交叉编译允许你从 32 位操作系统构建 64 位内核，反之亦然。或者，你也可以从 Raspberry Pi 以外的设备交叉编译 32 位或 64 位 Raspberry Pi 内核。

下面的说明分为本地编译和交叉编译。选择适合你的情况的部分；虽然这两个过程有许多相同的步骤，但也有一些重要的区别。

[[download-kernel-source]]
=== 下载内核源代码

在为任何目标构建之前，你都需要内核源代码。要获取内核源代码，你需要 Git。如果尚未安装 Git，请先在设备上安装：

[source,console]
----
$ sudo apt install git
----

接下来，下载最新 Raspberry Pi 内核的源代码：

[source,console]
----
$ git clone --depth=1 https://github.com/raspberrypi/linux
----

这可能需要几分钟时间。

[TIP]
====
上面的 `git clone` 命令下载的是当前活动分支，我们从该分支构建 Raspberry Pi 操作系统映像，不包含任何历史记录。省略 `--depth=1`可以下载整个版本库，包括所有分支的完整历史。这需要更长的时间，占用的存储空间也更大。

要下载不带历史记录的其他分支，请在上述命令中添加 `--branch` 选项，并将 `<branch>` 替换为要下载的分支名称：

[source,console]
----
$ git clone --depth=1 --branch <branch> https://github.com/raspberrypi/linux
----

有关可用分支的完整列表，请查看 https://github.com/raspberrypi/linux[树莓派内核库]。
====

现在你有了内核源代码，请通过 xref:linux_kernel.adoc#natively-build-a-kernel[本机] 或 xref:linux_kernel.adoc#cross-compile-the-kernel[交叉编译] 构建一个新内核。

[[natively-build-a-kernel]]
=== 本地构建内核

本指南假设你的 Raspberry Pi 运行的是最新版本的 xref:os.adoc[Raspberry Pi OS]。

首先，安装构建依赖项：

[source,console]
----
$ sudo apt install bc bison flex libssl-dev make
----

[[native-build-configuration]]
==== 构建配置

本节介绍如何在构建内核时应用默认配置。您还可以通过以下方式配置内核：

* xref:linux_kernel.adoc#configure-the-kernel[启用和禁用内核功能]
* xref:linux_kernel.adoc#patch-the-kernel[从另一个源头添加补丁]

要准备默认配置，请根据您的 Raspberry Pi 型号运行下表中的相应命令。

[cols="8,<.^20a,60a"]
|===
| 架构 | 型号 | 命令

.12+^.^| 64-bit
| Raspberry Pi 3
.9+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel8
$ make bcm2711_defconfig
----
| Compute Module 3
| Raspberry Pi 3+
| Compute Module 3+
| Raspberry Pi Zero 2 W
| Raspberry Pi 4
| Pi 400
| Compute Module 4
| Compute Module 4S


.^| Raspberry Pi 5
.3+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel_2712
$ make bcm2712_defconfig
----
| Pi 500
| Compute Module 5

.14+^.^| 32-bit
| Raspberry Pi 1
.4+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel
$ make bcmrpi_defconfig
----
| Compute Module 1
| Zero
| Zero W


| Raspberry Pi 2
.6+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel7
$ make bcm2709_defconfig
----
| Raspberry Pi 3
| Compute Module 3
| Raspberry Pi 3+
| Compute Module 3+
| Zero 2 W


| Raspberry Pi 4
.4+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel7l
$ make bcm2711_defconfig
----
| Pi 400
| Compute Module 4
| Compute Module 4S
|===

[NOTE]
====
4 系列设备上的 32 位 Raspberry Pi OS 发行版使用 32 位用户态域，但使用 _64_ 位内核。要构建 32 位内核，请设置 `ARCH=arm`。要启动 32 位内核，请在 `config.txt` 中设置 `arm_64bit=0`。
====

[[native-customisation]]
==== 使用 `LOCALVERSION` 自定义内核版本

为防止内核覆盖 `/lib/modules` 中的现有模块，并在 `uname` 输出中说明运行的是自己的内核，请修改 `LOCALVERSION`。

要修改 `LOCALVERSION`，请修改 `.config` 中此行：
[source,ini]
----
CONFIG_LOCALVERSION="-v7l-MY_CUSTOM_KERNEL"
----

TIP: 你也可以在 *General setup* > *Local version - append to kernel release* 中使用 `menuconfig` 以图形方式更改此设置。有关 `menuconfig` 的更多信息，请参阅 xref:linux_kernel.adoc#configure-the-kernel[内核配置说明]。

[[native-build]]
==== 构建

接下来，构建内核。这一步可能需要很长时间，取决于你的 Raspberry Pi 型号。

* 运行以下命令构建 64 位内核：
+
[source,console]
----
$ make -j6 Image.gz modules dtbs
----

* 运行以下命令构建 32 位内核：
+
[source,console]
----
$ make -j6 zImage modules dtbs
----

提示：在多核 Raspberry Pi 型号上， `make -j<n>` 选项可在不同内核之间分配工作。这会大大加快编译速度。运行 `nproc` 查看你有多少个处理器；我们建议使用处理器乘以 1.5。

[[native-install]]
==== 安装内核

接下来，将内核模块安装到启动介质上：

[source,console]
----
$ sudo make -j6 modules_install
----

然后，将内核和设备树 blobs 安装到启动分区，备份原始内核。

TIP: 如果不想在运行此命令的 Raspberry Pi 上安装刚编译好的内核，可将编译好的内核复制到另一个启动介质的启动分区，而不是 `/boot/firmware/`。

安装 64 位内核：

* 运行以下命令创建当前内核的备份镜像，安装新的内核镜像、overlays、README，并卸载分区：
+
[source,console]
----
$ sudo cp /boot/firmware/$KERNEL.img /boot/firmware/$KERNEL-backup.img
$ sudo cp arch/arm64/boot/Image.gz /boot/firmware/$KERNEL.img
$ sudo cp arch/arm64/boot/dts/broadcom/*.dtb /boot/firmware/
$ sudo cp arch/arm64/boot/dts/overlays/*.dtb* /boot/firmware/overlays/
$ sudo cp arch/arm64/boot/dts/overlays/README /boot/firmware/overlays/
----

安装 32 位内核：

. 创建当前内核的备份，然后安装新的内核映像：
+
[source,console]
----
$ sudo cp /boot/firmware/$KERNEL.img /boot/firmware/$KERNEL-backup.img
$ sudo cp arch/arm/boot/zImage /boot/firmware/$KERNEL.img
----
. 根据你的 xref:linux_kernel.adoc#identify-your-kernel-version[内核版本]，运行以下命令：
  ** 适用于 6.4 及以下版本的内核：
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/*.dtb /boot/firmware/
----
** 适用于 6.5 及以上版本的内核：
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/broadcom/*.dtb /boot/firmware/
----
. 最后，复制 overlays 和 README：
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/firmware/overlays/
$ sudo cp arch/arm/boot/dts/overlays/README /boot/firmware/overlays/
----

最后，运行以下命令重启 Raspberry Pi 并运行新编译的内核：

[source,console]
----
$ sudo reboot
----

[TIP]
====
或者，用不同的文件名复制内核（如 `kernel-myconfig.img`），而不是覆盖 `kernel.img` 文件。然后，编辑启动分区中的 `config.txt` 以选择内核：

[source,ini]
----
kernel=kernel-myconfig.img
----

将此方法与自定义的`LOCALVERSION` 相结合，可将自定义内核与系统管理的原版内核映像分开。有了这种安排，当你的内核无法启动时，你就可以迅速恢复到原版内核。
====

[[cross-compile-the-kernel]]
=== 交叉编译内核

首先，你需要一台合适的 Linux 交叉编译主机。我们倾向于使用 Ubuntu；因为 Raspberry Pi OS 也是 Debian 发行版，所以编译命令也类似。

[[cross-compiled-dependencies]]
==== 安装所需的依赖项和工具链

要构建用于交叉编译的源代码，请在设备上安装所需的依赖项。运行以下命令安装大部分依赖项：

[source,console]
----
$ sudo apt install bc bison flex libssl-dev make libc6-dev libncurses5-dev
----

然后，针对要构建的内核架构安装适当的工具链：

* 要安装 64 位工具链以构建 64 位内核，请运行以下命令：
+
[source,console]
----
$ sudo apt install crossbuild-essential-arm64
----

* 要安装 32 位工具链以构建 32 位内核，请运行以下命令：
+
[source,console]
----
$ sudo apt install crossbuild-essential-armhf
----

[[cross-compiled-build-configuration]]
==== 构建配置

本节介绍如何在构建内核时应用默认配置。您还可以通过以下方式配置内核：

* xref:linux_kernel.adoc#configure-the-kernel[启用和禁用内核功能]
* xref:linux_kernel.adoc#patch-the-kernel[从另一个源头安装补丁]

输入以下命令以创建源文件和设备树文件：

[cols="8,<.^20a,60a"]
|===
| 目标架构 | 目标产品 | 命令

.10+^.^| 64-bit
| Raspberry Pi 3
.9+.^| [source,console]
----
$ cd linux
$ KERNEL=kernel8
$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcm2711_defconfig
----
| Raspberry Pi Compute Module 3
| Raspberry Pi 3+
| Raspberry Pi Compute Module 3+
| Raspberry Pi Zero 2 W
| Raspberry Pi 4
| Raspberry Pi 400
| Raspberry Pi Compute Module 4
| Raspberry Pi Compute Module 4S

.^| Raspberry Pi 5
.1+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel_2712
$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcm2712_defconfig
----


.14+^.^| 32-bit

| Raspberry Pi 1
.4+.^| [source,console]
----
$ cd linux
$ KERNEL=kernel
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcmrpi_defconfig
----
| Raspberry Pi Compute Module 1
| Raspberry Pi Zero
| Raspberry Pi Zero W

| Raspberry Pi 2
.6+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel7
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2709_defconfig
----
| Raspberry Pi 3
| Raspberry Pi Compute Module 3
| Raspberry Pi 3+
| Raspberry Pi Compute Module 3+
| Raspberry Pi Zero 2 W

| Raspberry Pi 4
.4+.^|
[source,console]
----
$ cd linux
$ KERNEL=kernel7l
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2711_defconfig
----
| Raspberry Pi 400
| Raspberry Pi Compute Module 4
| Raspberry Pi Compute Module 4S
|===

[[cross-compiled-customisation]]
==== 使用 `LOCALVERSION` 自定义内核版本

为防止内核覆盖 `/lib/modules` 中的现有模块，并在 `uname` 输出中表明运行的是自己的内核，请调整 `LOCALVERSION` 内容。

要修改 `LOCALVERSION`，请修改 `.config` 中的此行：

[source,ini]
----
CONFIG_LOCALVERSION="-v7l-MY_CUSTOM_KERNEL"
----

TIP: 你也可以在 *General setup* > *Local version - append to kernel release* 中使用 `menuconfig` 以图形方式更改这一设置。有关 `menuconfig` 的更多信息，请参阅 xref:linux_kernel.adoc#configure-the-kernel[内核配置说明]。

[[cross-compiled-build]]
==== Build

* 运行以下命令构建 64 位内核：
+
[source,console]
----
$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image modules dtbs
----

* 运行以下命令构建 32 位内核：
+
[source,console]
----
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs
----

[[cross-compiled-install]]
==== 安装内核

创建内核后，您需要将其复制到 Raspberry Pi 启动介质（可能是 SD 卡或 SSD）上，然后安装模块。

===== 查找启动介质

首先，运行 `lsblk`。然后，连接启动媒体。再次运行 `lsblk`；新设备代表启动介质。你应该会看到类似下面的输出：

----
sdb
   sdb1
   sdb2
----

如果 `sdb` 代表启动介质，则 `sdb1` 代表 `FAT32` 格式的 **启动分区**，而 `sdb2` 代表（可能是 `ext4` 格式的）**根分区**。

首先，将这些分区挂载为 `mnt/boot` 和 `mnt/root`，调整分区代号以匹配启动介质的位置：

[source,console]
----
$ mkdir mnt
$ mkdir mnt/boot
$ mkdir mnt/root
$ sudo mount /dev/sdb1 mnt/boot
$ sudo mount /dev/sdb2 mnt/root
----

===== 安装

接下来，将内核模块安装到启动介质上：

* 对于 64 位内核：
+
[source,console]
----
$ sudo env PATH=$PATH make -j12 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_MOD_PATH=mnt/root modules_install
----

* 对于 32 位内核：
+
[source,console]
----
$ sudo env PATH=$PATH make -j12 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_MOD_PATH=mnt/root modules_install
----

TIP: 在多核设备上， `make -j<n>` 选项可在各核之间分配工作。这会大大加快编译速度。运行 `nproc` 查看你有多少个处理器；我们建议使用处理器数量的 1.5 倍。

接下来，将内核和设备树 blob 安装到启动分区，并备份原始内核。

安装 64 位内核：

* 运行以下命令创建当前内核的备份镜像，安装新的内核镜像、overlays、README，并卸载分区：
+
[source,console]
----
$ sudo cp mnt/boot/$KERNEL.img mnt/boot/$KERNEL-backup.img
$ sudo cp arch/arm64/boot/Image mnt/boot/$KERNEL.img
$ sudo cp arch/arm64/boot/dts/broadcom/*.dtb mnt/boot/
$ sudo cp arch/arm64/boot/dts/overlays/*.dtb* mnt/boot/overlays/
$ sudo cp arch/arm64/boot/dts/overlays/README mnt/boot/overlays/
$ sudo umount mnt/boot
$ sudo umount mnt/root
----

安装 32 位内核：

. 运行以下命令创建当前内核的备份镜像，并安装新的内核镜像：
+
[source,console]
----
$ sudo cp mnt/boot/$KERNEL.img mnt/boot/$KERNEL-backup.img
$ sudo cp arch/arm/boot/zImage mnt/boot/$KERNEL.img
----

. 根据你的 xref:linux_kernel.adoc#identify-your-kernel-version[内核版本]，运行以下命令安装设备树 blobs：
  ** 适用于 6.4 及以下版本的内核：
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/*.dtb mnt/boot/
----
** 适用于 6.5 及以上版本的内核：
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/broadcom/*.dtb mnt/boot/
----
. 最后，安装overlays和 README，并卸载分区：
+
[source,console]
----
$ sudo cp arch/arm/boot/dts/overlays/*.dtb* mnt/boot/overlays/
$ sudo cp arch/arm/boot/dts/overlays/README mnt/boot/overlays/
$ sudo umount mnt/boot
$ sudo umount mnt/root
----

最后，将启动媒体连接到 Raspberry Pi，并接通电源，运行新编译的内核。


[TIP]
====
或者，用不同的文件名复制内核（如 `kernel-myconfig.img`），而不是覆盖 `kernel.img` 文件。然后，编辑启动分区中的 `config.txt` 以选择内核：

[source,ini]
----
kernel=kernel-myconfig.img
----

将此方法与自定义的 `LOCALVERSION` 相结合，可将自定义内核与系统管理的原版内核映像分开。有了这种方法，当你的内核无法启动时，你就可以迅速恢复到原版内核。
====
