[[utilities]]
== 实用程序

Raspberry Pi OS中预装了几个有用的命令行实用程序。

[[kmsprint]]
=== kmsprint

`kmsprint` 工具可用于列出连接到Raspberry Pi的显示器支持的显示模式。使用 `kmsprint` 查看连接到Raspberry Pi的显示器的详细信息，使用 `kmsprint-m` 查看每个显示器支持的所有显示模式的列表。您可以在 https://github.com/tomba/kmsxx[Github] 上找到 `kmsprint` 实用程序的源代码。
=== `vclog`

`vclog` 可从 Arm 上运行的 Linux 中显示来自 VideoCore GPU 的日志信息。它需要以 root 用户身份运行。

`sudo vclog --msg` 会打印信息日志，而 `sudo vclog --assert` 则会打印断言日志。

[[vcgencmd]]
=== `vcgencmd`

`vcgencmd` 工具用于从Raspberry Pi上的 VideoCore GPU 输出信息。您可以在GitHub上找到 https://github.com/raspberrypi/utils/tree/master/vcgencmd[vcgencmd] 源代码。

要获取 `vcgencmd` 支持的所有命令的列表，请使用 `vcgencmd commands` 。下面列出了一些有用的命令及其所需参数。

==== `vcos`

`vcos` 命令有两个有用的子命令：

* `version` 显示VideoCore上固件的构建日期和版本
* `log status` 显示各种VideoCore固件区域的错误日志状态

==== `version`

显示VideoCore固件的构建日期和版本。

[[get_throttled]]
==== `get_throttled`

返回系统的节流状态。这是一个位模式。正在设置的位表示以下含义：

[cols="^,,"]
|===
| 位 | 十六进制值 | 意义

| 0
| `0x1`
| 检测到欠压

| 1
| `0x2`
| ARM频率上限

| 2
| `0x4`
| 当前节流

| 3
| `0x8`
| 软温度限制活动

| 16
| `0x10000`
| 已发生欠压

| 17
| `0x20000`
| 达到Arm频率上限

| 18
| `0x40000`
| 节流已经发生

| 19
| `0x80000`
| 已触发软温度限制
|===

[[measure_temp]]
==== `measure_temp`

返回 SoC 内部温度传感器测得的温度。
在 Raspberry Pi 4 上，`measure_temp pmic` 返回 PMIC 的温度。

==== `measure_clock [clock]`

返回指定时钟的当前频率。接受以下时钟值：

[cols="^,"]
|===
| clock | Description

| `arm`
| ARM core(s)

| `core`
| GPU core

| `h264`
| H.264 block

| `isp`
| Image Sensor Pipeline

| `v3d`
| 3D block

| `uart`
| UART

| `pwm`
| PWM block (analogue audio output)

| `emmc`
| SD card interface

| `pixel`
| Pixel valves

| `vec`
| Analogue video encoder

| `hdmi`
| HDMI

| `dpi`
| Display Parallel Interface
|===

例如  `vcgencmd measure_clock arm` 

==== `measure_volts [block]`

显示特定程序块使用的当前电压。接受以下区块值：

[cols="^,"]
|===
| block | Description

| `core`
| VC4 core voltage

| `sdram_c`
| SDRAM Core Voltage

| `sdram_i`
| SDRAM I/O voltage

| `sdram_p`
| SDRAM Phy Voltage
|===

==== `otp_dump`

显示 SoC 内部 OTP（一次性可编程）存储器的内容。这些内容为 32 位值，索引范围从 8 到 64。详情请参阅 xref:raspberry-pi.adoc#otp-register-and-bit-definitions[OTP 位页面]。

[[getconfig]]
==== `get_config [configuration item|int|str]`

显示指定配置设置的值：或者，指定 `int` （整数）或 `str`（字符串）以查看给定类型的所有配置项。例如，以下命令以 MB 为单位返回设备的总内存：

[source,console]
----
$ vcgencmd get_config total_mem
----

==== `get_mem type`

报告 Arm 和 GPU 可寻址的内存量。要显示 Arm 可寻址的内存量，请使用 `vcgencmd get_mem arm`；要显示 GPU 可寻址的内存量，请使用 `vcgencmd get_mem gpu`。在内存超过 1GB 的设备上，`arm` 参数将始终返回 1GB 减去`gpu`内存值，因为 GPU 固件只知道前 1GB 内存。要获得设备总内存的准确报告，请参阅上文的 `total_mem` 配置项和 <<getconfig,`get_config`>> 部分。

===== `codec_enabled [type]`

报告是否启用了指定的编解码器类型。可能的类型选项有 AGIF、FLAC、H263、H264、MJPA、MJPB、MJPG、MPG2、MPG4、MVC0、PCM、THRA、VORB、VP6、VP8、WMV9 和 WVC1。因为 Raspberry Pi 4 和 400 上的 H.265 HW 块不是 VideoCore GPU 的一部分，因此不能通过此命令访问其状态。

===== `mem_oom`

显示 VideoCore 内存空间中发生的任何 OOM（内存不足）事件的统计数据。

===== `mem_reloc_stats`

显示 VideoCore 上可重置内存分配器的统计数据。

===== `read_ring_osc`

返回环形振荡器当前的速度、电压和温度。
