[[playing-audio-and-video]]
== 播放音频和视频

Raspberry Pi OS 预装了 https://www.videolan.org/[VLC 媒体播放器]。您可以使用 VLC 播放视频和音频文件。VLC 在 Raspberry Pi OS 中使用硬件加速，支持许多流行的音频和视频文件格式。

=== VLC 媒体播放器

==== VLC GUI

要从 Raspberry Pi Desktop 播放音频或视频文件，请在文件管理器中双击文件。这会自动启动 VLC 播放该文件。或者，从 *Sound & Video* 菜单，启动 *VLC Media Player*。然后，从 *Media* 菜单中选择 *Open File...*，并导航到要播放的文件。

默认情况下，Raspberry Pi OS 通过 HDMI 将音频发送到显示器。要将音频输出到耳机插孔或 USB 扬声器等不同接口，请右键单击系统托盘中的扬声器图标并选择一个选项。

==== `vlc` CLI

你也可以通过命令行启动 VLC。在下面的示例中，我们使用了 Big Buck Bunny 的一个短片。要从 Raspberry Pi 上下载该短片，请运行以下命令：

[source,console]
----
$ wget --trust-server-names http://rptl.io/big-buck-bunny
----

要在 VLC 中通过命令行播放片段，请运行以下命令：

[source,console]
----
$ vlc big-buck-bunny-1080p.mp4
----

要防止 VLC GUI 在文件播放完毕后继续打开，请添加 `--play-and-exit` 标记：

[source,console]
----
$ vlc --play-and-exit big-buck-bunny-1080p.mp4
----

要以全屏模式播放视频（在某些情况下播放会更流畅），请添加 `--fullscreen` 标记：

[source,console]
----
$ vlc --play-and-exit --fullscreen big-buck-bunny-1080p.mp4
----

==== 使用 `cvlc` 在没有图形用户界面的情况下播放媒体

如果在这些命令中使用 `cvlc` 而不是 `vlc`，则不会显示 VLC 图形用户界面：

[source,console]
----
$ cvlc --play-and-exit big-buck-bunny-1080p.mp4
----

=== 在 Raspberry Pi OS Lite 上播放音频和视频
与完整版的 Raspberry Pi OS 不同，Raspberry Pi OS Lite 没有预装 VLC。要在 Raspberry Pi OS Lite 上使用 VLC 播放视频和音频，请安装所需的软件包，以便在没有桌面的情况下播放：

[source,console]
----
$ sudo apt install --no-install-recommends vlc-bin vlc-plugin-base
----

在下面的示例中，我们使用了一段简短的音频片段。要从 Raspberry Pi 上下载这个片段，请运行以下命令：

[source,console]
----
$ wget --trust-server-names http://rptl.io/startup-music
----

要在 VLC 中通过命令行播放片段，请运行以下命令：

[source,console]
----
$ cvlc --play-and-exit computer-startup-music.mp3
----

=== 指定音频输出设备

要强制将音频输出到特定设备，可在 `-A` 选项中加入 `alsa` 值以使用 https://www.alsa-project.org/wiki/Main_Page[ALSA] 音频输出，并在 `--alsa-audio-device` 选项中指定音频输出设备：

[source,console]
----
$ cvlc --play-and-exit -A alsa --alsa-audio-device <alsa-device> computer-startup-music.mp3
----

用以下选项之一替换 `<alsa-device>` 占位符：

|===
| ALSA device | Description

| `sysdefault:CARD=Headphones` | The headphone jack

| `sysdefault:CARD=vc4hdmi` | The HDMI output on devices with a single HDMI port (Zero models, CM4S, Compute Modules prior to CM4, and Flagship models prior to Raspberry Pi 4)

| `sysdefault:CARD=vc4hdmi0` | The HDMI0 output on Flagship models since Raspberry Pi 4B, Compute Modules since CM4, and Keyboard models

| `sysdefault:CARD=vc4hdmi1` | The HDMI1 output on Flagship models since Raspberry Pi 4B, Compute Modules since CM4, and Keyboard models

|===

[TIP]
====
使用以下命令获取 Raspberry Pi 上所有 ALSA 设备的列表：

[source,console]
----
aplay -L | grep sysdefault
----
====

=== 指定视频输出设备

要强制将视频输出到特定设备，请使用 `--drm-vout-display` 选项指定视频输出设备：

[source,console]
----
$ cvlc --play-and-exit --drm-vout-display <drm-device> big-buck-bunny-1080p.mp4
----

用以下选项之一替换 `<drm-device>` 占位符：

|===
| DRM device | Description

| `HDMI-A-1` | The HDMI output on a Raspberry Pi Zero, or Raspberry Pi Model 1, 2 or 3; *or* the HDMI0 output on a Raspberry Pi 4, 5, or 400

| `HDMI-A-2` | The HDMI1 output on Flagship models since Raspberry Pi 4B, Compute Modules since CM4 (including CM4S), and Keyboard models

| `DSI-1` | The Raspberry Pi Touch Display or Raspberry Pi Touch Display 2

| `DSI-2` | The second DSI output for models with multiple DSI ports (Flagship models since Raspberry Pi 5, and Compute Module models since CM5)

|===

[TIP]
====
使用以下命令获取 Raspberry Pi 上所有 DRM 设备的列表：

[source,console]
----
$ kmsprint | grep Connector
----
====

=== 同时指定音频和视频输出设备

您可以将音频和视频输出选项结合起来。例如，要将视频输出引向触摸屏，将音频输出引向耳机插孔，请使用上述命令的以下组合：

[source,console]
----
$ cvlc --play-and-exit --fullscreen --drm-vout-display DSI-1 -A alsa --alsa-audio-device sysdefault:CARD=Headphones your_video.mp4
----

=== 提高数据流播放性能

如果您有原始的 H.264 数据流，例如从 Raspberry Pi 摄像头模块捕获的数据流，您可以通过将数据流封装在 MP4 等容器格式中来提高 VLC 的播放性能。你可以使用 `ffmpeg` 将流内容转换为容器文件。例如，下面的命令将名为 `video.h264` 的数据流以 30fps 的速度转换为名为 `video.mp4` 的 MP4 容器：

[source,console]
----
$ ffmpeg -r 30 -i video.h264 -c:v copy video.mp4
----
