[[update-software]]
== 更新软件

始终将 Raspberry Pi 上运行的软件更新到最新版本。这将确保您的设备免受 https://cve.mitre.org/index.html[漏洞] 的威胁，并确保您获得最新的错误修复。

=== 使用 APT 管理软件包

https://en.wikipedia.org/wiki/APT_(software)[高级软件包工具(APT)]是在 Raspberry Pi 操作系统中安装、更新和删除软件的推荐方法。您可以通过 `apt` CLI 访问 APT。

==== 安装更新

`apt`  会在文件 `/etc/apt/sources.list` 中存储软件源列表。安装软件前，请运行以下命令，使用 `/etc/apt/sources.list` *更新* 本地软件包列表：

[source,console]
----
$ sudo apt update
----

运行以下命令，将所有已安装的软件包升级到最新版本：

[source,console]
----
$ sudo apt full-upgrade
----

TIP: 与 Debian 不同，Raspberry Pi OS 正在持续开发中。因此，软件包依赖关系有时会发生变化，所以你应该始终使用 `full-upgrade` 而不是标准的 `upgrade`。

定期运行这些命令以保持软件最新。使用 `apt` 保持 Raspberry Pi OS 的最新版本，也能保持 Linux 内核和固件的最新版本，因为 Raspberry Pi 将它们作为 Debian 软件包发布。

当 Raspberry Pi 发布新的 Raspberry Pi OS 主版本时，上述命令不会将你的操作系统升级到新的主版本。要升级到新的主版本，请遵循我们的 xref:os.adoc#upgrade-your-operating-system-to-a-new-major-version[操作系统升级说明]。

==== 搜索软件

要搜索存档软件包，请向 `apt-cache search` 传递搜索关键字：

[source,console]
----
$ apt-cache search <keyword>
----

例如，下面是对关键字 "raspi" 的搜索：

[source,console]
----
$ apt-cache search raspi
raspi3-firmware - Raspberry Pi 2 and 3 GPU firmware and bootloaders
libcamera-apps - libcamera-apps
libcamera-apps-lite - libcamera-apps-lite
python-picamera - Pure Python interface to the Raspberry Pi's camera module.
python-picamera-docs - Documentation for the Python interface to the RPi's camera module.
python3-picamera - Pure Python interface to the Raspberry Pi's camera module.
raspi-config - Raspberry Pi configuration tool
raspi-gpio - Dump the state of the BCM270x GPIOs
raspi-gpio-dbgsym - debug symbols for raspi-gpio
raspinfo - Dump information about the Pi
rc-gui - raspi-config GUI
raspi-copies-and-fills - ARM-accelerated versions of selected functions from string.h
raspi-copies-and-fills-dbgsym - debug symbols for raspi-copies-and-fills
----

搜索会返回多个名称或描述包含关键字的软件包。

使用以下命令查看软件包的详细信息：

[source,console]
----
$ apt-cache show <package-name>
----

例如，下面是对 "raspi-config "软件包的查询：

[source,console]
----
$ apt-cache show raspi-config
Package: raspi-config
Version: 20210212
Architecture: all
Maintainer: Serge Schneider <serge@raspberrypi.org>
Installed-Size: 121
Depends: whiptail, parted, lua5.1, alsa-utils, psmisc, initramfs-tools
Recommends: triggerhappy, iw
Priority: optional
Section: utils
Filename: pool/main/r/raspi-config/raspi-config_20210212_all.deb
Size: 27976
SHA256: 772d4fd3c6d8c9da47ac56012b74e7828b53c8521ff1c47266bb38ec71750c10
SHA1: 08254c976a8260bde914c2df72f92ffb9317fef6
MD5sum: 80aaac13be6a9b455c822edb91cf8ea2
Description: Raspberry Pi configuration tool
 A simple configuration tool for common Raspberry Pi administrative tasks
Description-md5: 19630c04463bfe7193152448b53d85a0
----

使用此命令可验证软件包的维护者、版本和大小是否符合您的预期。

==== 安装软件包

要在 Raspberry Pi 上安装软件包，请在以下命令中输入软件包的名称：

[source,console]
----
$ sudo apt install <package-name>
----

`apt` 将显示软件包将占用的磁盘空间。输入 *Y*，然后按 **Enter** 确认软件包的安装。在上述命令中添加 `-y` 标志可跳过这一确认步骤。

==== 卸载软件包

要卸载 Raspberry Pi 上的软件包，请将软件包的名称输入以下命令：

[source,console]
----
$ sudo apt remove <package-name>
----

TIP: 要完全删除软件包的所有痕迹，包括配置文件，请使用 `purge` 而不是 `remove`。

`apt` 将显示删除软件包将释放的磁盘空间。
输入 *Y*，然后按 **Enter** 确认删除软件包。在上述命令中添加 `-y` 标志可跳过确认步骤。

==== 管理 `apt` 磁盘使用量

在运行之前，`sudo apt full-upgrade` 会显示为完成升级而需要下载并存储在磁盘上的数据大小。要检查是否有足够的可用磁盘空间，请运行以下命令：

[source,console]
----
$ df -h
----

`apt` 将下载的软件包 (`.deb`) 文件存储在 `/var/cache/apt/archives` 中。在安装过程中，`apt` 会下载这些软件包，然后将软件包中的文件复制到正确的安装位置。根据所安装软件的不同，软件包文件可能会占用大量空间。要删除任何残留的软件包文件，请运行以下命令：

[source,console]
----
$ sudo apt clean
----

=== 将操作系统升级到新的主要版本

WARNING: 在尝试主要版本升级之前，请先进行备份。

要在 Raspberry Pi 上将操作系统升级到新的主要版本，请将新版本映像到第二张 SD 卡上。使用 USB SD 读卡器或网络存储设备将当前安装的文件和配置复制到新的 SD 卡上。然后，将新的 SD 卡插入 Raspberry Pi 的插槽并启动。

[[rpi-update]]
=== 升级固件

WARNING: 在尝试固件升级之前，请先进行备份。

WARNING: 不保证预发布版本的软件可以正常工作。除非得到 Raspberry Pi 工程师的建议，否则不要在任何系统上使用 `rpi-update`。这会导致系统不可靠或损坏。请勿将 `rpi-update` 用作任何定期更新过程的一部分。

要将 Raspberry Pi 上的固件更新到最新版本，请使用 https://github.com/raspberrypi/rpi-update[`rpi-update`]。

`rpi-update` 会下载最新预发布版本的 Linux 内核、其匹配模块、设备树文件和最新版本的 VideoCore 固件。然后将这些文件安装到现有的 Raspberry Pi OS 安装中。

rpi-update` 使用的所有源数据都来自 https://github.com/raspberrypi/rpi-firmware[`rpi-firmware` 资源库]。该版本库包含 https://github.com/raspberrypi/firmware[官方固件版本库]中数据的子集。

以根用户身份运行 `rpi-update` 启动更新。更新完成后，重启 Raspberry Pi 以使更改生效：

[source,console]
----
$ sudo rpi-update
$ sudo reboot
----

[.whitepaper, title="更新 Raspberry Pi 固件", subtitle="", link=https://pip.raspberrypi.com/categories/685-whitepapers-app-notes/documents/RP-003476-WP/Updating-Pi-firmware.pdf]
****
本白皮书记录了如何更新 Raspberry Pi OS 映像中的 VideoCore 固件。
****

=== 将固件降级到上一个稳定版本

如果您将固件更新到最新版本，但遇到问题，请使用以下命令返回到上一个稳定固件版本：

[source,console]
----
$ sudo apt update
$ sudo apt install --reinstall raspi-firmware
----

[NOTE]
====
如果仍在运行 Raspberry Pi OS Bullseye，则必须使用以下命令重新安装 `raspberrypi-kernel`：

[source,console]
----
$ sudo apt install --reinstall libraspberrypi0 libraspberrypi-{bin,dev,doc} raspberrypi-{kernel,bootloader}
----

使用 `sudo reboot` 重启 Raspberry Pi，使这些更改生效。
====
