== 概述

Raspberry Pi音频板为您现有的高保真或基于Raspberry Pi的设备和项目带来高质量的音频。我们提供四种不同的顶部附加硬件（HAT）选项，适用于使用40针GPIO接头的任何Raspberry Pi。

每个板卡都有特定的用途和一组功能。我们的DAC PRO、DAC{plus}和DigiAMP{plus}板卡提供最高音频质量的播放，支持高达HD音频（192kHz）；而Codec Zero支持高达HD音频（96kHz），并包括一个内置麦克风，非常适合紧凑型项目。

=== 功能一览

[cols="2,1,1,1,1,1,1,1,1,1"]
|===
| | *Line out* | *Balanced out* | *Stereo speakers* | *Mono speaker* | *Headphones* | *Aux in* | *Aux out* | *Ext mic* | *Built-in mic*

| DAC Pro ^| ✓ ^| ✓ | | ^| ✓ | | | | 
| DAC{plus} ^| ✓ | | | ^| ✓ | | | | 
| DigiAmp{plus} | | ^| ✓ | | | | | | 
| Codec Zero | | | ^| ✓ | ^| ✓ ^| ✓ ^| ✓ ^| ✓ 
|===

排线:: 双唱机/RCA连接器，通常为红色和白色。此输出是一个变量
模拟信号（0-2V RMS），可以连接到您现有的高保真（前置放大器或放大器），也可以使用
驱动内置放大器的有源扬声器。
平衡:: XLR连接器，通常是三针公连接器。这用于工作室设置，在一些
高端高保真系统。它也可以用来驱动有源监听扬声器，比如俱乐部或
舞台指向DJ或表演者。
立体声扬声器:: 两套用于2×25W扬声器的螺丝端子。这些用于没有内置放大的传统高保真扬声器。这些被称为无源扬声器。
单声道扬声器:: 用于单个1.2W扬声器的螺丝端子，如晶体管收音机或类似产品中所示。
耳机:: 为一组耳机提供立体声音频的3.5毫米插孔插座。Raspberry Pi DAC板上的耳机放大器可以驱动高达80/90Ω阻抗的耳机。
辅助:: 双Phono/RCA连接器或3.5毫米插座。接受高达1V RMS的模拟音频。这可用于录制来自可变模拟源（如手机、MP3播放器或类似设备）的音频。
辅助输出:: 双Phono/RCA连接器或3.5毫米插座。提供高达1V RMS的模拟音频输出。与线路输出相比，这可用于以较小的音量将音频馈入放大器。
外部麦克风:: 一个3.5毫米插座，用于外部驻极体麦克风。当使用外部麦克风输入连接器时，Codec Zero上的内置MEMS麦克风会自动禁用。
