=== Use the Build HAT from .NET

Raspberry Pi Built HAT 在乐高®术语中被称为 “Brick”，您可以使用 https://datasheets.raspberrypi.com/build-hat/build-hat-serial-protocol.pdf[Build HAT串行协议]通过.NET与它直接对话。

您可以创建一个 `brick` 对象，如下所示，

[source,csharp]
----
Brick brick = new("/dev/serial0");
----

但您需要记住在代码末尾处理 `brick`。

[source,csharp]
----
brick.Dispose();
----

WARNING: 如果您不调用 `brick.Dispose()`，您的程序将不会终止。

如果您想避免在最后调用 `brick.Dispose`，请使用 `using` 语句创建砖块：

[source,csharp]
----
using Brick brick = new("/dev/serial0");
----

在这种情况下，当到达程序结束时，您的砖块将被自动处理。

==== Display Build HAT information

您可以收集各种软件版本、签名和输入电压：

[source,csharp]
----
var info = brick.BuildHatInformation;
Console.WriteLine($"version: {info.Version}, firmware date: {info.FirmwareDate}, signature:");
Console.WriteLine($"{BitConverter.ToString(info.Signature)}");
Console.WriteLine($"Vin = {brick.InputVoltage.Volts} V");
----

NOTE: 输入电压在启动时只读取一次，之后不会再次读取。

==== Getting sensors and motors details

功能 `GetSensorType`、`GetSensor` 将允许您检索有关连接传感器的任何信息。

[source,csharp]
----
SensorType sensor = brick.GetSensorType((SensorPort)i);
Console.Write($"Port: {i} {(Brick.IsMotor(sensor) ? "Sensor" : "Motor")} type: {sensor} Connected: ");
----

在此示例中，您也可以使用 `IsMotor` 静态函数来检查连接的元件是传感器还是电机。

[source,csharp]
----
if (Brick.IsActiveSensor(sensor))
{
    ActiveSensor activeSensor = brick.GetActiveSensor((SensorPort)i);
}
else
{
    var passive = (Sensor)brick.GetSensor((SensorPort)i);
    Console.WriteLine(passive.IsConnected);
}
----

`ActiveSensor` 有一个高级属性和功能的集合，允许理解传感器的每个元素。也可以从砖块中调用原始函数。这将允许您选择特定模式并进行高级场景。虽然这是可能的，但电机和传感器类已经创建，让您的生活更轻松。

==== Events

大多数传感器在其特殊属性上实现事件。您可以简单地订阅 `PropertyChanged` 和 `PropertyUpdated`。更改后的值将在值更改时触发，而更新后的值将在属性成功更新时触发。根据使用的模式，一些属性可能一直在后台更新，而另一些属性偶尔会更新。

只有当颜色发生变化或电机位置发生变化时，您才会感兴趣，将其用作转速计。在这种情况下，`PropertyChanged` 就是您需要的！

[source,csharp]
----
Console.WriteLine("Move motor on Port A to more than position 100 to stop this test.");
brick.WaitForSensorToConnect(SensorPort.PortA);
var active = (ActiveMotor)brick.GetMotor(SensorPort.PortA);
bool continueToRun = true;
active.PropertyChanged += MotorPropertyEvent;
while (continueToRun)
{
    Thread.Sleep(50);
}

active.PropertyChanged -= MotorPropertyEvent;
Console.WriteLine($"Current position: {active.Position}, eventing stopped.");

void MotorPropertyEvent(object? sender, PropertyChangedEventArgs e)
{
    Console.WriteLine($"Property changed: {e.PropertyName}");
    if (e.PropertyName == nameof(ActiveMotor.Position))
    {
        if (((ActiveMotor)brick.GetMotor(SensorPort.PortA)).Position > 100)
        {
            continueToRun = false;
        }
    }
}
----

==== Wait for initialization

brick可能需要很长时间才能初始化。已实现等待连接传感器。

[source,csharp]
----
brick.WaitForSensorToConnect(SensorPort.PortB);
----

如果您想实现高级功能（例如在一段时间后警告用户并重试），也需要 `CancellationToken`。
