[[legacy-boot-options]]
== 旧版引导选项
（另请参见 xref:config_txt.adoc#boot-options[config.txt Boot Options]。）

[[start_x-start_debug]]
=== `start_x` , `start_debug` 

这些提供了一些替代 `start_file` 和 `fixup_file` 设置的快捷方式，并且是选择固件配置的推荐方法。

`start_x=1` 
----
  start_file=start_x.elf
  fixup_file=fixup_x.dat
----

在Raspberry Pi 4上，如果存在文件 `start4x.elf` 和 `fixup4x.dat` ，则将使用这些文件。

`start_debug=1` 
----
  start_file=start_db.elf
  fixup_file=fixup_db.dat
----

[[disable_commandline_tags]]
=== `disable_commandline_tags` 

将 `disable_commandline_tags` 命令设为 `1` ，以阻止 `start.elf` 在启动内核前填写 ATAGS（来自 `0x100` 的内存）。

[[arm_control]]
=== `arm_control` 

WARNING: 此设置已弃用。请改用 `arm_64bit` 来启用64位内核。

设置特定于板的控制位。

[[armstub]]
=== `armstub` 

`armstub` 是引导分区中加载 ARM 存根的文件名。默认 ARM 存根存储在固件中，并根据 Raspberry Pi 型号和各种设置自动选择。

存根是先于内核运行的一小段 ARM 代码。它的任务是在将控制权传递给内核之前设置中断控制器等低级硬件。

[[arm_peri_high]]
=== `arm_peri_high` 

将 `arm_peri_high` 设置为 `1` 以在 Raspberry Pi 4 上启用高外设模式。如果加载了合适的DTB，它会自动设置。

NOTE: 在没有兼容设备树的情况下启用高外设模式将使您的系统无法启动。目前缺少 ARM 存根支持，因此您还需要使用 `armstub` 加载合适的文件。

[[kernel_address]]
=== `kernel_address` 

`kernel_address` 是加载内核映像的内存地址。默认情况下，32 位内核加载到地址 `0x8000` ，64 位内核加载到地址 `0x200000` 。如果设置了 `kernel_old` ，内核将被加载到地址 `0x0` 。

[[kernel_old]]
=== `kernel_old` 

将 `kernel_old` 设置为1，将内核加载到内存地址 `0x0` 。

[[init_uart_baud]]
=== `init_uart_baud` 

`init_uart_baud` 是UART的初始波特率。默认值为 `115200` 。

[[init_uart_clock]]
=== `init_uart_clock` 

`init_uart_clock` 是初始 UART 时钟频率。默认值为 `48000000` (48MHz)。请注意，该时钟仅适用于 UART0（Linux 中为 ttyAMA0），UART 的最大波特率限制为时钟的 1/16。Raspberry Pi 3 和 Raspberry Pi Zero 的默认 UART 为 UART1（Linux 中为 ttyS0），其时钟为核心 VPU 时钟 - 至少 250MHz。

[[bootcode_delay]]
=== `bootcode_delay` 

`bootcode_delay` 命令会在 `bootcode.bin` 中设置延迟秒数，然后再加载 `start.elf` ：默认值为 `0` 。

例如，如果 Raspberry Pi 和显示器的电源相同，但显示器的启动时间比 Raspberry Pi 长，那么在读取显示器的 EDID 之前插入一个延迟值就特别有用。如果在初始启动时显示器检测错误，但在软启动 Raspberry Pi 而不移除显示器电源时检测正确，请尝试设置该值。

[[boot_delay]]
=== `boot_delay` 

`boot_delay` 命令在加载内核之前强制在start中等待给定的秒数：默认值为0。以毫秒为单位的总延迟计算为 `(1000 x boot_delay) + boot_delay_ms` 。如果您的SD卡需要一段时间才能准备好，这将非常有用Linux。

[[boot_delay_ms]]
=== `boot_delay_ms` 

`boot_delay_ms` 命令表示在加载内核之前，在start中等待给定的毫秒数和boot_delay。默认值为0。

[[enable_gic-raspberry-pi-4-only]]
=== `enable_gic` （仅限Raspberry Pi 4）

在Raspberry Pi 4B上，如果该值设置为 `0` ，则中断将使用传统中断控制器而不是通过GIC-400路由到Arm内核。默认值为 `1` 。

[[sha256]]
=== `sha256` 

如果设置为非零，则启用由 `sha256sum` 实用程序生成的加载文件（内核、initramfs、设备树.dtb文件和overlay）的SHA256哈希记录。如果启用，日志记录输出将转到UART，也可以通过 `sudo vclog--msg` 访问。此选项在调试启动问题时可能很有用，但代价是可能会增加_many_秒的启动时间。在所有平台上默认为0。

[[uart_2ndstage]]
=== `uart_2ndstage` 

设置 `uart_2ndstage=1` 会导致第二阶段加载程序（Raspberry Pi 4之前设备上的 `bootcode.bin` ，或Raspberry Pi 4设备的EEPROM中的引导代码）和主固件（ `start*.elf` ）将诊断信息输出到UART0。


[[upstream_kernel]]
=== `upstream_kernel` 

如果使用了 `upstream_kernel=1` ，固件会将 xref:config_txt.adoc#os_prefix[`os_prefix`] 设置为 "upstream/"，除非已明确设置为其他值，但与其他 `os_prefix` 值一样，如果在使用前缀时无法找到所需的内核和 .dtb 文件，该值将被忽略。

固件也会优先选择上游 Linux 的 DTB 名称（例如，"bcm2837-rpi-3-b.dtb "而不是 "bcm2710-rpi-3-b.dtb"）。如果找不到上游文件，固件将加载下游变体，并自动应用 "上游 "覆盖进行一些调整。请注意，这个过程是在 `os_prefix` 确定之后发生的。
