== 旧内存选项
（另请参见 xref:config_txt.adoc#memory-options[config.txt内存选项]）

NOTE: Raspberry Pi 5 不会代表操作系统分配 GPU 内存，因此以下设置不会产生任何影响。

[[gpu_mem]]
=== `gpu_mem` 

指定为GPU独占使用预留多少内存（以兆字节为单位）：剩余内存分配给Arm CPU供操作系统使用。对于内存小于1GB的Raspberry Pi，默认值为 `64` ；对于内存为1GB或更多的Raspberry Pi，默认值为 `76` 。

IMPORTANT: 与x86机器上的GPU不同，增加内存可以提高3D性能，VideoCore的架构意味着 *分配超过必要内存不会提高3D性能*，这样做实际上会损害性能。

为确保Linux的最佳性能，您应该将 `gpu_mem` 设置为尽可能低的值。如果特定图形功能无法正常工作，请尝试增加 `gpu_mem` 的值，同时注意下面显示的推荐最大值。

在Raspberry Pi 4上，GPU的3D组件有自己的内存管理单元（MMU），并且不使用来自 `gpu_mem` 分配的内存。相反，内存是在Linux内动态分配的。与以前的型号相比，这允许在Raspberry Pi 4上为 `gpu_mem` 指定更小的值。

在传统内核上，分配给GPU的内存用于显示、3D、编解码器和相机目的，以及一些基本的固件管理。下面指定的最大值假定您正在使用所有这些功能。如果不是，则应使用较小的gpu_mem值。

建议的最大值如下：

|===
| 总 RAM | `gpu_mem` 推荐最大值

| 256MB
|  `128` 

| 512MB
|  `384` 

| 1GB 或更大
| 在Raspberry Pi 4上配置 `512` , `76` 
|===

IMPORTANT: 树莓派操作系统上的相机堆栈（libcamera）使用LinuxCMA内存来分配缓冲区，而不是GPU内存，因此增加GPU内存大小没有好处。

可以将 `gpu_mem` 设置为较大的值，但是应该避免这样做，因为它会导致问题，例如阻止Linux启动。最小值是 `16` ，但是这会禁用某些GPU功能。

您还可以使用 `gpu_mem_256`、 `gpu_mem_512` 和 `gpu_mem_1024` ，以便在内存容量不同的 Raspberry Pi 之间交换同一张 SD 卡，而无需每次都编辑 `config.txt` ：

[[gpu_mem_256]]
=== `gpu_mem_256` 

`gpu_mem_256` 命令为具有256MB内存的Raspberry Pi设置GPU内存（以兆字节为单位）。如果内存大小不是256MB，则忽略该命令。该命令会覆盖 `gpu_mem` 。

[[gpu_mem_512]]
=== `gpu_mem_512` 

`gpu_mem_512` 命令为具有512MB内存的Raspberry Pi设置GPU内存（以兆字节为单位）。如果内存大小不是512MB，则忽略该命令。该命令会覆盖 `gpu_mem` 。

[[gpu_mem_1024]]
=== `gpu_mem_1024` 

`gpu_mem_1024` 命令为具有1GB或更多内存的Raspberry Pi设置GPU内存（以兆字节为单位）。如果内存小于1GB，则忽略该命令。该命令会覆盖 `gpu_mem` 。

[[disable_l2cache]]
=== `disable_l2cache` 

将其设置为 `1` 将禁止 CPU 访问 GPU 的二级缓存，并需要相应的二级禁用内核。BCM2835 上的默认值为 `0` 。在 BCM2836、BCM2837、BCM2711 和 BCM2712 上，ARM 拥有自己的二级缓存，因此默认值为 `1` 。标准的 Raspberry Pi `kernel.img` 和 `kernel7.img` 版本反映了缓存设置的这种差异。

