== 使用IPv6进行网络引导

通过网络引导Raspberry Pi计算机有4个阶段：

1. 引导加载程序协商使用DHCP获取IP地址和TFTP服务器的详细信息。
2. 引导加载程序通过TFTP加载固件并将引导过程移交给固件，将网络的详细信息传递给固件。
3. 固件通过TFTP加载内核和命令行。
4. 内核引导系统的其余部分，通过NFS或其他机制加载根文件系统（rootfs）。

引导加载程序和固件（阶段1到3）已得到增强，以支持通过IPv6引导。

IMPORTANT: IPv6 netboot是一项 *实验性alpha功能*，根据反馈，我们将来可能需要改变它的工作方式。这仅适用于Raspberry Pi 4和计算模块4。

=== 它是如何工作的

要通过IPv6启动，您需要更新版本的固件（例如 `start4.elf` ）和引导加载程序。使用最新版本的Raspberry Pi OS和最新的稳定引导加载程序应该就足够了。

NOTE: 常用的 `dnsmasq` DHCP服务器当前不支持IPv6网络引导所需的网络引导参数，因此目前您必须使用不同的DHCP服务器，例如 https://www.isc.org/dhcp/[ISC DHCP]。

要在网络上挂载rootfs， xref:remote-access.adoc#network-boot-your-raspberry-pi[IPv4 netboot教程] 建议使用nfsroot。这不支持IPv6，因此需要另一种方法在网络上挂载rootfs。

如果您的ISP和路由器不支持IPv6，您的功能将受到限制。

==== 网络地址

引导加载程序所做的第一件事是向路由器发送请求以获取网络的详细信息。路由器响应一个标识其以太网地址的广告包，如果TFTP服务器在不同的网络上，引导加载程序可能需要这个地址。

路由器通告包括一个标志，告诉它是对其IP地址使用有状态（托管）还是无状态（非托管）配置。无状态配置意味着设备配置自己的IP地址。目前，引导加载程序生成一个源自其以太网MAC地址的地址和路由器提供的网络前缀。

如果路由器指示启用了状态配置，则使用DHCP来获取设备的IP地址。这包括设备向DHCP服务器发送请求，DHCP服务器以广告响应。然后客户端在从服务器获得回复确认之前请求地址。

DHCP服务器和客户端使用可变长度DUID（设备唯一ID）标识自己。在Raspberry Pi上，这来自MAC地址（DUID_LL）。

==== TFTP地址

无论是使用无状态配置还是有状态配置，DHCP服务器都用于获取TFTP服务器地址。这被编码在 `BOOTFILE-URL` 参数中。我们发送客户端架构类型值 `0x29` 来识别设备。

请参阅 https://datatracker.ietf.org/doc/html/rfc5970[RFC 5970]和 https://www.iana.org/assignments/dhcpv6-parameters/dhcpv6-parameters.xhtml[IANA IPv6动态主机设置协议] 文档。

==== 启动过程

该设备现在应该有一个IP地址和TFTP详细信息。它从TFTP服务器下载固件二进制文件 `start 4.elf` 并继续运行。固件被传递IP地址和TFTP服务器详细信息，以便它可以下载内核并启动系统的其余部分。

==== 内核引导

对于IPv4 netboot， `nfsroot` 用于通过网络挂载 `rootfs` 。这不支持IPv6，因此需要另一种解决方案。它可能涉及一个小型RAM文件系统，可以在切换到正确的 `rootfs` 内容之前挂载适当的网络位置。

NOTE: 通过IPv6使用NFS引导Linux内核的机制仍有待演示。

=== 测试设置

如果您想尝试一下，您将需要另一个Raspberry Pi来充当TFTP和DHCP服务器。

理论上，TFTP服务器可以在任何可路由的网络上，但DHCP服务器必须与其服务的设备位于同一网络上。

==== TFTP服务器

如果您有一个有效的IPv4网络启动设置，您可以重用dnsmasq中的TFTP服务器来提供文件（它可以与IPv4和
IPv6）。

或者，您可以使用独立的TFTP服务器，例如 `tftpd-hpa` 。

[,bash]
----
$ sudo apt install tftpd-hpa
$ sudo systemctl start tftpd-hpa
----

==== DHCP服务器

IPv6中的DHCP发生了很大变化。我们需要DHCP至少告诉我们TFTP服务器的地址，在这种情况下是同一台机器。

[,bash]
----
$ sudo apt install isc-dhcp-server
----

修改 `/etc/default/isc-dhcp-server` 中的配置

[,bash]
----
DHCPDv6_CONF=/etc/dhcp/dhcpd6.conf
INTERFACESv6="eth0"
----

在 `/etc/dhcp/dhcpd6.conf` 中，您需要指定 TFTP 服务器地址并设置子网。此处，DHCP 服务器配置为提供一些虚构的唯一本地地址 (ULA)。 `host test-rpi4` 行告诉 DHCP 为测试设备提供固定地址。

----
not authoritative;

# 检查客户端看起来是否为 Raspberry Pi
if option dhcp6.client-arch-type = 00:29 {
option dhcp6.bootfile-url "tftp://[fd49:869:6f93::1]/";
}

subnet6 fd49:869:6f93::/64 {
host test-rpi4 {
host-identifier option dhcp6.client-id 00:03:00:01:e4:5f:01:20:24:0b;
fixed-address6 fd49:869:6f93::1000;
}
}
----

必须在 `/etc/dhcpcd.conf` 中为您的服务器分配 IPv6 地址

----
interface eth0
static ip6_address=fd49:869:6f93::1/64
----

现在启动 DHCP 服务器。

[,bash]
----
$ sudo systemctl restart isc-dhcp-server.service
----

[[bootloader]]
==== Bootloader

修改配置以告诉它尝试通过 IPv6 而不是 IPv4 进行网络启动。

----
BOOT_ORDER=0xf21 # 2=网络启动
USE_IPV6=1 # 启用 IPv6 网络启动
BOOT_UART=1 # 调试
----

要恢复到 IPv4 网络启动，只需从 `boot.conf` 中删除 `USE_IPV6` 行。

==== 路由器

要使用 IPv6，您确实需要支持 IPv6 的路由器和 ISP。互联网上有一些网站可以为您检查这一点，或者您也可以运行以下命令。

[,bash]
----
sudo apt install ndisc6
rdisc6 -1 eth0
----

这会向您的路由器发送路由器请求，询问您的网络详细信息，例如网络前缀、路由器以太网地址以及是否使用 DHCP 进行寻址。如果此命令没有响应，则可能是您的网络和 ISP 仅支持 IPv4。如果支持 IPv6，则很可能将其配置为使用无状态配置，客户端会生成自己的地址。

----
Soliciting ff02::2 (ff02::2) on eth0...
Hop limit                 :           64 (      0x40)
Stateful address conf.    :           No
Stateful other conf.      :          Yes
Mobile home agent         :           No
Router preference         :       medium
Neighbor discovery proxy  :           No
Router lifetime           :          180 (0x000000b4) seconds
Reachable time            :  unspecified (0x00000000)
Retransmit time           :  unspecified (0x00000000)
----


您可能能够将路由器配置为全状态配置，这意味着它将使用 DHCP 获取 IP 地址。

----
Hop limit                 :           64 (      0x40)
Stateful address conf.    :          Yes
Stateful other conf.      :          Yes
Mobile home agent         :           No
Router preference         :       medium
Neighbor discovery proxy  :           No
Router lifetime           :          180 (0x000000b4) seconds
Reachable time            :  unspecified (0x00000000)
Retransmit time           :  unspecified (0x00000000)
----

=== 调试

==== 日志和跟踪

如果启用了启动 UART，您应该会从串行端口看到类似这样的内容。以 RX6 开头的行表示正在使用 IPv6。

此处 `dc:a6:32:6f:73:f4` 是 TFTP 服务器的 MAC 地址，其 IPv6 地址为 `fd49:869:6f93::1` 。设备本身具有 MAC 地址 `e4:5f:01:20:24:0b` 和 IPv6 地址 `fd49:869:6f93::1000` 

----
Boot mode: NETWORK (02) order f
GENET: RESET_PHY
PHY ID 600d 84a2
NET_BOOT: e4:5f:01:20:24:0b wait for link TFTP6: (null)
LINK STATUS: speed: 100 full duplex
Link ready
GENET START: 64 16 32
GENET: UMAC_START 0xe45f0120 0x240b0000
RX6: 12 IP: 1 MAC: 1 ICMP: 1/1 UDP: 0/0 ICMP_CSUM_ERR: 0 UDP_CSUM_ERR: 0
NET fd49:869:6f93::1000 tftp fd49:869:6f93::1
RX6: 17 IP: 4 MAC: 4 ICMP: 2/2 UDP: 2/2 ICMP_CSUM_ERR: 0 UDP_CSUM_ERR: 0
TFTP_GET: dc:a6:32:6f:73:f4 fd49:869:6f93::1 ab5a4158/start4.elf

RX6: 17 IP: 4 MAC: 4 ICMP: 2/2 UDP: 2/2 ICMP_CSUM_ERR: 0 UDP_CSUM_ERR: 0
RX6: 18 IP: 5 MAC: 5 ICMP: 2/2 UDP: 3/3 ICMP_CSUM_ERR: 0 UDP_CSUM_ERR: 0
TFTP_GET: dc:a6:32:6f:73:f4 fd49:869:6f93::1 ab5a4158/config.txt
----

最后，引导加载程序将移交给应加载内核的固件。

==== 状态配置

您可以使用 tcpdump 检查网络活动。

[source,console]
----
$ sudo tcpdump -i eth0 -e ip6 -XX -l -v -vv
----

以下是 TCP 转储的摘录，其中路由器配置为使用状态（DHCP）网络配置。

设备发送路由器请求。

----
12:23:35.387046 e4:5f:01:20:24:0b (oui Unknown) > 33:33:00:00:00:02 (oui Unknown), ethertype IPv6 (0x86dd), length 70: (hlim 255, next-header ICMPv6 (58) payload length: 16) fe80::e65f:1ff:fe20:240b > ip6-allrouters: [icmp6 sum ok] ICMP6, router solicitation, length 16
          source link-address option (1), length 8 (1): e4:5f:01:20:24:0b
            0x0000:  e45f 0120 240b
----

路由器发送一个响应，告诉设备使用有状态配置。

----
12:23:35.498902 60:8d:26:a7:c1:88 (oui Unknown) > 33:33:00:00:00:01 (oui Unknown), ethertype IPv6 (0x86dd), length 110: (hlim 255, next-header ICMPv6 (58) payload length: 56) bthub.home > ip6-allnodes: [icmp6 sum ok] ICMP6, router advertisement, length 56
        hop limit 64, Flags [managed, other stateful], pref medium, router lifetime 180s, reachable time 0ms, retrans timer 0ms
          rdnss option (25), length 24 (3):  lifetime 60s, addr: bthub.home
            0x0000:  0000 0000 003c fe80 0000 0000 0000 628d
            0x0010:  26ff fea7 c188
          mtu option (5), length 8 (1):  1492
            0x0000:  0000 0000 05d4
          source link-address option (1), length 8 (1): 60:8d:26:a7:c1:88
            0x0000:  608d 26a7 c188
----

设备发送DHCP请求。

----
12:23:35.502517 e4:5f:01:20:24:0b (oui Unknown) > 33:33:00:01:00:02 (oui Unknown), ethertype IPv6 (0x86dd), length 114: (hlim 255, next-header UDP (17) payload length: 60) fe80::e65f:1ff:fe20:240b.dhcpv6-client > ff02::1:2.dhcpv6-server: [udp sum ok] dhcp6 solicit (xid=8cdd56 (client-ID hwaddr type 1 e45f0120240b) (IA_NA IAID:0 T1:0 T2:0) (option-request opt_59) (opt_61) (elapsed-time 0))
----


DHCP服务器回复。

----
12:23:35.510478 dc:a6:32:6f:73:f4 (oui Unknown) > e4:5f:01:20:24:0b (oui Unknown), ethertype IPv6 (0x86dd), length 172: (flowlabel 0xad54d, hlim 64, next-header UDP (17) payload length: 118) fe80::537a:52c:c647:b184.dhcpv6-server > fe80::e65f:1ff:fe20:240b.dhcpv6-client: [bad udp cksum 0xd886 -> 0x6d26!] dhcp6 advertise (xid=8cdd56 (IA_NA IAID:0 T1:3600 T2:7200 (IA_ADDR fd49:869:6f93::1000 pltime:604800 vltime:2592000)) (client-ID hwaddr type 1 e45f0120240b) (server-ID hwaddr/time type 1 time 671211709 dca6326f73f4) (opt_59))
----

设备向DHCP服务器发送地址和TFTP详细信息请求。

----
12:23:35.510763 e4:5f:01:20:24:0b (oui Unknown) > 33:33:00:01:00:02 (oui Unknown), ethertype IPv6 (0x86dd), length 132: (hlim 255, next-header UDP (17) payload length: 78) fe80::e65f:1ff:fe20:240b.dhcpv6-client > ff02::1:2.dhcpv6-server: [udp sum ok] dhcp6 request (xid=8cdd56 (client-ID hwaddr type 1 e45f0120240b) (server-ID hwaddr/time type 1 time 671211709 dca6326f73f4) (IA_NA IAID:0 T1:0 T2:0) (option-request opt_59) (opt_61) (elapsed-time 1))
----

DHCP服务器回答， `opt_59` 用于传递TFTP服务器的地址。

----
12:23:35.512122 dc:a6:32:6f:73:f4 (oui Unknown) > e4:5f:01:20:24:0b (oui Unknown), ethertype IPv6 (0x86dd), length 172: (flowlabel 0xad54d, hlim 64, next-header UDP (17) payload length: 118) fe80::537a:52c:c647:b184.dhcpv6-server > fe80::e65f:1ff:fe20:240b.dhcpv6-client: [bad udp cksum 0xd886 -> 0x6826!] dhcp6 reply (xid=8cdd56 (IA_NA IAID:0 T1:3600 T2:7200 (IA_ADDR fd49:869:6f93::1000 pltime:604800 vltime:2592000)) (client-ID hwaddr type 1 e45f0120240b) (server-ID hwaddr/time type 1 time 671211709 dca6326f73f4) (opt_59))
----

设备向FTP服务器发送邻居请求，因为它需要其MAC地址。

----
12:23:36.510768 e4:5f:01:20:24:0b (oui Unknown) > 33:33:ff:00:00:01 (oui Unknown), ethertype IPv6 (0x86dd), length 86: (hlim 255, next-header ICMPv6 (58) payload length: 32) fe80::e65f:1ff:fe20:240b > ff02::1:ff00:1: [icmp6 sum ok] ICMP6, neighbor solicitation, length 32, who has fd49:869:6f93::1
          source link-address option (1), length 8 (1): e4:5f:01:20:24:0b
            0x0000:  e45f 0120 240b
----

FTP服务器使用其MAC地址进行回复。

----
12:23:36.510854 dc:a6:32:6f:73:f4 (oui Unknown) > e4:5f:01:20:24:0b (oui Unknown), ethertype IPv6 (0x86dd), length 86: (hlim 255, next-header ICMPv6 (58) payload length: 32) fd49:869:6f93::1 > fe80::e65f:1ff:fe20:240b: [icmp6 sum ok] ICMP6, neighbor advertisement, length 32, tgt is fd49:869:6f93::1, Flags [solicited, override]
          destination link-address option (2), length 8 (1): dc:a6:32:6f:73:f4
            0x0000:  dca6 326f 73f4
----

TFTP请求由现在应该通过网络启动的设备发出。

----
12:23:36.530820 e4:5f:01:20:24:0b (oui Unknown) > dc:a6:32:6f:73:f4 (oui Unknown), ethertype IPv6 (0x86dd), length 111: (hlim 255, next-header UDP (17) payload length: 57) fd49:869:6f93::1000.61785 > fd49:869:6f93::1.tftp: [udp sum ok]  49 RRQ "ab5a4158/start4.elf" octet tsize 0 blksize 1024
----

==== 无状态配置

下面是无状态（非 DHCP）网络配置的 tcp dump 摘要。

设备发送路由器请求。

----
12:55:27.541909 e4:5f:01:20:24:0b (oui Unknown) > 33:33:00:00:00:02 (oui Unknown), ethertype IPv6 (0x86dd), length 70: (hlim 255, next-header ICMPv6 (58) payload length: 16) fe80::e65f:1ff:fe20:240b > ip6-allrouters: [icmp6 sum ok] ICMP6, router solicitation, length 16
          source link-address option (1), length 8 (1): e4:5f:01:20:24:0b
            0x0000:  e45f 0120 240b
----

路由器回复网络详细信息。

----
12:55:27.834684 60:8d:26:a7:c1:88 (oui Unknown) > 33:33:00:00:00:01 (oui Unknown), ethertype IPv6 (0x86dd), length 174: (hlim 255, next-header ICMPv6 (58) payload length: 120) bthub.home > ip6-allnodes: [icmp6 sum ok] ICMP6, router advertisement, length 120
        hop limit 64, Flags [other stateful], pref medium, router lifetime 180s, reachable time 0ms, retrans timer 0ms
          prefix info option (3), length 32 (4): 2a00:23c5:ee00:5001::/64, Flags [onlink, auto, router], valid time 300s, pref. time 120s
            0x0000:  40e0 0000 012c 0000 0078 0000 0000 2a00
            0x0010:  23c5 ee00 5001 0000 0000 0000 0000
          prefix info option (3), length 32 (4): fd4d:869:6f93::/64, Flags [onlink, auto, router], valid time 10080s, pref. time 2880s
            0x0000:  40e0 0000 2760 0000 0b40 0000 0000 fd4d
            0x0010:  0869 6f93 0000 0000 0000 0000 0000
          rdnss option (25), length 24 (3):  lifetime 60s, addr: bthub.home
            0x0000:  0000 0000 003c fe80 0000 0000 0000 628d
            0x0010:  26ff fea7 c188
          mtu option (5), length 8 (1):  1492
            0x0000:  0000 0000 05d4
          source link-address option (1), length 8 (1): 60:8d:26:a7:c1:88
            0x0000:  608d 26a7 c188
----

设备向 DHCP 多播地址发送信息请求，询问 TFTP 详细信息。

----
12:55:27.838300 e4:5f:01:20:24:0b (oui Unknown) > 33:33:00:01:00:02 (oui Unknown), ethertype IPv6 (0x86dd), length 98: (hlim 255, next-header UDP (17) payload length: 44) fe80::e65f:1ff:fe20:240b.dhcpv6-client > ff02::1:2.dhcpv6-server: [udp sum ok] dhcp6 inf-req (xid=e5e0a4 (client-ID hwaddr type 1 e45f0120240b) (option-request opt_59) (opt_61) (elapsed-time 0))
----

DHCP 服务器回复 TFTP 服务器详细信息（ `opt_59` ）。

----
12:55:27.838898 dc:a6:32:6f:73:f4 (oui Unknown) > e4:5f:01:20:24:0b (oui Unknown), ethertype IPv6 (0x86dd), length 150: (flowlabel 0xd1248, hlim 64, next-header UDP (17) payload length: 96) fe80::537a:52c:c647:b184.dhcpv6-server > fe80::e65f:1ff:fe20:240b.dhcpv6-client: [bad udp cksum 0xd870 -> 0x78bb!] dhcp6 reply (xid=e5e0a4 (client-ID hwaddr type 1 e45f0120240b) (server-ID hwaddr/time type 1 time 671211709 dca6326f73f4) (opt_59))
----

设备询问 TFTP 服务器 MAC 地址，因为它可以判断它位于同一网络上。

----
12:55:28.834796 e4:5f:01:20:24:0b (oui Unknown) > 33:33:ff:1d:fe:2a (oui Unknown), ethertype IPv6 (0x86dd), length 86: (hlim 255, next-header ICMPv6 (58) payload length: 32) fe80::e65f:1ff:fe20:240b > ff02::1:ff1d:fe2a: [icmp6 sum ok] ICMP6, neighbor solicitation, length 32, who has 2a00:23c5:ee00:5001:57f1:7523:2f1d:fe2a
          source link-address option (1), length 8 (1): e4:5f:01:20:24:0b
            0x0000:  e45f 0120 240b
----

FTP 服务器以其 MAC 地址回复。

----
12:55:28.834875 dc:a6:32:6f:73:f4 (oui Unknown) > e4:5f:01:20:24:0b (oui Unknown), ethertype IPv6 (0x86dd), length 86: (hlim 255, next-header ICMPv6 (58) payload length: 32) 2a00:23c5:ee00:5001:57f1:7523:2f1d:fe2a > fe80::e65f:1ff:fe20:240b: [icmp6 sum ok] ICMP6, neighbor advertisement, length 32, tgt is 2a00:23c5:ee00:5001:57f1:7523:2f1d:fe2a, Flags [solicited, override]
          destination link-address option (2), length 8 (1): dc:a6:32:6f:73:f4
            0x0000:  dca6 326f 73f4
----

设备开始发出 TFTP 请求。

----
12:55:28.861097 e4:5f:01:20:24:0b (oui Unknown) > dc:a6:32:6f:73:f4 (oui Unknown), ethertype IPv6 (0x86dd), length 111: (hlim 255, next-header UDP (17) payload length: 57) 2a00:23c5:ee00:5001:e65f:1ff:fe20:240b.46930 > 2a00:23c5:ee00:5001:57f1:7523:2f1d:fe2a.tftp: [udp sum ok]  49 RRQ "ab5a4158/start4.elf" octet tsize 0 blksize 1024
----
