[[samba]]
== Samba (SMB/CIFS)

Samba 是 https://en.wikipedia.org/wiki/Server_Message_Block[服务器消息] (SMB) 网络协议的免费软件重新实现。使用 Samba，您可以在 Windows、macOS 和 Linux 计算机之间共享文件夹。

[[install-samba-on-your-raspberry-pi]]
=== 在您的 Raspberry Pi 上安装 Samba

默认情况下，Raspberry Pi OS 不包含 Samba。要在 Raspberry Pi 上安装 Samba，请运行以下命令，该命令将安装运行 Samba 服务器或客户端所需的所有依赖项：

[source,console]
----
$ sudo apt update
$ sudo apt install samba samba-common-bin smbclient cifs-utils
----

[[mount-a-folder-shared-from-windows]]
=== 安装从 Windows 共享的文件夹

首先，您需要在 Windows 设备上共享文件夹。

[[turn-on-sharing]]
==== 打开共享

. 右键单击系统托盘，从菜单中选择 *网络和共享中心*。
. 选择 *更改高级共享设置*。
. 选择 *打开网络发现*。
. 选择 *打开文件和打印机共享*。
. 单击 *保存* 按钮保存更改。

[[share-the-folder]]
==== 共享文件夹

按照以下步骤从 Windows 共享文件夹：

. 右键单击要共享的文件夹，然后选择 *属性*。
. 选择 *共享* 选项卡。
. 单击 *高级共享* 按钮。
. 选择 *共享此文件夹*；默认情况下，Windows 使用文件夹名称作为共享名称。
. 单击 *权限* 按钮。
. 配置 *Everyone* 和 *Full Control* 权限。
. 单击 *OK* 按钮离开 *Permissions* 页面。
. 再次单击 *OK* 按钮离开 *Advanced Sharing* （高级共享）页面。
. 选择 *安全性* 选项卡。
. 配置 *Everyone* 和 *Full Control* 权限。
. 单击 *OK* 按钮。

现在应该可以共享文件夹了。您可以通过在 `权限` 和 `安全` 页面上更改权限来修改共享文件夹权限。

[[windows-10-sharing-wizard]]
==== Windows 10 共享向导

Windows 10 上有一个共享向导，可帮助您完成其中一些步骤。

. 从 "开始 "栏运行 "计算机管理 "* 应用程序。
. 选择 *共享文件夹* > *共享*。
. 右键单击并选择 *New Share* 开始共享向导。
. 单击 *下一步* 按钮。
. 选择要共享的文件夹，然后单击 *下一步* 按钮。
. 单击 *下一步* 使用共享默认值，或选择 *自定义* 并设置所需的权限。
. 单击 *OK* 按钮。
. 单击 *Finish* 按钮共享文件夹。

[[mount-the-folder-on-the-raspberry-pi]]
==== 在 Raspberry Pi 上安装文件夹

Linux 中的 `安装` 是将文件夹附加到某个位置的过程，因此首先我们需要该位置。

[source,console]
----
$ mkdir windowshare
----

现在，我们需要将远程文件夹安装到该位置。远程文件夹是 Windows PC 的主机名或 IP 地址，以及共享时使用的共享名。我们还需要提供用于访问远程计算机的 Windows 用户名。不要忘记用您的 Raspberry Pi OS 用户名替换 `<username>` 占位符。

[source,console]
----
$ sudo mount.cifs //<hostname or IP address>/<shared windows folder> /home/<username>/windowshare -o user=<name>
----

您现在应该能够在 Raspberry Pi 上查看 Windows 共享的内容。

[source,console]
----
$ ls windowshare/
----

[[host-is-down-error]]
==== "主机已关闭"错误

当 SMB 协议版本不匹配且 Linux Samba 客户端返回误导性错误消息时，会发生此错误。默认情况下，Raspberry Pi OS 使用 2.1 及以上版本，与 Windows 7 及更高版本兼容。较旧的设备（包括某些 NAS）可能需要 1.0 版本。要修复此错误，请在挂载命令后附加一个版本条目（例如 `,vers=1.0` ）：

[source,console]
----
$ sudo mount.cifs //IP/share /mnt/point -o user=<uname>,vers=1.0
----

您可能需要尝试不同的版本以与服务器版本匹配。可能的值包括：

|===
| 版本 | 说明

| 1.0
| 经典 CIFS/SMBv1 协议

| 2.0
| SMBv2.002 协议。Windows Vista Service Pack 1 和 Windows Server 2008

| 2.1
| SMBv2.1 协议。Microsoft Windows 7 和 Windows Server 2008R2

| 3.0
| SMBv3.0 协议。 Microsoft Windows 8 和 Windows Server 2012

| 3.02
| SMBv3.0.2 协议。Microsoft Windows 8.1 和 Windows Server 2012R2

| 3.11
| SMBv3.1.1 协议。Microsoft Windows 10 和 Windows Server 2016

| 3
| SMBv3.0 协议版本及以上
|===

[[sharing-a-folder-from-your-raspberry-pi]]
=== 从 Raspberry Pi 共享文件夹

首先，创建一个要共享的文件夹。此示例在当前用户的 `home` 文件夹中创建一个名为 `shared` 的文件夹：

[source,console]
----
$ cd ~
$ mkdir shared
$ chmod 0740 shared
----

现在，我们需要告诉 Samba 在访问该文件夹时你的默认用户账户。出现提示时，请输入您的密码，并用您的主用户账户的用户名替换"<username>"占位符：

[source,console]
----
$ sudo smbpasswd -a <username>
----

现在我们需要使用Samba配置文件告诉Samba共享这个文件夹。

[,bash]
----
sudo nano /etc/samba/smb.conf
----

在文件末尾，添加以下内容以共享文件夹，授予远程用户读/写权限。将 `<username>` 占位符替换为Raspberry Pi上主要用户帐户的用户名：

----
[share]
    path = /home/<username>/shared
    read only = no
    public = yes
    writable = yes
----

在同一文件中，找到 `workgroup` 行，如有必要，将其更改为本地Windows网络的工作组名称。

[,bash]
----
workgroup = <your workgroup name here>
----

共享文件夹现在应该出现在网络上的Windows或macOS设备上。输入您的Raspberry Pi用户名和密码以挂载文件夹。
