== Software Utilities

=== What is on your Pico-series device?

如果您不确定 Raspberry Pi Pico 系列设备中的编程内容，并且程序是使用 Pico C/{cpp} SDK 构建的，那么它通常会在二进制文件中嵌入名称和有用信息。SDK构建的程序，它通常会在二进制文件中嵌入名称和其他有用信息。您可以使用 https://github.com/raspberrypi/picotool[Picotool] 命令行实用程序查找这些详细信息。我们的 “https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[入门] 文档中提供了有关如何使用 Picotool 的完整说明。

* 访问 https://github.com/raspberrypi/picotool[Picotool Github repository].

=== Debugging using another Pico-series device

您可以使用一个Pico系列设备来调试另一个Pico系列设备。这可以通过 `debugprobe` 实现，XXX2 是一个允许Pico充当USB→SWD和通用异步收发设备转换器的应用程序。

您可以在 https://github.com/raspberrypi/debugprobe/releases/latest[the debugprobe GitHub repository] 中找到固件的最新版本。

从最新版本下载 `debugprobe_on_pico.uf2`（Pico）或 `debugprobe_on_pico2.uf2`（Pico2）。

将调试器设备插入计算机以挂载名为“RPI-RP2”的卷时，按住BOOTSEL按钮。

将UF2文件复制到卷上。文件完成复制到设备后，卷将自动卸载。

您的设备将重新启动，现在运行更新版本的 `debugprobe` 固件。它现在可以调试了。

TIP: 有关如何使用调试器的说明，请参阅 https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[Pico 系列微控制器入门指南]。

=== Resetting Flash memory

对于Pico系列设备，BOOTSEL模式存在于RP2040或RP2350芯片内的只读存储器中，不会被意外覆盖。无论如何，如果您在插入Pico时按住BOOTSEL按钮，它将显示为一个驱动器，您可以将新的UF2文件拖到该驱动器上。没有办法通过软件砖块电路板。但是，在某些情况下，您可能希望确保闪存为空。当Pico处于大容量存储模式时，您可以通过将特殊的UF2二进制文件拖放到Pico上来做到这一点。

* 现在 https://datasheets.raspberrypi.com/soft/flash_nuke.uf2[UF2 file]
* 查看 https://github.com/raspberrypi/pico-examples/blob/master/flash/nuke/nuke.c[Github] 上的代码
