[[compute-moduleeeprom-bootloader]]
== 计算模块 EEPROM 引导加载程序

从计算模块 4 开始，计算模块使用 EEPROM 引导加载程序。该引导加载程序位于板载存储的一小部分中，而不是引导分区中。因此，更新它需要不同的程序。在生产中使用带有 EEPROM 引导加载程序的计算模块之前，请务必遵循以下最佳实践：

* 选择特定的引导加载程序版本。确认使用的每个计算模块都有该版本。`usbboot` repo 中的版本始终是最近的稳定版本。
* 通过 xref:raspberry-pi.adoc#raspberry-pi-bootloader-configuration[设置 `BOOT_ORDER`] 配置引导设备。
* 在引导加载器 EEPROM 上启用硬件写保护，以确保引导加载器无法在无法访问的产品（如远程或嵌入式设备）上被修改。

=== Flash计算模块引导加载程序 EEPROM

Flash引导加载程序 EEPROM：

. 与 xref:../computers/compute-module.adoc#flash-compute-module-emmc[flashing the eMMC] 时一样设置硬件，但要确保 `EEPROM_nWP` _不_ 被拉低。
. 运行以下命令将 `recovery/pieeprom.bin` 写入引导加载程序 EEPROM：
+
[source,console]
----
$ ./rpiboot -d recovery
----
. 完成后，`EEPROM_nWP` 可以再次被拉低。

=== SD 卡以外的闪存设备

基于 Linux 的 https://github.com/raspberrypi/usbboot/blob/master/mass-storage-gadget/README.md[`mass-storage-gadget`] 支持闪存 NVMe、eMMC 和 USB 块设备。与基于固件的 `rpiboot` 机制相比，`mass-storage-gadget` 写入设备的速度更快，还为设备提供了一个 UART 控制台用于调试。

`usbboot` 还包括一些 https://github.com/raspberrypi/usbboot/blob/master/Readme.md#compute-module-4-extensions[扩展]，可让您与计算模块上的 EEPROM 引导加载程序进行交互。

=== 更新计算模块引导加载程序

在使用 EEPROM 引导加载程序的计算模块上，ROM 从未从 SD/eMMC 运行过 `recovery.bin`。这些计算模块默认禁用 `rpi-eeprom-update` 服务，因为 eMMC 不可拆卸，无效的  `recovery.bin` 文件可能会阻止系统启动。

你可以用 "自我更新 "模式覆盖这一行为。在 "自我更新 "模式下，可以通过 USB MSD 或网络启动更新引导加载程序。

WARNING: `self-update` 模式不会雾化更新引导加载程序。如果在更新 EEPROM 时发生断电，可能会损坏 EEPROM。

=== 修改引导加载程序配置

修改计算模块 EEPROM 引导加载程序配置：

. 导航至 `usbboot/recovery` 目录。
. 如果需要特定的引导加载程序版本，请将 `pieeprom.original.bin` 替换为引导加载程序版本中的相应内容。
. 编辑默认的 `boot.conf` 引导加载器配置文件以定义 xref:../computers/raspberry-pi.adoc#BOOT_ORDER[`BOOT_ORDER`]：
 * 对于网络启动，使用 `BOOT_ORDER=0xf2`。
 * 对于 SD/eMMC 启动，使用 `BOOT_ORDER=0xf1`。
 * 对于 USB 启动失败转到 eMMC，使用 `BOOT_ORDER=0xf15`。
 * 对于 NVMe 启动，使用 `BOOT_ORDER=0xf6`。
. 运行 `./update-pieeprom.sh`，生成新的 EEPROM 映像文件 `pieeprom.bin` 映像文件。
. 如果需要 EEPROM 写保护，请在 `/boot/firmware/config.txt` 中添加 `eeprom_write_protect=1`。
 * 软件启用后，可以通过将 `EEPROM_nWP` 引脚拉低来锁定硬件写保护。
. 运行以下命令将更新后的 `pieeprom.bin` 映像写入 EEPROM：
+
[source,console]
----
$ ../rpiboot -d .
----
