[[flash-compute-module-emmc]]
== 将图像烧录到计算模块

[[flashing-the-compute-module-emmc]]

计算模块有一个连接到主 SD 卡接口的板载 eMMC 设备。本指南介绍如何将操作系统映像闪存（写入）到单个计算模块的 eMMC 存储器中。

NOTE: **Lite** 版本的计算模块没有板载 eMMC。相反，您可以按照 xref:../computers/getting-started.adoc#installing-the-operating-system[Install an operating system] 中为其他 Raspberry Pi 设备烧录存储设备的步骤进行操作。

将映像烧录到多个计算模块时，请考虑使用计算模块供应程序：

[.whitepaper, title="使用Compute Module Provisioner进行大规模烧录", subtitle="", link=https://pip.raspberrypi.com/categories/685-whitepapers-app-notes/documents/RP-003468-WP/Using-the-Compute-Module-Provisioner.pdf]
****
Compute Module Provisioner 是一款网络应用程序，可帮助开发人员同时对多个 Compute Module 设备进行编程。

除了自动标签打印和固件更新外，它还提供内核映像数据库，并能在闪存过程中运行脚本。
****

=== 前提条件

要闪存计算模块 eMMC，您需要具备以下条件：

* 另一台计算机，在本指南中称为 *主机设备*。您可以使用 Linux（Raspberry Pi OS 或 Ubuntu）、Windows 或 macOS。
* Compute Module IO 板 xref:compute-module.adoc#io-board-compatibility[与您的 Compute Module 型号相对应]。
* 微型 USB 电缆。

=== 安装 IO 板

首先，物理安装 IO 板。这包括将计算模块和主机设备连接到 IO 板。

==== Compute Module 4 IO 板

设置计算模块 4 IO 板：

. 将计算模块连接到 IO 板。连接后，计算模块应平放。

. 将 "nRPI_BOOT "安装到 IO 板跳线 J2（"禁用 eMMC 启动"）上。

. 将电缆从 IO 板上的微型 USB 从端口 J11 连接到主机设备。

==== Compute Module IO 板

设置计算模块 IO 板：

. 将计算模块连接到 IO 板。连接时，计算模块应平行于电路板，啮合夹应卡紧到位。

. 将 J4（"USB SLAVE BOOT ENABLE"）设为 1-2 =（"USB BOOT ENABLED"）。

. 将电缆从 IO 板上的微型 USB 从端口 J15 连接到主机设备。

=== 设置主机设备

接下来，让我们在主机设备上设置软件。

==== Linux

在 Linux 主机设备上设置软件：

. 运行以下命令安装 `rpiboot`：
+
[source,console]
----
$ sudo apt install rpiboot
----

. 连接 IO 板电源。

. 然后运行 `rpiboot`：
+
[source,console]
----
$ sudo rpiboot
----

. 几秒钟后，计算模块应显示为一个大容量存储设备。检查 `/dev/` 目录，可能是 `/dev/sda` 或 `/dev/sdb`。或者，运行 `lsblk` 查找存储容量与计算模块容量相匹配的设备。

TIP: 或者，您也可以 https://github.com/raspberrypi/usbboot[从源代码构建 `rpiboot`]。

==== macOS

在 macOS 主机设备上设置软件：

. 首先，https://github.com/raspberrypi/usbboot?tab=readme-ov-file#macos[从源代码构建`rpiboot`]。

. 连接 IO 板电源。

. 然后，使用以下命令运行 `rpiboot` 可执行文件：
+
[source,console]
----
$ sudo ./rpiboot
----

. 命令运行完成后，你会看到一条信息，提示 "你插入的磁盘本计算机无法读取"。单击**忽略**。现在，您的计算模块应显示为大容量存储设备。

==== Windows

在 Windows 主机设备上设置软件：

. 下载 https://github.com/raspberrypi/usbboot/raw/master/win32/rpiboot_setup.exe[Windows 安装程序］

. 双击安装程序运行。这将安装驱动程序和启动工具。

. 连接 IO 板电源。Windows 将发现硬件并配置所需的驱动程序。

. 双击 `RPiBoot.exe` 运行。几秒钟后，计算模块 eMMC 应显示为 USB 大容量存储设备。

TIP: 或者，您也可以 https://github.com/raspberrypi/usbboot[从源代码构建 `rpiboot`]。

=== Flash the eMMC

您可以使用 xref:../computers/getting-started.adoc#raspberry-pi-imager[Raspberry Pi Imager] 将操作系统映像烧录到计算模块。

或者，使用 `dd` 将原始操作系统映像 xref:../computers/getting-started.adoc#raspberry-pi-imager[Raspberry Pi Imager] 写入计算模块。运行以下命令，将 `/dev/sdX` 替换为计算模块的大容量存储设备表示路径，将 `raw_os_image.img` 替换为原始操作系统映像的路径：

[source,console]
----
$ sudo dd if=raw_os_image.img of=/dev/sdX bs=4MiB
----

写入映像后，断开并重新连接计算模块。现在你应该能看到两个分区（Raspberry Pi OS）：

[source,console]
----
/dev/sdX    <- Device
/dev/sdX1   <- First partition (FAT)
/dev/sdX2   <- Second partition (Linux filesystem)
----

您可以正常挂载 `/dev/sdX1` 和 `/dev/sdX2` 分区。

=== 从 eMMC 启动

==== Compute Module 4 IO 板

断开 IO 板跳线 J2（`禁用 eMMC 启动`）上的 `nRPI_BOOT`。

==== Compute Module IO 板

将 J4（`USB SLAVE BOOT ENABLE`）设置为 2-3（`USB BOOT DISABLED`）。

==== Boot

断开 USB 从端口。关闭 IO 板电源，从刚写入 eMMC 的新映像启动计算模块。

=== 已知问题

* 一小部分 CM3 出现了启动问题。我们已将这些问题追溯到创建 FAT32 分区的方法；我们认为问题是由于 CPU 和 eMMC 之间的时间差造成的。如果在启动 CM3 时遇到问题，请使用以下命令手动创建分区：
+
[source,console]
----
$ sudo parted /dev/<device>
(parted) mkpart primary fat32 4MiB 64MiB
(parted) q
$ sudo mkfs.vfat -F32 /dev/<device>
$ sudo cp -r <files>/* <mountpoint>
----

* CM1 引导加载程序会向主机返回一个略微不正确的 USB 数据包。大多数 USB 主机会忽略它，但有些 USB 端口会因为这个错误而无法工作。CM3 修正了这一错误。
