== 连接外设

本指南可帮助开发人员将外设连接到计算模块引脚，并说明如何在软件中启用这些外设。

SoC 的大部分引脚，包括 GPIO、两个 CSI 摄像头接口、两个 DSI 显示器接口和 HDMI 都可用于布线。您通常可以将未使用的引脚断开。

采用 DDR2 SODIMM 外形的计算模块与任何 DDR2 SODIMM 插座物理兼容。不过，引脚布局与 SODIMM 内存模块并 **不** 相同。

要使用计算模块，用户设计的主板必须具备以下条件

* 为计算模块供电（至少 3.3V 和 1.8V）
* 为用户应用所需的外设连接引脚

本指南首先介绍启动过程以及设备树如何描述所连接的硬件。

然后，我们将介绍如何将 I2C 和 SPI 外围设备连接到 IO 板。最后，我们将创建必要的设备树文件，以便在 Raspberry Pi OS 中使用这两个外设。

=== BCM283x GPIOs

BCM283x 有三组通用输入/输出 (GPIO) 引脚： 0 组有 28 个引脚，1 组有 18 个引脚，2 组有 8 个引脚，共计 54 个引脚。这些引脚可用作真正的 GPIO 引脚：软件可将其设置为输入或输出、读取和/或设置状态，并将其用作中断。它们还可以运行 I2C、SPI、I2S、UART、SD 卡等其他功能。

您可以在任何计算模块上使用组 0 或组 1。不要使用组 2：它控制 eMMC、HDMI 热插拔检测和 ACT LED/USB 启动控制。

使用 `pinctrl` 检查 GPIO 引脚的电压和功能，查看设备树是否按预期工作。

=== BCM283x 启动过程

BCM283x 设备具有 VideoCore GPU 和 Arm CPU 内核。GPU 由 DSP 处理器和用于成像、视频编解码、3D 图形和图像合成的硬件加速器组成。

在 BCM283x 设备中，GPU 中的 DSP 内核首先启动。它在启动主 Arm 处理器之前处理设置。

Raspberry Pi BCM283x 设备的启动过程分为三个阶段：

* GPU DSP 复位后执行小型内部启动 ROM 中的代码。该代码通过外部接口加载第二阶段启动加载程序。该代码首先在引导分区上名为 `bootcode.bin` 的引导设备上寻找第二阶段引导加载器。如果没有找到引导设备或找不到 `bootcode.bin`，引导 ROM 将在 USB 启动模式下等待主机提供第二阶段引导加载器（`usbbootcode.bin`）。
* 第二阶段引导加载器负责设置 LPDDR2 SDRAM 接口和其他关键系统功能。设置完成后，第二阶段启动加载器将加载并执行主 GPU 固件（`start.elf`）。
* `start.elf` 处理额外的系统设置并启动 Arm 处理器子系统。它包含 GPU 固件。GPU 固件首先会读取 `dt-blob.bin`，以确定 GPIO 引脚的初始状态以及 GPU 专用接口和时钟，然后解析 `config.txt`。然后，在启动 Arm 子系统并将设备树数据传递给启动的 Linux 内核之前，加载特定于模型的 Arm 设备树文件和 `config.txt` 中指定的任何设备树overlay。

=== 设备树

xref:configuration.adoc#device-trees-overlays-and-parameters[适用于 Raspberry Pi 的 Linux 设备树]对连接到系统的硬件信息以及用于与该硬件通信的驱动程序进行编码。

启动分区包含多个二进制设备树（`.dtb`）文件。设备树编译器使用人类可读的设备树描述 (`.dts`)创建这些二进制文件。

启动分区包含两种不同类型的设备树文件。其中一个仅供 GPU 使用；其余的是标准的 Arm 设备树文件，适用于基于 BCM283x 的每种 Raspberry Pi 产品：

* `dt-blob.bin`（GPU 使用）
* `bcm2708-rpi-b.dtb` （用于 Raspberry Pi 1 型号 A 和 B）
* `bcm2708-rpi-b-plus.dtb` （用于 Raspberry Pi 1 型号 B+ 和 A+）
* `bcm2709-rpi-2-b.dtb` （用于 Raspberry Pi 2 型号 B）
* `bcm2710-rpi-3-b.dtb` （用于 Raspberry Pi 3 Model B）
* `bcm2708-rpi-cm.dtb` （用于 Raspberry Pi 计算模块 1）
* `bcm2710-rpi-cm3.dtb` （用于 Raspberry Pi 计算模块 3）

在启动过程中，用户可以通过 `config.txt` 中的 `device_tree` 参数指定要使用的特定 Arm 设备树。例如，`config.txt` 中的 `device_tree=mydt.dtb` 行指定了名为 `mydt.dtb` 文件中的Arm设备树。

您可以为计算模块产品创建完整的 `设备树`，但我们建议您使用 **overlay**。覆盖层将非特定于板卡的硬件描述添加到基本设备树中。这包括使用的 GPIO 引脚及其功能，以及所连接的设备，以便加载正确的驱动程序。在将设备树传递给 Linux 内核之前，引导加载程序会将覆盖与基本设备树合并。基础设备树偶尔会发生变化，但通常不会破坏覆盖层。

使用 `config.txt` 中的 `dtoverlay` 参数加载设备树覆盖。Raspberry Pi OS 假定所有覆盖都位于 `/overlays` 目录中，并使用后缀 `-overlay.dtb`。例如，"dtoverlay=myoverlay "一行将加载覆盖图"/overlays/myoverlay-overlay.dtb"。

要将外设连接到计算模块，请在覆盖层中描述连接到 Bank 0 和 Bank 1 GPIO 的所有硬件。这样，您就可以使用标准的 Raspberry Pi OS 映像，因为覆盖层已被合并到标准的基本设备树中。或者，您也可以为自己的应用程序定义一个自定义的 "设备树"（Device Tree），但这样就无法使用标准的 Raspberry Pi OS 映像。取而代之的是，您必须创建一个修改过的 Raspberry Pi OS 镜像，其中包含您希望发布的每个操作系统更新的自定义设备树。如果基础覆盖层发生变化，你可能需要更新你定制的设备树。

=== `dt-blob.bin`

当 `start.elf` 运行时，它会首先读取 `dt-blob.bin`。这是一种特殊形式的设备树 blob，它告诉 GPU 如何设置 GPIO 引脚状态。

`dt-blob.bin` 包含 GPU（而非 SoC）控制的 GPIO 和外设信息。例如，GPU 管理摄像头模块。GPU 需要独占一个 I2C 接口和几个引脚，才能与摄像头模块通信。

在大多数 Raspberry Pi 型号上，I2C0 被保留给 GPU 专用。`dt-blob.bin` 定义了用于 I2C0 的 GPIO 引脚。

默认情况下，`dt-blob.bin` 不存在。相反，`start.elf` 包含了该文件的内置版本。许多计算模块项目会提供一个自定义的 `dt-blob.bin`，该文件会覆盖默认的内置文件。

`dt-blob.bin` 指定：

* 用于 HDMI 热插拔检测的引脚
* 用作 GPCLK 输出的 GPIO 引脚
* 启动时 GPU 可以使用的 ACT LED

https://datasheets.raspberrypi.com/cm/minimal-cm-dt-blob.dts[`minimal-cm-dt-blob.dts`]是一个`.dts`设备树文件示例。它设置了 HDMI 热插拔检测和 ACT LED，并将所有其他 GPIO 设置为默认输入。

要将 `minimal-cm-dt-blob.dts` 编译为 `dt-blob.bin`，请使用 xref:configuration.adoc#device-trees-overlays-and-parameters[设备树编译器] `dtc`。
要在 Raspberry Pi 上安装 `dtc`，请运行以下命令：

[source,console]
----
$ sudo apt install device-tree-compiler
----

然后，运行以下命令将 `minimal-cm-dt-blob.dts` 编译成 `dt-blob.bin`：

[source,console]
----
$ dtc -I dts -O dtb -o dt-blob.bin minimal-cm-dt-blob.dts
----

有关详细信息，请参阅我们的 xref:configuration.adoc#change-the-default-pin-configuration[创建 `dt-blob.bin` 指南]。

=== Arm Linux 设备树

在`start.elf`读取`dt-blob.bin`并设置初始引脚状态和时钟后，它会读取 xref:config_txt.adoc[`config.txt`]，其中包含许多其他系统设置选项。

读取 `config.txt` 之后，`start.elf` 会读取特定型号的设备树文件。例如，计算模块 3 使用 `bcm2710-rpi-cm.dtb`。该文件是一个标准的 Arm Linux 设备树文件，详细说明了处理器上连接的硬件。它列举了

* 有哪些外围设备以及存在于何处
* 使用了哪些 GPIO
* 这些 GPIO 具有哪些功能
* 连接了哪些物理设备

如果 GPIO 的引脚状态与 `dt-blob.bin` 中的不同，该文件会通过覆盖引脚状态来设置 GPIO。它还会尝试加载特定设备的驱动程序。

特定型号的设备树文件包含禁用的外设条目。它不包含 GPIO 引脚定义，但 eMMC/SD 卡外设具有 GPIO 定义并始终使用相同的引脚。

=== 设备树源代码和编译

当您构建自己的内核时,构建主机需要在 `scripts/dtc` 中使用设备树编译器。为了自动构建您的设备树重叠层,请将它们添加到 `arch/arm/boot/dts/overlays/Makefile` 中的 `dtbs` make 目标中。

Raspberry Pi OS 映像提供编译后的 `dtb` 文件，但源代码 `dts` 文件位于 https://github.com/raspberrypi/linux/tree/rpi-6.6.y/arch/arm/boot/dts/broadcom[Raspberry Pi Linux 内核分支]。在文件名中查找 `rpi`。

默认的覆盖`dts`文件位于 https://github.com/raspberrypi/linux/tree/rpi-6.6.y/arch/arm/boot/dts/overlays[`arch/arm/boot/dts/overlays`]。这些覆盖文件是创建自己的覆盖文件的良好起点。要将这些 `dts` 文件编译成 `dtb` 文件，请使用 xref:configuration.adoc#device-trees-overlays-and-parameters[设备树编译器] `dtc`。

构建自己的内核时，构建主机需要使用 `scripts/dtc` 中的设备树编译器。要自动编译覆盖层，请将其添加到 `arch/arm/boot/dts/overlays/Makefile` 中的 `dtbs` 。



=== 设备树调试

启动 Linux 内核时，GPU 会提供使用基本 `dts` 和任何覆盖创建的完整组装设备树。这个完整的设备树可以通过 Linux `proc` 界面的 `/proc/device-tree`获得。节点变成目录，属性变成文件。

你可以使用 `dtc` 将其写成人类可读的 `dts` 文件，以便调试。要查看完整的设备树，请运行以下命令：

[source,console]
----
$ dtc -I fs -O dts -o proc-dt.dts /proc/device-tree
----

`pinctrl` 提供 GPIO 引脚的状态。如果似乎出了什么问题，请尝试转储 GPU 日志信息：

[source,console]
----
$ sudo vclog --msg
----

TIP: 要在输出中包含更多诊断信息，请在 `config.txt` 中添加 `dtdebug=1`。

使用 https://forums.raspberrypi.com/viewforum.php?f=107[Device Tree Raspberry Pi 论坛] 询问与 Device Tree 相关的问题或报告问题。

=== 示例

以下示例使用的是通过跳线连接外设的 IO 板。我们假定使用 CM1+CMIO 或 CM3+CMIO3，运行已安装的 Raspberry Pi OS Lite。这里的示例需要互联网连接，因此我们建议将 USB 集线器、键盘和无线局域网或以太网加密狗插入 IO 板 USB 端口。

==== 将 I2C RTC 连接到第 1 组引脚

在本例中，我们将把 NXP PCF8523 实时时钟 (RTC) 连接到 IO 板第 1 组 GPIO 引脚： 3V3、GND、GPIO44 上的 I2C1_SDA 和 GPIO45 上的 I2C1_SCL。

下载 https://datasheets.raspberrypi.com/cm/minimal-cm-dt-blob.dts[`minimal-cm-dt-blob.dts`]，并将其复制到 `/boot/firmware/` 中的启动分区。

编辑 `minimal-cm-dt-blob.dts`，将 GPIO44 和 45 的引脚状态改为带上拉的 I2C1：

[source,console]
----
$ sudo nano /boot/firmware/minimal-cm-dt-blob.dts
----

替换以下几行：

[source,kotlin]
----
pin@p44 { function = "input"; termination = "pull_down"; }; // DEFAULT STATE WAS INPUT NO PULL
pin@p45 { function = "input"; termination = "pull_down"; }; // DEFAULT STATE WAS INPUT NO PULL
----

上拉定义如下

[source,kotlin]
----
pin@p44 { function = "i2c1"; termination = "pull_up"; }; // SDA1
pin@p45 { function = "i2c1"; termination = "pull_up"; }; // SCL1
----

我们可以使用 `dt-blob.dts` 而不做任何更改，因为 Linux 设备树会在 Linux 内核启动期间加载特定驱动程序时重新配置这些引脚。但是，如果配置了 `dt-blob.dts`，GPIO 就会在 GPU 启动阶段尽快达到最终状态。在某些情况下，必须在 GPU 启动时配置引脚，以便它们在 Linux 驱动程序加载时处于特定状态。例如，复位线可能需要保持正确的方向。

运行以下命令编译 `dt-blob.bin`：

[source,console]
----
$ sudo dtc -I dts -O dtb -o /boot/firmware/dt-blob.bin /boot/firmware/minimal-cm-dt-blob.dts
----

下载 https://datasheets.raspberrypi.com/cm/example1-overlay.dts[`example1-overlay.dts`]，将其复制到 `/boot/firmware/` 中的启动分区，然后用以下命令编译：

[source,console]
----
$ sudo dtc -@ -I dts -O dtb -o /boot/firmware/overlays/example1.dtbo /boot/firmware/example1-overlay.dts
----

`-@` 标记用于编译带有外部引用的 `dts` 文件。这通常是必要的。

在 xref:../computers/config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`] 中添加以下一行：

[source,ini]
----
dtoverlay=example1
----

最后，使用 `sudo reboot` 重启。

重启后，你应该会在 `/dev`中看到一个 `rtc0` 条目。运行以下命令查看硬件时钟时间：

[source,console]
----
$ sudo hwclock
----

==== 在组 0 上添加 ENC28J60 SPI 以太网控制器

在本示例中，我们使用已在 `/boot/firmware/overlays`中定义的覆盖层，将ENC28J60 SPI 以太网控制器添加到第 0 行。以太网控制器使用 SPI 引脚 CE0、MISO、MOSI 和 SCLK（分别为 GPIO8-11），GPIO25 用于下降沿中断，此外还有 GND 和 3.3V。

在本例中，我们不会更改 `dt-blob.bin`。相反，在 `/boot/firmware/config.txt`中添加以下一行：

[source,ini]
----
dtoverlay=enc28j60
----

使用 `sudo reboot` 重新启动。

现在你应该能在 `/dev`中看到一个 `rtc0` 条目。运行以下命令查看硬件时钟时间：

[source,console]
----
$ sudo hwclock
----

您还应该有以太网连接。运行以下命令测试连接性：

[source,console]
----
$ ping 8.8.8.8
----

运行以下命令显示 GPIO 功能；GPIO8-11 现在应提供 ALT0（SPI）功能：

[source,console]
----
$ pinctrl
----

