[[common-options]]
== 常用选项

[[common-display-options]]
=== 常用显示选项

[[hdmi_enable_4kp60-raspberry-pi-4-only]]
==== `hdmi_enable_4kp60` （仅限树莓派4）

默认情况下，当连接到 4K 显示器时，Raspberry Pi 4B、400 和 CM4 将选择 30Hz 刷新率。使用该选项可选择 60Hz 刷新率。Raspberry Pi 4 不支持同时通过两个微型 HDMI 端口输出 4Kp60。设置 `hdmi_enable_4kp60`会增加功耗和温度。


IMPORTANT: 无法在Raspberry Pi 4的两个micro HDMI端口上同时输出4Kp60。

WARNING: 设置 `hdmi_enable_4kp60` 会增加功耗和树莓派的温度。

[[common-hardware-configuration-options]]
=== 常用硬件配置选项

[[camera_auto_detect]]
==== `camera_auto_detect` 

启用此设置后（在Raspberry Pi OS中默认启用），固件将自动加载它识别的CSI相机的overlays。设置 `camera_auto_detect=0` 以禁用该设置。

[[display_auto_detect]]
==== `display_auto_detect` 

启用此设置后（在Raspberry Pi OS中默认启用），固件将自动加载它识别的DSI显示器的overlay。设置 `display_auto_detect=0` 以禁用。

[[dtoverlay]]
==== `dtoverlay` 

dtoverlay选项请求固件加载一个命名的设备树overlay — 一个可以启用内核对内置和外部硬件支持的配置文件。例如， `dtoverlay=vc4-kms-v3d` 加载一个启用内核图形驱动程序的设备树文件。

作为一种特殊情况，如果不带值调用 - `dtoverlay=` - 该选项将标记覆盖参数列表的结束。如果在任何其他 `dtoverlay` 或 `dtparam` 设置之前使用，它会阻止加载任何HAT overlay。

有关更多详细信息，请参阅 xref:configuration.adoc#part3.1[DTBs, overlays and config.txt]。

[[dtparam]]
==== `dtparam` 

Raspberry Pis的设备树配置文件支持许多参数，例如启用I2C和SPI接口。许多DT overlay可以通过使用参数进行配置。这两种类型的参数都可以使用 `dtparam` 设置提供。此外，overlay参数可以附加到 `dtoverlay` 选项中，用逗号分隔，但请记住行长限制为98个字符。

有关更多详细信息，请参阅 xref:configuration.adoc#part3.1[DTBs, overlays and config.txt]。

[[arm_boost-raspberry-pi-4-only]]
==== `arm_boost` （仅限树莓派4）

所有树莓派400和树莓派4B的更新版本都配备了用于SoC电压轨的第二个开关模式电源，这允许默认涡轮模式时钟从1.5GHz增加到1.8GHz。此更改在树莓派操作系统中默认启用。设置 `arm_boost=0` 以禁用。

[[power_force_3v3_pwm-raspberry-pi-5-only]]
==== `power_force_3v3_pwm` （仅限树莓派5）

使用3V3电源时强制PWM。设置 `power_force_3v3_pwm=0` 以禁用。
