[[what-is-config-txt]]
== 什么是 `config.txt` ？

Raspberry Pi 设备使用名为 `config.txt` 的配置文件，而不是传统 PC 上的 https://en.wikipedia.org/wiki/BIOS[BIOS]。在 Arm CPU 和 Linux 初始化之前，GPU 会读取 `config.txt`。Raspberry Pi OS 会在 *boot 分区*（位于 `/boot/firmware/`）中查找该文件。

注意：在 Raspberry Pi OS _Bookworm_ 之前，Raspberry Pi OS 将启动分区存储在 `/boot/`。

您可以直接从 Raspberry Pi OS 安装中编辑 `config.txt`。也可以移除存储设备，在另一台电脑上编辑启动分区中的文件，包括 `config.txt`。

对 `config.txt` 的更改仅在重启后生效。您可以使用以下命令查看当前活动设置：

`vcgencmd get_config <config>`:: 显示特定配置值，例如 `vcgencmd get_config arm_freq`.
`vcgencmd get_config int`:: 列出所有非零整数配置选项（非零）
`vcgencmd get_config str`:: 列出所有非空字符串配置选项

NOTE: 并非所有配置设置都能使用 `vcgencmd` 检索。

[[file-format]]
=== 文件格式

`config.txt` 文件由早期启动固件读取，因此它有一个非常简单的文件格式。格式是每行上的单个 `property=value` 语句，其中 `value` 是整数或字符串。可以添加注释，或者可以注释掉现有的配置值并禁用，方法是在行首添加 `#` 字符。

条目的行长限制为98个字符-超过此限制的任何字符都将被忽略。

这是一个示例文件：

[source,ini]
----
# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
----

[[advanced-features]]
=== 高级功能

[[include]]
==== `include` 

使指定文件的内容插入到当前文件中。

例如，在config.txt中添加 `include exfig.txt` 行将在 `config.txt` 文件中包含 `extraconfig.txt` 文件的内容。

[NOTE]
====

`bootcode.bin` 或 EEPROM 引导加载程序不支持 `include` 指令。

引导加载程序处理的设置只有在 `config.txt` （而不是任何其他包含的文件）中指定的情况下才会生效：

* `bootcode_delay` ,
* `gpu_mem` , `gpu_mem_256` , `gpu_mem_512` , `gpu_mem_1024` ,
* `total_mem` ,
* `sdram_freq` ,
* `start_x` , `start_debug` , `start_file` , `fixup_file` ,
* `uart_2ndstage` .

====

[[conditional-filtering]]
==== 条件过滤

条件过滤器在 xref:config_txt.adoc#conditional-filters[条件部分] 中介绍。
