== 模型部署

要将新的神经网络模型部署到Raspberry Pi AI相机，请完成以下步骤：

. 提供神经网络模型。
. 量化和压缩模型，以便它可以使用IMX500相机模块上可用的资源运行。
. 将压缩模型转换为IMX500格式。
. 将模型打包成固件文件，可以在运行时加载到相机上。

前三个步骤通常会在功能更强大的计算机（例如台式机或服务器）上执行。您必须在Raspberry Pi上运行最后的打包步骤。

=== 创建模型

神经网络模型的创建超出了本指南的范围。可以重用现有模型，也可以使用TensorFlow或PyTorch等流行框架创建新模型。

有关更多信息，请参阅官方 https://developer.aitrios.sony-semicon.com/en/raspberrypi-ai-camera[AITRIOS开发网站]。

=== 量化和压缩

使用Sony的模型压缩工具包对模型进行量化和压缩。要安装工具包，请运行以下命令：

[source,console]
----
$ pip install model_compression_toolkit
----

有关详细信息，请参阅 https://github.com/sony/model_optimization[索尼模型优化 GitHub 代码库]。

模型压缩工具包以以下格式生成量化模型：

* Keras (TensorFlow)
* ONNX (PyTorch)

=== 转换

要转换模型，首先安装转换器工具：

[tabs]
======
TensorFlow::
+
[source,console]
----
$ pip install imx500-converter[tf]
----
+
TIP: 始终使用用于压缩模型的相同版本的TensorFlow。

PyTorch：：
+
[source,console]
----
$ pip install imx500-converter[pt]
----
======

如果您需要安装这两个包，请使用两个单独的Python虚拟环境。这可以防止TensorFlow和PyTorch导致彼此冲突。

接下来，转换模型：

[tabs]
======
TensorFlow::
+
[source,console]
----
$ imxconv-tf -i <compressed Keras model> -o <output folder>
----

PyTorch::
+
[source,console]
----
$ imxconv-pt -i <compressed ONNX model> -o <output folder>
----
======

这两个命令都会创建一个包含内存使用报告和 `packerOut.zip` 文件的output文件夹。

为了优化IMX500传感器上加速器的可用存储器，请在上述命令中添加 `--no-input-persistency`。但是，这将禁用输入张量生成并返回应用程序进行调试。

有关模型转换过程的更多信息，请参阅官方 https://developer.aitrios.sony-semicon.com/en/raspberrypi-ai-camera/documentation/imx500-converter[索尼 IMX500 转换器文档资料]。

=== 打包

重要提示：您必须在Raspberry Pi上运行此步骤。

最后一步将模型打包到RPK文件中。运行神经网络模型时，我们会将此文件上传到AI相机。在继续之前，运行以下命令以安装必要的工具：

[source,console]
----
$ sudo apt install imx500-tools
----

要将模型打包到RPK文件中，请运行以下命令：

[source,console]
----
$ imx500-package -i <path to packerOut.zip> -o <output folder>
----

此命令应在输出文件夹中创建一个名为 `network.rpk` 的文件。您将把此文件的名称传给IMX500相机应用程序。

有关使用的工具的更全面的说明和更多细节，请参阅 https://developer.aitrios.sony-semicon.com/en/raspberrypi-ai-camera/documentation/imx500-packager[索尼 IMX500 打包文档]。
