== Raspberry Pi Pico C/{cpp} SDK

我们的官方C SDK可以从命令行使用，也可以从流行的集成开发环境中使用，如Visual Studio Code、Eclipse和CLion。要开始使用，请下载我们的C/{cpp}SDK和示例，并查看我们的“https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[getting started]”留档。或者有关快速设置，请参阅下一节。

您可以在以下位置找到C/{cpp}SDK的留档：

https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[Getting started with Raspberry Pi Pico-series]:: C/{cpp}开发与树莓派Pico，Pico2和其他树莓派microcontroller-based板

https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf[用 Raspberry Pi Pico W 连接互联网]:: 使用C/{cpp}或MicroPython在线获取Raspberry Pi Pico W

https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf[Raspberry Pi Pico-series C/{cpp} SDK]:: 库和工具，用于在Raspberry Pi微控制器上开发C/{cpp}

树莓派PicoC/{cpp}SDK的 xref:../pico-sdk/index_doxygen.adoc[API level documentation]:: 文档

https://github.com/raspberrypi/pico-examples[The pico-examples repository]:: 示例项目

SDK源代码是开源的，可通过 https://github.com/raspberrypi/pico-sdk[pico-sdk Github repository] 获得。

[NOTE]
====
要使用 C/{cpp} SDK 为除 Raspberry Pi Pico 之外的电路板构建应用程序，请向 CMake 传递 `-DPICO_BOARD=boardname`。要使用 C/{cpp} SDK 为 Raspberry Pi Pico 之外的电路板构建应用程序，请向 CMake 传递 `-DPICO_BOARD=boardname`，其中 `boardname` 是您的电路板名称。例如

* 要为 Adafruit Feather RP2040 构建应用程序，请通过 `-DPICO_BOARD=adafruit_feather_rp2040` 。
* 要为 Pico W 构建应用程序，请传递 `-DPICO_BOARD=pico_w`（如果希望连接到无线网络，还需添加参数 -DWIFI_SSID="Your Network" -DWIFI_PASSWORD="Your Password"）。

有关详细信息，请参阅 Raspberry Pi Pico SDK 中的 https://github.com/raspberrypi/pico-sdk/tree/master/src/boards[`boards/`目录]和 https://forums.raspberrypi.com/viewtopic.php?f=147&t=304393[论坛]。
====
