== Unicam

树莓派SoC都有两个摄像头接口，支持CSI-2 D-PHY 1.1或紧凑型摄像头端口2（CCP2）源。该接口的代号为 Unicam。Unicam 的第一个实例支持两个CSI-2数据通道，而第二个实例支持四个。每个通道可以以高达1Gbit/s（DDR，因此最大链路频率为500MHz）的速度运行。

Compute Modules 和 Raspberry Pi 5 可从两个外设引出所有通道。Raspberry Pi 5 之前的其他型号只引出了第二个通道到摄像头连接器。

=== 软件接口

V4L2软件接口是与Unicam外设通信的唯一方式。过去也有固件和MMAL rawcam组件接口，但不再支持这些。

==== V4L2

NOTE: Unicam的V4L2接口仅在使用 `libcamera` 时可用。

Unicam部分有一个完全开源的内核驱动程序；这个名为 `bcm2835-unicam` 的内核模块与V4L2子设备驱动程序接口以提供原始帧。这个 `bcm2835-unicam` 驱动程序控制传感器并配置相机串行接口2（CSI-2）接收器。外设将原始帧（在Debayer之后）写入SDRAM，以便V4L2交付给应用程序。捕获图像的相机传感器和将图像数据放入SDRAM的 `bcm2835-unicam` 驱动程序之间没有图像处理，除了Bayer解压为16位/像素。

----
|------------------------|
|     bcm2835-unicam     |
|------------------------|
     ^             |
     |      |-------------|
 img |      |  Subdevice  |
     |      |-------------|
     v   -SW/HW-   |
|---------|   |-----------|
| Unicam  |   | I2C or SPI|
|---------|   |-----------|
csi2/ ^             |
ccp2  |             |
    |-----------------|
    |     sensor      |
    |-----------------|
----

主线Linux包含一系列现有的驱动程序。树莓派内核树有一些额外的驱动程序和设备树覆盖来配置它们：

|===
| Device | Type | Notes

| Omnivision OV5647
| 5MP Camera
| Original Raspberry Pi Camera

| Sony IMX219
| 8MP Camera
| Revision 2 Raspberry Pi camera

| Sony IMX477
| 12MP Camera
| Raspberry Pi HQ camera

| Sony IMX708
| 12MP Camera
| Raspberry Pi Camera Module 3

| Sony IMX296
| 1.6MP Camera
| Raspberry Pi Global Shutter Camera Module

| Toshiba TC358743
| HDMI to CSI-2 bridge
|

| Analog Devices ADV728x-M
| Analog video to CSI-2 bridge
| No interlaced support

| Infineon IRS1125
| Time-of-flight depth sensor
| Supported by a third party
|===

由于子设备驱动程序也是具有标准化API的内核驱动程序，因此第三方可以自由地为他们选择的任何来源编写自己的驱动程序。

=== 写第三方驱动

这是通过Unicam进行接口的推荐方法。

为打算与 `bcm2835-unicam` 模块一起使用的新设备开发驱动程序时，您需要驱动程序和相应的设备树overlay。理想情况下，驱动程序应该提交到 http://vger.kernel.org/vger-lists.html#linux-media[linux-media] 邮件列表进行代码审查并合并到主线中，然后移动到 https://github.com/raspberrypi/linux[Raspberry Pi内核树]；但是驱动程序可能会被审查并直接合并到Raspberry Pi内核中。

NOTE: 所有内核驱动程序都在GPLv2许可下获得许可，因此源代码必须可用。仅运送二进制模块违反了Linux内核许可下的GPLv2许可。

`bcm2835-unicam` 模块已被编写为尝试适应当前主线Linux内核中所有类型的CSI-2源驱动程序。这些可以大致分为相机传感器和桥接芯片。桥接芯片允许在其他格式和CSI-2之间进行转换。

==== 相机传感器

相机传感器的传感器驱动程序负责设备的所有配置，通常通过I2C或SPI。与其从头开始编写驱动程序，不如以现有驱动程序为基础并酌情对其进行修改。

https://github.com/raspberrypi/linux/blob/rpi-6.1.y/drivers/media/i2c/imx219.c[IMX219驱动程序] 是一个很好的起点。该驱动程序支持8位和10位Bayer读出，因此枚举帧格式和帧大小稍微复杂一些。

传感器通常支持 https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/control.html[V4L2 用户控制]。并非所有这些控制都需要在驱动程序中实现。IMX219 驱动程序只实现了下面列出的一小部分，其实现由 `imx219_set_ctrl` 函数处理。

* `V4L2_CID_PIXEL_RATE` / `V4L2_CID_VBLANK` / `V4L2_CID_HBLANK` ：允许应用程序设置帧频。
* `V4L2_CID_EXPOSURE` : 以行为单位设置曝光时间；应用程序需要使用 `V4L2_CID_PIXEL_RATE`、 `V4L2_CID_HBLANK` 和帧宽来计算行时间。
* `V4L2_CID_ANALOGUE_GAIN` ：以传感器为单位的模拟增益
* `V4L2_CID_DIGITAL_GAIN`：以传感器为单位的可选数字增益
* `V4L2_CID_HFLIP / V4L2_CID_VFLIP` ： 水平或垂直翻转图像；此操作可能会改变帧中数据的Bayer顺序，IMX219 就是这种情况。
* `V4L2_CID_TEST_PATTERN` / `V4L2_CID_TEST_PATTERN_*` ：可从传感器输出各种测试模式；对调试非常有用。

对于IMX219，其中许多控件直接映射到寄存器写入传感器本身。

进一步的指导可以在 `libcamera` https://git.linuxtv.org/libcamera.git/tree/Documentation/sensor_driver_requirements.rst[传感器驱动程序要求]和 https://datasheets.raspberrypi.com/camera/raspberry-pi-camera-guide.pdf[树莓派相机调谐指南] 的第3章中找到。


===== 设备树

设备树用于选择传感器驱动程序并配置参数，例如CSI-2通道数、连续时钟通道操作和链路频率（通常只支持一个）。

6.1版本内核中IMX219的 https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/overlays/imx219-overlay.dts[Device Tree overlay] 可在GitHub上获得。

==== 桥接芯片

这些设备将传入的视频流（例如HDMI或复合）转换为Raspberry Pi CSI-2接收器可以接受的CSI-2流。

处理桥接芯片更复杂。与相机传感器不同，它们必须响应传入信号并将其报告给应用程序。

处理桥接芯片的机制可以分为两类：模拟或数字。

在下面的章节中使用 `ioctls` 时， `ioctl` 名称中的 `_S_` 表示它是一个 set 函数，而 `_G_` 是一个 get 函数， `_ENUM_` 枚举一组允许的值。

===== 模拟视频源

模拟视频源使用标准 `ioctls` 检测和设置视频标准。https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-g-std.html[`VIDIOC_G_STD`]、https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-g-std.html[`VIDIOC_S_STD`], https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-enumstd.html[`VIDIOC_ENUMSTD`] 和 https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-querystd.html[`VIDIOC_QUERYSTD`] 可用。

选择错误的标准通常会导致图像损坏。设置标准通常也会设置 V4L2 CAPTURE 队列的分辨率。它不能通过 `VIDIOC_S_FMT` 设置。一般来说，通过 `VIDIOC_QUERYSTD` 请求检测到的标准，然后在流媒体播放前用 `VIDIOC_S_STD` 设置是个好主意。

===== 数字视频源

对于数字视频源，例如HDMI，有一组备用调用允许指定所有数字定时参数：https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-g-dv-timings.html[`VIDIOC_G_DV_TIMINGS`], https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-g-dv-timings.html[`VIDIOC_S_DV_TIMINGS`], https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-enum-dv-timings.html[`VIDIOC_ENUM_DV_TIMINGS`] 和 https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-query-dv-timings.html[`VIDIOC_QUERY_DV_TIMINGS`]。

与模拟网桥一样，时序通常会固定 V4L2 CAPTURE 队列的分辨率，在流媒体传输之前，用 `VIDIOC_QUERY_DV_TIMINGS` 的结果调用 `VIDIOC_S_DV_TIMINGS` 应能确保格式正确。

根据桥接芯片和驱动程序，可以通过 `VIDIOC_SUBSCRIBE_EVENT` 和 `V4L2_EVENT_SOURCE_CHANGE` 向应用程序报告输入源的变化。

===== 当前支持的设备

Raspberry PiLinux内核目前支持两种桥接芯片：用于模拟视频源的Analog Devices ADV728x-M和用于HDMI源的Toshiba TC358743。

ADI公司 ADV728x(A)-M 模拟视频到CSI2桥接芯片将复合S视频（Y/C）或分量（YPrPb）视频转换为单通道CSI-2接口，并由 https://github.com/raspberrypi/linux/blob/rpi-6.1.y/drivers/media/i2c/adv7180.c[ADV7180内核驱动程序] 支持。

有关该芯片各种版本的产品详细信息，请访问 Analog Devices 网站：https://www.analog.com/en/products/adv7280a.html[ADV7280A], https://www.analog.com/en/products/adv7281a.html[ADV7281A] 和 https://www.analog.com/en/products/adv7282a.html[ADV7282A]。

由于当前 V4L2 核心实现中的某些代码缺失，导致选择源失败，因此树莓派内核版本为 ADV7180 内核驱动程序添加了一个名为 `dbg_input` 的内核模块参数，每次调用 VIDIOC_S_STD 时都会设置输入源。主流将在某个时候修复根本问题（内核 API 调用 s_routing 与用户空间调用 `VIDIOC_S_INPUT` 之间的脱节），届时这一修改将被删除。

不支持接收隔行扫描视频，因此 ADV7281(A)-M 版本的芯片用途有限，因为它没有必要的 I2P 去隔行扫描块。在选择设备时，请确保指定 -M 选项。否则，您将得到一个并行输出总线，无法与 Raspberry Pi 连接。

目前尚无使用这些芯片的商用电路板，但此驱动程序已通过ADI公司 https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/EVAL-ADV7282A-M.html[EVAL-ADV7282-M评估板] 进行了测试。

如果使用的是 "ADV7282-M "芯片变体，可使用 "config.txt "dtoverlay "adv7282m "加载该驱动程序；如果使用的是其他变体，可使用 "adv7280m=1"、"adv7281m=1 "或 "adv7281ma=1 "参数加载 "adv728x-m "驱动程序。

----
dtoverlay=adv728x-m,adv7280m=1
----

东芝 TC358743 是一款 HDMI 转 CSI-2 桥接芯片，能够转换最高 1080p60 的视频数据。。

关于这款桥接芯片的信息可以在 https://toshiba.semicon-storage.com/ap-en/semiconductor/product/interface-bridge-ics-for-mobile-peripheral-devices/hdmir-interface-bridge-ics/detail.TC358743XBG.html[东芝网站] 上找到。

TC358743将HDMI连接到CSI-2和I2S输出。它由 https://github.com/raspberrypi/linux/blob/rpi-6.1.y/drivers/media/i2c/tc358743.c[TC358743内核模块] 支持。

该芯片支持输入 RGB888、YUV444 或 YUV422 的 HDMI 信号，最高可达 1080p60。它可以转发 RGB888，或将其转换为 YUV444 或 YUV422，也可以在 YUV444 和 YUV422 之间进行转换。目前只测试了对 RGB888 和 YUV422 的支持。使用两个 CSI-2 通道时，可支持的最大速率为 RGB888 的 1080p30 或 YUV422 的 1080p50。在计算模块上使用四个通道时，可接收 1080p60 的任一格式。

HDMI 通过接收设备发布一个包含所有可支持模式的 https://en.wikipedia.org/wiki/Extended_Display_Identification_Data[EDID] 来协商分辨率。内核驱动程序并不了解用户希望接收的分辨率、帧速率或格式，因此用户需要通过 VIDIOC_S_EDID ioctl 提供合适的文件，或者使用 `v4l2-ctl --fix-edid-checksums --set-edid=file=filename.txt` （添加 --fix-edid-checksums 选项意味着用户不必在源文件中获取正确的校验和值）。生成所需的 EDID 文件（二进制 EDID 文件的文本十六进制转储）并不繁琐，也有一些工具可以生成，但不在本页讨论范围之内。

如上所述，使用 `DV_TIMINGS` ioctls 配置驱动程序以匹配传入视频。最简单的方法是使用 `v4l2-ctl --set-dv-bt-timings query` 命令。驱动程序确实支持生成 "SOURCE_CHANGED "事件，如果你想编写一个应用程序来处理不断变化的信号源的话。通过 `VIDIOC_S_FMT` 设置可更改输出像素格式，但只有像素格式字段会更新，因为分辨率是由 DV 时序配置的。

市面上有几种电路板可以将这种芯片连接到 Raspberry Pi。最常见的是 Auvidea B101 和 B102，但也有其他同类电路板。

该驱动程序使用 `config.txt` dtoverlay `tc358743` 加载。

该芯片还支持通过 I2S 捕捉立体声 HDMI 音频。Auvidea 电路板将相关信号分解到一个针座上，然后连接到 Raspberry Pi 的 40 针座上。所需接线如下

[cols=",^,^,^"]
|===
| Signal | B101 header | 40-pin header | BCM GPIO

| LRCK/WFS
| 7
| 35
| 19

| BCK/SCK
| 6
| 12
| 18

| DATA/SD
| 5
| 38
| 20

| GND
| 8
| 39
| N/A
|===


除了 `tc358743-audio` 覆盖层之外，还需要 `tc358743` 覆盖层。这将为 HDMI 音频创建一个 ALSA 录音设备。

音频不会重新采样。音频的存在反映在 V4L2 控制 `TC358743_CID_AUDIO_PRESENT` （音频存在）中，输入音频的采样率反映在 V4L2 控制 `TC358743_CID_AUDIO_SAMPLING_RATE` （音频采样频率）中。在没有音频或音频采样率与报告的采样率不同的情况下进行录音会发出警告。
