=== 编写自己的后处理阶段

使用 `rpicam-apps` 后处理框架，用户可以创建自己的自定义后处理阶段。您甚至可以包含来自OpenCV和TensorFlow Lite的算法和例程。

==== 基本后处理阶段

要创建自己的后处理阶段，请从 `PostProcessingStage` 类派生一个新类。
所有后处理阶段必须实现以下成员功能：

`char const *Name() const`:: 返回阶段名称。与 JSON 后处理配置文件中列出的阶段匹配。
`void Read(boost::property_tree::ptree const &params)`:: 从提供的 JSON 文件中读取舞台的配置参数。
`void AdjustConfig(std::string const &use_case, StreamConfiguration *config)`:: 为舞台提供影响摄像机配置的机会。对于不需要配置摄像机的舞台，通常为空。
`void Configure()`:: 在摄像机配置完成后调用，以分配资源并检查舞台是否能访问必要的数据流。
`void Start()`:: 摄像机启动时调用。对于不需要配置摄像机的舞台，通常为空。
`bool Process(CompletedRequest &completed_request)`:: 显示已完成的摄像机请求，以便进行后处理。这是您执行像素处理和图像分析的地方。如果后处理框架不应***将此请求传送给应用程序，则返回 `true` 。
`void Stop()`:: 摄像机停止时调用。用于关闭异步线程上的任何活动处理。
`void Teardown()`:: 摄像机配置销毁时调用。将其用作解构器，在此可以取消分配在 `Configure` 方法中设置的资源。

在任何阶段实现中，调用 `RegisterStage` 向系统注册您的阶段。

不要忘记将您的stage添加到后处理文件夹中的 `meson.build` 中。

在编写自己的阶段时，请记住以下TIP: 

* `Process` 方法阻塞成像管道。如果时间太长，管道会卡顿。**始终将耗时的算法委托给异步线程。**

* 将工作委托给另一个线程时，您必须复制图像缓冲区。对于不需要全分辨率的图像分析等应用程序，请尝试使用低分辨率图像流。

* 后处理框架_使用并行方式处理每个帧_。这提高了吞吐量。然而，一些 OpenCV 和 TensorFlow Lite 函数在每个帧内引入了另一层并行性。考虑在每一帧内序列化调用，因为后处理已经利用了多个线程。

* 大多数流，包括低分辨率流，使用YUV420格式。对于某些OpenCV或TFLite功能，您可能需要将其转换为另一种格式。

* 为获得最佳性能，请务必就地修改图像。

关于一个基本的例子，请参见 https://github.com/raspberrypi/rpicam-apps/blob/main/post_processing_stages/negate_stage.cpp[`negate_stage.cpp`]。这个阶段通过将亮像素变暗和暗像素变亮来反相图像。这个阶段主要是派生类样板，只用六行代码就实现了反相逻辑。

另一个例子，请参见 https://github.com/raspberrypi/rpicam-apps/blob/main/post_processing_stages/sobel_cv_stage.cpp[`sobel_cv_stage.cpp`]，它仅在几行OpenCV函数中实现了Sobel过滤器。

==== TensorFlow Lite阶段

对于使用TensorFlow Lite（TFLite）的阶段，从 `TfStage` 类派生一个新类。
此类将模型执行委托给单独的线程以防止相机卡顿。

`TfStage` 类实现了后处理阶段通常必须实现的所有 `PostProcessingStage` 成员函数，_除了_ `` Name `` 。"
所有 `TfStage` 派生的阶段都必须实现 `` Name `` 函数，并且应该实现以下部分或全部虚拟成员函数：

`void readExtras（）`::基类读取命名模型和某些其他参数，如 `refresh_rate` 。使用此函数this读取派生阶段的额外参数并检查加载的模型是否正确（例如具有正确的输入和输出尺寸）。
`void checkConfiguration()`:: 基类获取 TFLite 运行所需的低分辨率数据流和全分辨率数据流，以备派生阶段之需。使用此函数检查舞台所需的流。如果您的舞台无法访问所需的流之一，您可能会跳过处理或抛出错误。
`void interpretOutputs()`::  使用此函数读取并解释模型输出。当模型完成时，在与模型相同的线程中运行。
`void applyResults()`::  使用此函数将模型结果（可能是几帧前的结果）应用到当前帧。通常涉及附加元数据或绘图。在主线程中运行，在帧传送之前。

有关示例实现，请参见 https://github.com/raspberrypi/rpicam-apps/blob/main/post_processing_stages/object_classify_tf_stage.cpp[`object_classify_tf_stage.cpp` ] 和 https://github.com/raspberrypi/rpicam-apps/blob/main/post_processing_stages/pose_estimation_tf_stage.cpp[ `pose_estimation_tf_stage.cpp`]。
