== 高级  `rpicam-apps` 

[[build-libcamera-and-rpicam-apps]]
=== 构建 `libcamera` 和 `rpicam-apps` 

为自己构建 `libcamera` 和 `rpicam-apps` 有以下优点：

* 您可以获得最新的增强功能和特性。

* `rpicam-apps` 可以针对运行 32 位操作系统的 Raspberry Pi 3 和 Raspberry Pi 4 设备进行额外优化编译。

* 您可以包含可选的 OpenCV 和/或 TFLite 后处理阶段，也可以添加您自己的阶段。

* 您可以自定义或添加您自己的源自 `rpicam-apps` 的应用程序

==== 删除预装的 `rpicam-apps`

Raspberry Pi OS 包含预安装的 `rpicam-apps` 副本。在构建和安装自己的 `rpicam-apps` 版本之前，必须先移除预安装版本。运行以下命令从 Raspberry Pi 上删除 `rpicam-apps` 软件包：

[源码,控制台］
----
$ sudo apt remove --purge rpicam-apps
----

==== Building `rpicam-apps` without building `libcamera`

To build `rpicam-apps` without first rebuilding `libcamera` and `libepoxy`, install `libcamera`, `libepoxy` and their dependencies with `apt`:

[source,console]
----
$ sudo apt install -y libcamera-dev libepoxy-dev libjpeg-dev libtiff5-dev libpng-dev
----

TIP: 如果您不需要支持 GLES/EGL 预览窗口，请省略 `libepoxy-dev` 。

要使用 Qt 预览窗口，请安装以下附加依赖项：

[source,console]
----
$ sudo apt install -y qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5
----

要获得 `rpicam-vid` 中的 xref:camera_software.adoc#libav-integration-with-rpicam-vid[`libav`] 支持，请安装以下附加依赖项：

[source,console]
----
$ sudo apt install libavcodec-dev libavdevice-dev libavformat-dev libswresample-dev
----

如果您运行的是 Raspberry Pi OS Lite，请安装 `git` ：

[source,console]
----
$ sudo apt install -y git
----

接下来，xref:camera_software.adoc#building-rpicam-apps[build `rpicam-apps` ]。

[[building-libcamera]]
==== 构建  `libcamera` 

NOTE: 如果您需要自定义行为或 `apt` 源内的包还未支持的最新功能，请仅从头构建 `libcamera` 。

[NOTE]
======
如果您运行 Raspberry Pi OS Lite，请先安装以下软件包：

[source,console]
----
$ sudo apt install -y python3-pip git python3-jinja2
----
======

首先，安装以下 `libcamera` 依赖项：

[source,console]
----
$ sudo apt install -y libboost-dev
$ sudo apt install -y libgnutls28-dev openssl libtiff5-dev pybind11-dev
$ sudo apt install -y qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5
$ sudo apt install -y meson cmake
$ sudo apt install -y python3-yaml python3-ply
$ sudo apt install -y libglib2.0-dev libgstreamer-plugins-base1.0-dev
----

现在我们准备构建 `libcamera` 本身。

从 GitHub 下载 Raspberry Pi 的 `libcamera` 分支的本地副本：

[source,console]
----
$ git clone https://github.com/raspberrypi/libcamera.git
----

导航到存储库的根目录：

[source,console]
----
$ cd libcamera
----

接下来，运行 `meson` 来配置构建环境：

[source,console]
----
$ meson setup build --buildtype=release -Dpipelines=rpi/vc4,rpi/pisp -Dipas=rpi/vc4,rpi/pisp -Dv4l2=true -Dgstreamer=enabled -Dtest=false -Dlc-compliance=disabled -Dcam=disabled -Dqcam=disabled -Ddocumentation=disabled -Dpycamera=enabled
----

NOTE: 您可以通过替换 `-Dgstreamer=enabled` 来禁用 `gstreamer` 插件在 `meson` 构建配置期间使用 `-Dgstreamer=disabled` 。如果禁用 `gstreamer` ，则无需安装 `libglib2.0-dev` 和 `libgstreamer-plugins-base1.0-dev` 依赖项。

现在，您可以使用 `ninja` 构建 `libcamera` ：

[source,console]
----
$ ninja -C build
----

最后，运行以下命令安装您刚刚构建的 `libcamera` 二进制文件：

[source,console]
----
$ sudo ninja -C build install
----

TIP: 在内存为 1GB 或更少的设备上，构建可能会超出可用内存。将 `-j 1` 标志附加到 `ninja` 命令以将构建限制为单个进程。这应该可以防止构建超出 Raspberry Pi Zero 和 Raspberry Pi 3 等设备上的可用内存。

`libcamera` 尚未具有稳定的二进制接口。始终在构建 `libcamera` 之后构建 `rpicam-apps` 。

[[building-rpicam-apps]]
==== 构建 `rpicam-apps` 

首先获取 `rpicam-apps` 所需的依赖项。

[source,console]
----
$ sudo apt install -y cmake libboost-program-options-dev libdrm-dev libexif-dev
$ sudo apt install -y meson ninja-build
----

下载 Raspberry Pi 的 `rpicam-apps` GitHub 存储库的本地副本：

[source,console]
----
$ git clone https://github.com/raspberrypi/rpicam-apps.git
----

导航到存储库的根目录：

[source,console]
----
$ cd rpicam-apps
----

对于基于桌面的操作系统（如 Raspberry Pi OS），使用以下 `meson` 命令配置 `rpicam-apps` 构建：

[source,console]
----
$ meson setup build -Denable_libav=enabled -Denable_drm=enabled -Denable_egl=enabled -Denable_qt=enabled -Denable_opencv=disabled -Denable_tflite=disabled -Denable_hailo=disabled
----

对于 Raspberry Pi OS Lite 等无人机交互操作系统，请使用以下 `meson` 命令配置 `rpicam-apps` 构建：

[source,console]
----
$ meson setup build -Denable_libav=disabled -Denable_drm=enabled -Denable_egl=disabled -Denable_qt=disabled -Denable_opencv=disabled -Denable_tflite=disabled -Denable_hailo=disabled
----

[TIP]
======

* 使用 `-Dneon_flags=armv8-neon` 为 Raspberry Pi 3 或 Raspberry Pi 4 上的 32 位操作系统启用优化。
* 如果您已安装 OpenCV 并希望使用基于 OpenCV 的后处理阶段，请使用 `-Denable_opencv=enabled` 。
* 如果您已安装 TensorFlow Lite 并希望在后处理阶段使用它，请使用 `-Denable_tflite=enabled` 。
* 如果安装了 HailoRT 并希望在后处理阶段使用它，请使用 `-Denable_hailo=enabled` 。

======

您现在可以使用以下命令构建 `rpicam-apps` ：

[source,console]
----
$ meson compile -C build
----

TIP: 在内存为 1GB 或更少的设备上，构建可能会超出可用内存。将 `-j 1` 标志加在 `meson` 命令后面将构建限制为单个进程。这应该可以防止构建超出 Raspberry Pi Zero 和 Raspberry Pi 3 等设备上的可用内存。

最后，运行以下命令安装您新构建的 `rpicam-apps` 二进制文件：

[source,console]
----
$ sudo meson install -C build
----

安装后打开一个新的终端窗口，以确保您使用新的二进制文件。

最后，按照 xref:camera_software.adoc#configuration[配置部分] 中的 `dtoverlay` 和显示驱动程序说明进行操作。

[TIP]
====
上述命令会自动更新 `ldconfig` 缓存。如果在访问新的 `rpicam-apps` 版本时遇到问题，请运行以下命令更新缓存：

[source,console]
----
$ sudo ldconfig
----
====

运行以下命令检查设备是否使用了新的二进制文件：

[source,console]
----
$ rpicam-still --version
----

输出结果应包括本地 `rpicam-apps` 生成的日期和时间。

==== `rpicam-apps` meson标志参考


`rpicam-apps` 的 `meson` 构建配置支持以下标志：

`-Dneon_flags=armv8-neon`:: 加快运行 32 位操作系统的 Raspberry Pi 3 或 Raspberry Pi 4 设备上的某些后处理功能。

`-Denable_libav=enabled`:: 启用或禁用 `libav` 编码器集成。

`-Denable_drm=enabled`:: 启用或禁用 **DRM/KMS 预览渲染**，即在没有桌面环境的情况下使用的预览窗口。

`-Denable_egl=enabled`:: 启用或禁用非基于 Qt 桌面环境的预览。如果您的系统缺少桌面环境，请禁用。

`-Denable_qt=enabled`:: 启用或禁用对基于 Qt 的预览窗口实现的支持。如果您未安装桌面环境或不打算使用基于 Qt 的预览窗口，请禁用。通常不推荐使用基于 Qt 的预览，因为它的计算成本非常高，但它可以与 X 显示转发配合使用。

`-Denable_opencv=enabled`:: 强制基于 OpenCV 的后处理阶段链接或不链接。需要 OpenCV 才能启用。默认为 `disabled` 。

`-Denable_tflite=enabled`:: 启用或禁用 TensorFlow Lite 后处理阶段。默认情况下禁用。需要 Tensorflow Lite 才能启用。根据您构建和/或安装 TFLite 的方式，您可能需要调整 `post_processing_stages` 目录中的 `meson.build` 文件。

`Denable_hailo=enabled`:: 启用或禁用基于 HailoRT 的后处理阶段。需要 HailoRT 才能启用。默认为 `auto`。

`Ddownload_hailo_models=true`:: 为 HailoRT 后处理阶段下载并安装模型。需要安装 `wget`。默认为 `true`。


上述每个选项（除 `neon_flags` 外）都支持以下值：

* `enabled` ：启用该选项，如果依赖项不可用，则构建失败
* `disabled` ：禁用该选项
* `auto` ：如果依赖项可用，则启用该选项

==== 构建 `libepoxy` 

通常不需要重建 `libepoxy` ，因为这个库很少更改。但是，如果您确实想从头开始构建它，请按照以下说明操作。

首先安装必要的依赖项。

[source,console]
----
$ sudo apt install -y libegl1-mesa-dev
----

接下来，从 GitHub 下载 `libepoxy` 存储库的本地副本：

[source,console]
----
$ git clone https://github.com/anholt/libepoxy.git
----

导航到存储库的根目录：

[source,console]
----
$ cd libepoxy
----

在存储库的根级别创建一个构建目录，然后导航到该目录：

[source,console]
----
$ mkdir _build
$ cd _build
----

接下来，运行 `meson` 来配置构建环境：

[source,console]
----
$ meson
----

现在，您可以使用 `ninja` 构建 `libexpoxy` ：

[source,console]
----
$ ninja
----

最后，运行以下命令来安装您刚刚构建的 `libepoxy` 二进制文件：

[source,console]
----
$ sudo ninja install
----
