=== 图像选项

本节中指定的命令行选项仅适用于静止图像输出。

要将以下选项之一传递给应用程序，请在选项名称前加上 `--` .如果选项需要值，请在选项名称后立即传递该值，并用单个空格分隔。如果值包含空格，请将值用引号括起来。

一些选项有速记别名，例如 `-h` 而不是 `--help` 。使用这些速记别名而不是完整的选项名称可以节省空间和时间，但会牺牲易读性。

==== `quality` 

别名： `-q` 

默认值： `93` 

设置JPEG质量。接受介于 `1` 和 `100` 之间的值。

==== `exif` 

在JPEG输出文件中保存额外的EXIF标签。仅适用于JPEG输出。由于 `libexif` 库中的限制，许多标签当前（错误地）格式化为ASCII并在终端中打印警告。

此选项对于添加与相机设置相关的某些EXIF标签是必需的，您可以在使用 https://exiftool.org/[ExifTool] 录制后将与相机设置无关的标签添加到输出JPEG。

示例： `rpicam-still -o test.jpg --exif IDO0.Artist=Someone` 

[[timelapse]]
==== `timelapse` 

以指定的间隔记录图像。接受以毫秒为单位的间隔。将此设置与 xref:camera_software.adoc#timeout[`timeout`] 结合使用以捕获一段时间内重复的图像。

您可以使用字符串格式为每个输出文件指定单独的文件名，例如 `--output test%d.jpg` 。

示例： `rpicam-still -t 100000 -o test%d.jpg --timelapse 10000` 每10秒捕获一张图像，持续100秒。

==== `framestart` 

将在输出文件名中访问的帧计数器的起始值配置为 `%d` 。接受整数起始值。

[[datetime]]
==== `datetime` 

在输出文件名中使用当前日期和时间，形式为 `MMDDhhmmss.jpg` :

* `MM` = 2位月数
* `DD` = 2位数的天数
* `hh` = 2位24小时小时数
* `mm` = 2位分钟数
* `ss` = 2位第二个数字

不接受值。

[[timestamp]]
==== `timestamp` 

使用当前系统 https://en.wikipedia.org/wiki/Unix_time[Unix time] 作为输出文件名。不接受值。

==== `restart` 

默认值： `0` 

配置 JPEG 输出的重启标记间隔。JPEG 重启标记可帮助限制损坏对 JPEG 图像的影响，还能启用多线程 JPEG 编码和解码。接受整数值。

[[immediate]]
==== `immediate` 

在应用程序运行时立即捕获图像。

==== `keypress` 

别名： `-k` 

当 xref:camera_software.adoc#timeout[`timeout`] 过期或按 *Enter* 键时捕获图像，以先到者为准。按 `x` 键，然后按 *Enter* 退出而不捕获。不接受值。

==== `signal` 

当 xref:camera_software.adoc#timeout[`timeout`] 过期或收到 `SIGUSR1` 时捕获图像。使用 `SIGUSR2` 退出而不捕获。不接受值。

==== `thumb` 

默认值： `320:240:70` 

使用以下格式配置缩略图的尺寸和质量： `<w:h:q>` （或 `none` ，省略缩略图）。

[[encoding]]
==== `encoding` 

别名： `-e` 

默认值： `jpg` 

设置用于图像输出的编码器。接受以下值：

* `jpg` - JPEG
* `png` - PNG
* `bmp` - BMP
* `rgb` - 未压缩RGB像素的二进制转储
* `yuv420` - 未压缩YUV420像素的二进制转储

此选项始终确定编码，覆盖传递给 xref:camera_software.adoc#output[`output`] 的扩展名。

使用 xref:camera_software.adoc#datetime[`datetime` ]和 xref:camera_software.adoc#timestamp[ `timestamp`] 选项时，此选项确定输出文件扩展名。

[[raw]]
==== `raw` 

别名： `-r` 

除输出图像外，还以 DNG 格式保存原始 Bayer 文件。用 `.dng` 替换输出文件扩展名。您可以使用 _dcraw_ 或 _RawTherapee_ 等工具处理这些标准 DNG 文件。不接受数值。

原始文件中的图像数据正是来自传感器的数据，没有来自ISP或其他任何东西的处理。文件中保存的EXIF数据包括：

* 曝光时间
* 模拟增益（ISO标签是使用的模拟增益的100倍）
* 白平衡增益（这是 `拍摄中性` 值的倒数）
* ISP使用的颜色矩阵

[[latest]]
==== `latest` 

创建指向最近保存的文件的符号链接。接受符号链接名称作为输入。

[[autofocus-on-capture]]
==== `autofocus-on-capture` 

如果设置，则在捕捉图像之前运行自动对焦循环。与下列 xref:camera_software.adoc#autofocus-mode[`autofocus_mode`] 值交互：

* `default` 或 `manual` ：只运行捕捉时的自动对焦循环。

* `auto` ：在预览窗口加载时运行额外的自动对焦循环。

* `continuous` : 忽略此选项，而是在整个预览过程中持续对焦。

不需要数值，但可以通过 `1` 启用，通过 `0` 关闭。不传递值等同于传递 `1` 。

只有某些相机模块（如 _Raspberry Pi Camera Module 3_）支持该选项。
