[[troubleshooting]]
== 故障排除

如果你的相机模块不能像你期望的那样工作，请尝试以下修复方法：

* 在运行 Raspberry Pi OS _Bullseye_ 或更早版本的 Raspberry Pi 3 及更早设备上： 
** 要启用硬件加速相机预览，请启用 *Glamor*。要启用 Glamor，在终端中输入 `sudo raspi-config` ，选择 `Advanced Options` > `Glamor` > `Yes` 。然后用 `sudo reboot` 重启树莓派。 
** 如果看到与显示驱动程序有关的错误，在 `/boot/config.txt` 中添加 `dtoverlay=vc4-fkms-v3d` 或 `dtoverlay=vc4-kms-v3d` 。
* 在 Raspberry Pi 3 及更早的版本中，图形硬件只能支持最大 2048×2048 像素的图像，这就限制了预览窗口中可调整大小的摄像头图像。因此，对宽度大于 2048 像素的图像进行视频编码时，会产生损坏或丢失的预览图像。 
* 在 Raspberry Pi 4 上，图形硬件只能支持最大 4096×4096 像素的图像，这就限制了可在预览窗口中调整大小的摄像头图像。因此，对宽度大于 4096 像素的图像进行视频编码时，会产生损坏或丢失的预览图像。 
* 在桌面环境中，预览窗口可能会出现显示撕裂。这是一个已知但是无法修复的问题
* 检查 FFC（扁平软电缆）是否牢固就位、完全插入，以及触点是否朝向正确方向。
* 如果在摄像头和 Raspberry Pi 之间使用连接器，请检查连接器上的端口是否牢固就位、完全插入，以及触点是否朝向正确方向。 
* 检查并确保 FFC（扁平软电缆）连接到 CSI（摄像头串行接口），而不是 DSI（显示器串行接口）。连接器可以插入任何一个端口，但只有 CSI 端口可以供电和控制摄像头。请查看印在端口附近电路板上的 "CSI "标签。 
* xref:os.adoc#update-software[更新至最新软件] 
* 尝试使用不同的电源。相机模块会增加 Raspberry Pi 约 200-250mA 的电力需求。如果您的电源质量较差，您的 Raspberry Pi 可能无法为相机模块供电。 
* 如果您已经检查了上述所有问题，但您的相机模块仍然无法像您期望的那样工作，请尝试在我们的论坛上发帖寻求更多帮助。
