//包含在silicon. adoc和Pico-系列.adoc中

== Documentation

Pico系列和其他树莓派microcontroller-based板的文档。

=== RP2350

https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf[RP2350 Datasheet]:: 树莓派的微控制器

https://datasheets.raspberrypi.com/rp2350/hardware-design-with-rp2350.pdf[Hardware design with RP2350]:: 使用RP2350微控制器构建电路板和产品

=== RP2040

https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf[RP2040 Datasheet]:: 树莓派的微控制器

https://datasheets.raspberrypi.com/rp2040/hardware-design-with-rp2040.pdf[Hardware design with RP2040]:: 使用RP2040微控制器构建电路板和产品

=== Raspberry Pi Pico 2

https://datasheets.raspberrypi.com/pico/pico-2-datasheet.pdf[Raspberry Pi Pico 2 Datasheet]:: 基于RP2350的微控制器板

使用Raspberry PiPico系列器件和其他Raspberry Pimicrocontroller-based开发 https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[Getting started with Raspberry Pi Pico-series Microcontrollers]:: C/{cpp}

=== Raspberry Pi Pico

https://datasheets.raspberrypi.com/pico/pico-datasheet.pdf[Raspberry Pi Pico Datasheet]:: 基于RP2040的微控制器板

https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf[Getting started with Raspberry Pi Pico-series Microcontrollers]:: C/{cpp}开发与树莓派Pico系列和其他基于RP2040的微控制器板

=== Raspberry Pi Pico 2 W

https://datasheets.raspberrypi.com/picow/pico-2-w-datasheet.pdf[Raspberry Pi Pico 2 W Datasheet]:: 基于RP2350的无线微控制器板

https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf[Connecting to the Internet with Raspberry Pi Pico W-series]:: 使用C/{cpp}或MicroPython在线获取Raspberry PiPicoW系列设备

=== Raspberry Pi Pico W

https://datasheets.raspberrypi.com/picow/pico-w-datasheet.pdf[Raspberry Pi Pico W Datasheet]:: 基于RP2040的无线微控制器板

https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf[Connecting to the Internet with Raspberry Pi Pico W-series]:: 使用C/{cpp}或MicroPython在线获取Raspberry PiPicoW系列设备

=== Software Development

用于在RP2040微控制器上开发C/{cpp}的 https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf[Raspberry Pi Pico C/{cpp} SDK]:: 库和工具

https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-python-sdk.pdf[Raspberry Pi Pico Python SDK]:: 用于RP2040微控制器的MicroPython环境

Raspberry PiPicoC/{cpp}SDK的API级别Doxygen 文档也可用 https://rptl.io/pico-doxygen[as a micro-site]。

