[[boot-folder-contents]]
== `boot` 文件夹内容

Raspberry Pi OS将引导文件存储在SD卡的第一个分区上，使用FAT文件系统。

启动时，每个Raspberry Pi都会从引导分区加载各种文件，以便在Linux内核启动之前启动各种处理器。

在引导时，Linux将引导分区挂载为 `/boot/firmware/` 。

NOTE: 在 _Bookworm_ 之前，树莓派操作系统将引导分区存储在 `/boot/` 。从 _Bookworm_ 开始，引导分区位于 `/boot/firmware/` 。

[[bootcode-bin]]
=== `bootcode.bin` 

引导加载程序，由SoC在引导时加载。它执行一些非常基本的设置，然后加载其中一个 `start*.elf` 文件。

Raspberry Pi 4和5不使用bootcode.bin。它已被 xref:raspberry-pi.adoc#raspberry-pi-boot-eeprom[板载EEPROM] 中的引导代码代替。

=== `start*.elf` 

二进制固件块加载到 SoC 中的 VideoCore GPU 上，然后接管启动过程。

`start.elf`:: 基本固件。
`start_x.elf`:: 包含额外的编解码器。
`start_db.elf`:: 用于调试。
`start_cd.elf`:: 固件的精简版，删除了对编解码器和 3D 等硬件模块的支持以及调试日志支持；它还施加了初始帧缓冲区限制。如果在 `config.txt` 中指定了 `gpu_mem=16`，则会自动使用精简版固件。


`start4.elf` , `start4x.elf` , `start4db.elf` 和 `start4cd.elf` 是特定于Raspberry Pi 4系列（Model 4B, Pi 400, Compute Module 4 和 Compute Module 4S）的同功能固件文件。

有关如何使用这些文件的详细信息，请参阅 xref:config_txt.adoc#boot-options[ `config.txt` 文档].

Raspberry Pi 5 不使用 `elf` 文件。固件独立包含在引导加载程序EEPROM中。

=== `fixup*.dat` 

与上一节中列出的 `start*.elf` 文件配对的链接器文件。

[[cmdline-txt]]
=== `cmdline.txt` 

启动时传入内核的 <<kernel-command-line-cmdline-txt,kernel command line>>

[[config-txt]]
=== `config.txt` 

包含用于设置Raspberry Pi的许多配置参数。有关详细信息，请参阅 xref:config_txt.adoc[ `config.txt` 文档].。

IMPORTANT: Raspberry Pi 5 要求启动分区中有一个非空的 `config.txt` 文件。

[[issue-txt]]
=== `issue.txt` 

基于文本的内务信息，包含发行版的日期和 git commit ID。

=== `initramfs*` 

初始ramdisk的内容。这会在挂载真正的根文件系统之前将临时根文件系统加载到内存中。

从 Bookworm 开始，Raspberry Pi OS 默认包含一个 `initramfs` 文件。要启用初始 ramdisk，请在 xref:config_txt.adoc[`config.txt`] 中使用 xref:config_txt.adoc#auto_initramfs[`auto_initramfs`] 关键字进行配置。

[[ssh-or-ssh-txt]]
=== `ssh` 或 `ssh.txt` 

如果存在该文件，则在启动时启用 SSH。否则 SSH 默认为禁用。文件内容并不重要。即使是空文件也能启用 SSH。


NOTE: 内容无关紧要。即使是一个空文件也可以使能SSH。

=== 设备树blob文件 ( `*.dtb` )

设备树blob文件包含Raspberry Pi各种型号的硬件定义。这些文件在引导 xref:configuration.adoc#part3.1[基于检测到的Raspberry Pi模型]。

=== 内核文件 ( `*.img` )

与树莓派型号对应的各种 xref:linux_kernel.adoc#kernel[kernel] 内核文件：

|===
| 文件名 | 处理器 | 型号 | 说明

|  `kernel.img` 
| BCM2835
| Pi Zero, Pi 1
|

|  `kernel7.img` 
| BCM2836， BCM2837
| Pi Zero 2 W, Pi 2, Pi 3
| 后来的Pi 2使用BCM2837

|  `kernel7l.img` 
| BCM2711
| Pi 4， Pi 400，CM4，CM4S
| 大型物理地址扩展 (LPAE)

|  `kernel8.img` 
| BCM2837、BCM2711、BCM2712
| Pi Zero 2 W, Pi 2, Pi 3, Pi 4, Pi 400, CM4, CM4S, Pi 5
| xref:config_txt.adoc#boot-options[64位内核]。带有BCM2836的Raspberry Pi 2不支持64位内核。

|  `kernel_2712.img` 
| BCM2712
| Pi 5
| Pi 5优化的 xref:config_txt.adoc#boot-options[64-bit kernel]。
|===

NOTE: 对于运行 32 位内核的系统，`lscpu` 报告的 CPU 架构为 `armv7l`；对于运行 64 位内核的系统，`aarch64` 报告的 CPU 架构为 `armv7l`。`armv7l` 中的 `l`指的是小端 CPU 架构，而不是 `kernel7l.img` 文件名中的 `l` 所表示的 `LPAE`。

[[overlays-folder]]
=== `overlays` 文件夹

包含设备树overlay。这些用于配置各种硬件设备，例如第三方声卡。通过修改 `config.txt` 中的配置选择这些overlay。有关详细信息，请参阅 xref:configuration.adoc#part2[Device Trees, overlays and parameters]。
