== 显示

要配置 Raspberry Pi 使用非默认显示模式，请手动设置分辨率或旋转。

=== 支持 HDMI 显示器

对于大多数 HDMI 显示器，Raspberry Pi OS 使用显示器支持的最高分辨率和刷新率。

Raspberry Pi Zero、Zero W 和 Zero 2 W 有一个迷你 HDMI 端口，因此您需要迷你 HDMI 转全尺寸 HDMI 的导线或适配器。

从 Raspberry Pi 4B 开始的旗舰机型和键盘机型有两个微型 HDMI 端口，因此您需要为每台要连接的显示器准备一条微型 HDMI 转全尺寸 HDMI 的导线或适配器。在打开 Raspberry Pi 之前连接电缆。

自 Raspberry Pi 4B 开始的旗舰机型、自 CM4 开始的计算模块（CM4S 除外）以及键盘机型最多可驱动两台显示器。

4 系列设备以 60Hz 的刷新率支持高达 1080p 的分辨率，或以 30Hz 的刷新率支持两台 4K 显示器。如果将显示器连接到 `HDMI0` 端口，并在 xref:../computers/config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`] 中设置 `hdmi_enable_4kp60=1` 标志，还能以 60Hz 的刷新率驱动一台 4K 显示器。

5 系列设备无需额外配置，即可以 60hz 的刷新率支持多达两台 4K 分辨率的显示器。

[[set-resolution-and-rotation]]
=== 设置分辨率和旋转

在 Raspberry Pi 桌面上，打开 *Preferences* 菜单，选择 **Screen Configuration** 实用程序。你会看到连接到 Raspberry Pi 的显示器的图形显示。右键单击要修改的显示屏，然后选择一个选项。单击 **Apply** 并关闭 **Screen Configuration** 以保存更改。

或者, 使用以下命令打开 **Screen Configuration** 组件:
[source,console]
----
$ raindrop
----

[TIP]
====
如果你的系统不包含 `raindrop`可以使用以下命令安装：

[source,console]
----
$ sudo apt install raindrop
----

旧版本的 Raspberry Pi OS 使用名为 `arandr` 的不同屏幕配置实用程序。要卸载 `arandr`，请运行以下命令：
[source,console]
----
$ sudo apt purge arandr
----
====

=== 手动设置分辨率和旋转

==== 确定显示设备名称

要手动配置分辨率和旋转，需要知道显示设备的名称。要确定设备名称，请运行以下命令显示连接设备的信息：

[source,console]
----
$ kmsprint | grep Connector
----

==== 设置自定义分辨率

要设置自定义分辨率，请使用我们的屏幕配置工具 `raindrop`。如果您的Raspberry Pi OS安装尚未包含 `raindrop`（例如，如果您仍在使用以前的屏幕配置工具 `arandr`），您可以从 `apt` 或推荐软件GUI下载 `raindrop`。

==== 设置自定义旋转

要设置自定义分辨率，请使用我们的屏幕配置工具 `raindrop`。如果您的Raspberry Pi OS安装尚未包含 `raindrop`（例如，如果您仍在使用以前的屏幕配置工具 `arandr`），您可以从 `apt` 或推荐软件GUI下载 `raindrop`。

如果运行 Wayland 桌面合成器，可以使用 `wlr-randr` 设置自定义的显示旋转。以下命令可将显示屏旋转 0°、90°、180° 和 270°：

[source,console]
----
$ wlr-randr --output HDMI-A-1 --transform normal
$ wlr-randr --output HDMI-A-1 --transform 90
$ wlr-randr --output HDMI-A-1 --transform 180
$ wlr-randr --output HDMI-A-1 --transform 270
----

`--output` 选项指定要旋转的设备。

NOTE: 要通过 SSH 运行该命令，请添加以下前缀: `WAYLAND_DISPLAY=wayland-1`，例如 `WAYLAND_DISPLAY=wayland-1 wlr-randr --output HDMI-A-1 --transform 90`.

您还可以使用以下 `-transform` 选项之一，在旋转显示屏的同时镜像显示屏： `flipped`, `flipped-90`, `flipped-180`, `flipped-270`

=== 控制台分辨率和旋转

要更改 Raspberry Pi 在控制台模式下的分辨率和旋转，请使用 KMS 设置。更多信息，请参阅 <<kernel-command-line-cmdline-txt,configuring the kernel command line>>.
NOTE: 当使用多台显示器的控制台模式时，所有连接的显示器共享相同的旋转设置。
