== 显示

要配置 Raspberry Pi 使用非默认显示模式，请手动设置分辨率或旋转。

=== 支持 HDMI 显示器

对于大多数 HDMI 显示器，Raspberry Pi OS 使用显示器支持的最高分辨率和刷新率。

Raspberry Pi Zero、Zero W 和 Zero 2 W 有一个迷你 HDMI 端口，因此您需要迷你 HDMI 转全尺寸 HDMI 的导线或适配器。

Raspberry Pi 4、Raspberry Pi 5 和 Raspberry Pi 400 有两个微型 HDMI 端口，因此您需要为每个要连接的显示器准备一个微型 HDMI 转全尺寸 HDMI 连接线或适配器。在打开 Raspberry Pi 之前连接电缆。

Raspberry Pi 4 和 400 最多可驱动两台显示器，分辨率可达 1080p，刷新率为 60Hz。这些设备支持两台刷新率为 30Hz 的 4K 显示器。如果将显示器连接到 "HDMI0 "端口，并在 xref:../computers/config_txt.adoc#what-is-config-txt[`/boot/firmware/config.txt`] 中设置 "hdmi_enable_4kp60=1 "标志，还可以以 60Hz 的刷新率驱动一台 4K 显示器。

Raspberry Pi 5 最多可驱动两台分辨率为 4K、刷新率为 60hz 的显示器，无需额外配置。

[[set-resolution-and-rotation]]
=== 设置分辨率和旋转

==== 桌面

在 Raspberry Pi 桌面上，打开 *Preferences* 菜单，选择 **Screen Configuration** 实用程序。你会看到连接到 Raspberry Pi 的显示器的图形显示。右键单击要修改的显示屏，然后选择一个选项。单击 **Apply** 并关闭 **Screen Configuration** 以保存更改。

==== CLI

使用以下命令打开 **Screen Configuration** 实用程序：

[source,console]
----
$ arandr
----

你会看到连接到 Raspberry Pi 的显示器的图形显示。右键单击要修改的显示屏，选择一个选项。点击 **Apply** 并关闭 **Screen Configuration** 以保存更改。

=== 手动设置分辨率和旋转

[[determine-display-device-name]]
==== 确定显示设备名称

要手动配置分辨率和旋转，需要知道显示设备的名称。要确定设备名称，请运行以下命令显示连接设备的信息：

[source,console]
----
$ kmsprint | grep Connector
----

==== 设置自定义分辨率

如果运行 Wayland 桌面合成器，可以通过编辑主目录下的 `.config/wayfire.ini` 文件来设置自定义显示分辨率。编辑现有的 `[output:<device>]` 部分，或为你的 xref:configuration.adoc#determine-display-device-name[display device] 添加一个新的 `[output:<device>]` 部分（如果不存在）。要更改显示分辨率，请添加 `mode` 行。例如，以下示例显示了名为 `HDMI-A-1` 的设备的配置，其分辨率为 1080p，频率为 60Hz：

[source,ini]
----
[output:HDMI-A-1]
mode = 1920x1080@60
----

有关支持的模式和 `mode` 语法，请参阅 https://github.com/WayfireWM/wayfire-wiki/blob/master/Configuration.md#output-configuration[Wayfire文档]。

在 `/usr/share/greeter.ini` 中添加相同的配置块，以配置登录屏幕的分辨率。

==== 设置自定义旋转

如果运行 Wayland 桌面合成器，可以使用 `wlr-randr` 设置自定义的显示旋转。以下命令可将显示屏旋转 0°、90°、180° 和 270°：

[source,console]
----
$ wlr-randr --output HDMI-A-1 --transform normal
$ wlr-randr --output HDMI-A-1 --transform 90
$ wlr-randr --output HDMI-A-1 --transform 180
$ wlr-randr --output HDMI-A-1 --transform 270
----

`--output` 选项指定要旋转的设备。

NOTE: 要通过 SSH 运行该命令，请添加以下前缀: `WAYLAND_DISPLAY=wayland-1`，例如 `WAYLAND_DISPLAY=wayland-1 wlr-randr --output HDMI-A-1 --transform 90`.

您还可以使用以下 `-transform` 选项之一，在旋转显示屏的同时镜像显示屏： `flipped`, `flipped-90`, `flipped-180`, `flipped-270`

另外，你也可以通过编辑主目录下的 `.config/wayfire.ini` 文件来旋转显示屏。编辑现有的 `[output:<device>]` 部分，如果 xref:configuration.adoc#determine-display-device-name[display device] 部分不存在，则为其添加新的 `[output:<device>]`  部分。要旋转显示屏，请添加 `transform` 行。例如，以下示例显示了名为 `HDMI-A-1` 的设备的配置，其分辨率为 1080p，频率为 60Hz，变换角度为 270°：

[source,ini]
----
[output:HDMI-A-1]
mode = 1920x1080@60
transform = 270
----

Wayland 支持以下 `transform` 选项：

* `normal`
* `90`
* `180`
* `270`

在 `/usr/share/greeter.ini` 中添加相同的配置块，以配置登录屏幕的旋转。

=== 控制台分辨率和旋转

要更改 Raspberry Pi 在控制台模式下的分辨率和旋转，请使用 KMS 设置。更多信息，请参阅 <<kernel-command-line-cmdline-txt,configuring the kernel command line>>.
NOTE: 当使用多台显示器的控制台模式时，所有连接的显示器共享相同的旋转设置。
