[[configure-uarts]]
== 配置 UART

Raspberry Pi 上有两种类型的 UART - http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0183g/index.html[PL011] 和 mini UART。PL011 是一款功能强大、广泛兼容 16550 的 UART，而 mini UART 的功能集则有所减少。

Raspberry Pi 上的所有 UART 都仅为 3.3V - 如果将它们连接到 5V 系统，则会发生损坏。可以使用适配器连接到 5V 系统。或者，可以从各种第三方获得低成本的 USB 转 3.3V 串行适配器。

=== Raspberry Pi Zero、1、2 和 3

Raspberry Pi Zero、1、2 和 3 各包含两个 UART，如下所示：

|===
| 名称 | 类型

| UART0
| PL011

| UART1
| mini UART
|===

[[raspberry-pi-4-and-400]]
=== Raspberry Pi 4 和 400

Raspberry Pi 4 Model B 和 400 有另外四个 PL011，默认情况下处于禁用状态：

|===
| 名称 | 类型

| UART0
| PL011

| UART1
| mini UART

| UART2
| PL011

| UART3
| PL011

| UART4
| PL011

| UART5
| PL011
|===

=== Raspberry Pi 5

Raspberry Pi 5 有另外四个 PL011，默认情况下处于禁用状态：

|===
| 名称 | 类型

| UART0
| PL011

| UART1
| PL011

| UART2
| PL011

| UART3
| PL011

| UART4
| PL011

|===

Raspberry Pi 5 没有Mini-UART。

[[cm1-cm3-cm3-and-cm4]]
=== CM1、CM3、CM3+ 和 CM4

第一代计算模块以及计算模块 3 和计算模块 3+ 有两个 UART，而计算模块 4 有六个 UART，如上所述。

在所有型号的计算模块上，UART 默认处于禁用状态，可以使用设备树覆盖明确启用。您还可以指定要使用的 GPIO 引脚，例如：

[source,ini]
----
dtoverlay=uart1,txd1_pin=32,rxd1_pin=33
----

=== 主 UART

在 Raspberry Pi 上，GPIO 14（发送）和 15（接收）上有一个 UART 被选择为主 UART。默认情况下，这也是 Linux 控制台可能使用的 UART。请注意，GPIO 14 是 GPIO 针座上的第 8 针，而 GPIO 15 是第 10 针。

在 Raspberry Pi 5 上，主 UART 为调试接头。

[[secondary-uart]]
=== 辅助 UART

辅助 UART 通常不存在于 GPIO 连接器上。默认情况下，辅助 UART 连接到组合无线 LAN/蓝牙控制器的蓝牙侧，在包含此控制器的型号上。


=== 主 UART 和辅助 UART

下表总结了各种 Raspberry Pi 设备上 UART 的分配：

|===
| 型号 | 主/控制台 | 辅助/蓝牙

| Raspberry Pi Zero
| UART0
| UART1

| Raspberry Pi Zero W / Raspberry Pi Zero 2 W
| UART1
| UART0

| Raspberry Pi 1
| UART0
| UART1

| Raspberry Pi 2
| UART0
| UART1

| Raspberry Pi 3
| UART1
| UART0

| Compute Module 3 & 3+
| UART0
| UART1

| Raspberry Pi 4
| UART1
| UART0

| Raspberry Pi 5
| UART10
| <dedicated UART>
|===

Raspberry Pi OS 上的 Linux 设备：

|===
| Linux 设备 | 说明

|  `/dev/ttyS0` 
| mini UART

|  `/dev/ttyAMA0` 
| first PL011 (UART0)

|  `/dev/serial0` 
| primary UART

|  `/dev/serial1` 
| secondary UART

|  `/dev/ttyAMA10` 
| Raspberry Pi 5 Debug UART
|===

`/dev/serial0` 和 `/dev/serial1` 是指向 `/dev/ttyS0` 或 `/dev/ttyAMA0` 的符号链接。

在 Raspberry Pi 5 上， `/dev/serial0` 是指向 `/dev/ttyAMA10` 的符号链接。

由于 Bookworm 中的更改，默认情况下不存在 `/dev/serial1` 。 您可以通过在 `config.txt` 中设置以下值来重新启用 `serial1` ：

[source,ini]
----
dtparam=krnbt=off
----

TIP: 此选项将来可能无法在所有型号上工作。 仅在您的用例没有其他替代方案时才使用此选项。

[[mini-uart-and-cpu-core-frequency]]
=== Mini-UART 和 CPU 核心频率

NOTE: 如果 mini UART 是主 UART 或蓝牙被禁用，则默认情况下会禁用 mini UART。

为了使用Mini-UART，您需要将 Raspberry Pi 配置为使用固定的 VPU 核心时钟频率。这是因为Mini-UART 时钟与 VPU 核心时钟相连，因此当核心时钟频率发生变化时，UART 波特率也会发生变化。可以将 `enable_uart` 和 `core_freq` 设置添加到 `config.txt` 以更改Mini-UART 的行为。下表总结了可能的组合：

|===
| Mini UART set to | core clock | Result

| primary UART
| variable
| mini UART disabled

| primary UART
| fixed by setting  `enable_uart=1` 
| mini UART enabled, core clock fixed to 250MHz, or if `force_turbo=1` is set, the VPU turbo frequency

| secondary UART
| variable
| mini UART disabled

| secondary UART
| fixed by setting  `core_freq=250` 
| mini UART enabled
|===

The default state of the `enable_uart` flag depends on which UART is the primary UART:

|===
| Primary UART | Default state of enable_uart flag

| mini UART
| 0

| first PL011 (UART0)
| 1
|===

[[disabling-the-linux-serial-console]]
=== 禁用Linux串行控制台

默认情况下，主通用异步收发设备被分配到Linux控制台。如果您希望将主通用异步收发设备用于其他目的，您必须重新配置Raspberry Pi OS。这可以通过使用 xref:configuration.adoc#raspi-config[raspi-config] 来完成：

* 启动 raspi-config:  `sudo raspi-config` 
* 选择选项 3 - Interface Options
* 选择选项 P6 - Serial Port
* 在提示 `Would you like a login shell to be accessible over serial?` 时，回答 "否"
* 在提示 `Would you like the serial port hardware to be enabled?` 时，回答 "是"
* 退出 `raspi-config` 并重启 Raspberry Pi 以使更改生效

[[enabling-early-console-for-linux]]
=== 为Linux启用早期控制台

尽管Linux内核在引导过程中相对较早地启动了UART，但在基础设施的一些关键部分启动之后仍然需要很长时间。如果不访问当时的内核日志消息，则很难诊断这些早期阶段的故障。要启用对其中一个UART的 `earlycon` ，可根据哪个 UART 是主 UART，在 `cmdline.txt` 中添加以下选项之一：

对于 Raspberry Pi 5， `earlycon` 输出只出现在 3 针调试连接器上，配置如下：

[source,ini]
----
earlycon=pl011,0x107d001000,115200n8
----

对于Raspberry Pi 4、400 和 Compute Module 4:

[source,ini]
----
earlycon=uart8250,mmio32,0xfe215040
earlycon=pl011,mmio32,0xfe201000
----

对于Raspberry Pi 2、Pi 3 和 Compute Module 3:

[source,ini]
----
earlycon=uart8250,mmio32,0x3f215040
earlycon=pl011,mmio32,0x3f201000
----

对于Raspberry Pi 1、Pi Zero 和 Compute Module 1:

[source,ini]
----
earlycon=uart8250,mmio32,0x20215040
earlycon=pl011,mmio32,0x20201000
----

波特率默认为115200bps。

NOTE: 选择错误的早期控制台会阻碍Raspberry Pi启动。

[[uarts-and-device-tree]]
=== UART和设备树

各种通用异步收发设备树覆盖定义可以在 https://github.com/raspberrypi/linux[内核GitHub] 中找到。两个最有用的overlay https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/overlays/disable-bt-overlay.dts[`disable-bt` ] 和 https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/overlays/miniuart-bt-overlay.dts[ `miniuart-bt`]。

`disable-bt` 禁用蓝牙设备并使第一个PL011（UART0）成为主要的通用异步收发设备。您还必须禁用初始化调制解调器的系统服务，使其不连接到通用异步收发设备，使用 `sudo systemctl disable hciuart` 。

`miniuart-bt` 将蓝牙功能切换为使用 mini UART，并使第一个PL011（UART0）成为primary UART。请注意，这可能会降低最大可用波特率（请参阅下面的迷你通用步异步收发设备限制）。您还必须使用 `force_turbo=1` 或 `core_freq=250` 将VPU核心时钟设置为固定频率。

overlay `uart2`、 `uart3`、 `uart4` 和 `uart5` 用于在Raspberry Pi 4上启用另外四个UART。文件夹中还有其他通用异步收发设备特定的overlay。有关设备树overlay的详细信息，请参阅 `/boot/firmware/overays/README` ，或运行 `dtoverlay-h overlay-name` 以获取描述和使用信息。

您可以在config.txt文件中添加一行以应用 xref:configuration.adoc#device-trees-overlays-and-parameters[Device Tree overlay]。请注意，文件名的 `-overlay.dts` 部分已被删除。例如：

[source,ini]
----
dtoverlay=disable-bt
----

[[pl011-and-mini-uart]]
=== PL011和 mini-UART

PL011 UART和 mini-UART有一些区别。

 mini-UART的FIFO较小。加上缺乏流量控制，这使得它更容易在更高的波特率下丢失字符。它的能力通常也不如PL011，主要是因为它的波特率链接到 VPU 时钟速度。

与PL011相比，微型通用异步收发设备的具体缺陷是：

* 无断线检测
* 无成帧错误检测
* 无奇偶校验位
* 无接收超时中断

 mini-UART和PL011的BCM2835实现都没有DCD、DSR、DTR或RI信号。

有关mini UART的更多文档，请参见 https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf[SoC外围设备文档]。
